Fix ECE exception when payment fails
Automattic/woocommerce-payments pull request #10048
Opened 2024-12-30 19:28 UTC by cesarcosta99

Fixes #9990.

#### Changes proposed in this Pull Request

This PR removes the `payment.paymentFailed` call when aborting the ECE payment. I went with this approach because it looks like we're mistakenly calling that function.

The error message ("Ensure you are either submitting a payment or calling paymentFailed() once per confirm event") indicates an integration error. I confirmed we're calling that function just once, and I've simulated errors before and after confirming the intent, and in all cases the exception was generated.

According to the [documentation](https://docs.stripe.com/js/elements_object/express_checkout_element_confirm_event), we're only supposed to call this before calling `stripe.confirmPayment`, but we don't use that API, we process payments through intents in the backend. That makes me conclude we have an integration error because we're using different APIs, and the only solution is to remove that call, which has no effect.

#### Testing instructions

**Setup**

1. Checkout to this branch.
2. Run `npm run build:client`.

**Regression test: Ensure ECE still works as expected**

1. As a shopper, pay for any kind of product with ECE (Google Pay/Apple Pay).
4. Confirm payment is successful.

**Test: Ensure ECE fails gracefully**

1. Modify [the backend](https://github.com/Automattic/woocommerce-payments/blob/009bc4416b6a3d74efe68e79b7ae2c5195d43531/includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php#L70) to fail the payment, or modify [the JS](https://github.com/Automattic/woocommerce-payments/blob/cf6d2c1f5de1df9d60c9f040757fd35a79525b35/client/express-checkout/event-handlers.js#L87) to simulate an error.
2. Confirm all the following:
- Error message is correctly displayed in the frontend.
- No JS errors in the console.
- No Stripe intent is created and confirmed (if you modify the backend, make sure it's before the processing).

**Test: Ensure tokenized ECE works as expected**

1. As a merchant, go to the WCPay Dev Tools.
2. Enable the Cart-Token implementation for ECE feature flag and save.
5. Repeat both tests above, they must show the same results.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-12-30 19:32 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `10048` or branch name `fix/9990-payment-failed-exception` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9990-payment-failed-exception) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 93ed0233e7d36551c8bd43d3f91908f4c40185fd
- Build time: 2025-01-03 14:54:37 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2025-01-02 18:47 UTC, asumaran requested changes
LGTM! Tests as expected. JS error is gone. Just left a minor comment for you @cesarcosta99

2025-01-02 18:47 UTC, asumaran commented on client/express-checkout/index.js
> +		abortPayment: async ( message ) => {
Why was the `async` keyword added here? I don’t see any asynchronous operations being performed inside this method.

2025-01-03 14:52 UTC, cesarcosta99 commented on client/express-checkout/index.js
> +		abortPayment: async ( message ) => {
Most likely it was a leftover, thanks for catching it. Fixed in 93ed023.

2025-01-03 14:57 UTC, asumaran approved these changes

2025-01-03 18:15 UTC, merged