Subscriptions compatibility for order tracking updates
Automattic/woocommerce-payments pull request #1312
Opened 2021-02-10 15:39 UTC by dmallory42

Fixes 585-gh-Automattic/woocommerce-payments-server 

#### Changes proposed in this Pull Request

Adds Subscription Compatibility for Order Update Events

Some order updates were not getting tracked because the child-orders which are created for a Subscription do not have an `intent_id` attached. This adds logic to the Subscriptions compatibility WCPay gateway to get the details of the parent order when a subscription is updated.

#### Testing instructions

- Create a subscription order by purchasing it via the checkout. 
- Go to the account of the user who purchased the order (**My Account -> Subscriptions**) and make a change to the subscription (for example, cancelling it)
- Verify that this created an update order event in the **Tools -> ActionScheduler** section (this should be visible in the 'Pending' jobs section).

*

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

2021-02-18 13:59 UTC, dmallory42 commented on includes/class-wc-payments-action-scheduler-service.php
> +			array_merge( $order->get_data(), [ '_payment_method_id' => $payment_method ] ),
Thanks, I ended up rewriting some logic and I guess that the server PR must have been outdated. Sorry about that, resolved on the latest server commit.

2021-02-18 14:00 UTC, dmallory42 commented on includes/class-wc-payments-action-scheduler-service.php
>  			true
Yep, good thinking. They need to be different functions to make it clear in ActionScheduler which job is being run, but agree that most of the logic can be extracted into a helper function, will update this.

2021-02-18 14:04 UTC, dmallory42 commented
Thanks for your comments @marcinbot. I've just made an update which should resolve the issues relating to free trials and subscription sub-orders. :)

2021-02-18 14:18 UTC, luizreis commented on includes/class-wc-payment-gateway-wcpay.php
> +		$order->update_meta_data( '_payment_method_token', $payment_method );
I think `_payment_method_token` might create some confusion with the WC tokens. Would you mind changing this to `_payment_method_id` here and in the server PR?

2021-02-18 20:20 UTC, luizreis requested changes
@dmallory42 - thanks for the changes! It's looking great. I tested this on my local site and all works as expected.

However, some unit tests are failing. It looks like the `WC_Payments_API_Client::track_order` mock is returning a boolean, but the code expects an array. Could you double-check if that's correct?

2021-02-19 10:38 UTC, dmallory42 commented
Thanks @luizreis, I'd made a change to how the function worked and forgot to update the test. Fixed now.

2021-02-19 14:07 UTC, luizreis approved these changes
LGTM! :shipit:

2021-02-19 15:58 UTC, merged