Send more data when creating/updating customers
Automattic/woocommerce-payments pull request #1336
Opened 2021-02-16 17:09 UTC by marcinbot

Fixes 506-gh-Automattic/woocommerce-payments-server

#### Changes proposed in this Pull Request

- Added `WC_Payments_Customer_Service::map_customer_data` to map Woo Orders and Woo Customers to Stripe-acceptable data
- Updated the gateway to use that method when creating or updating customers in the backend

#### Testing instructions

* Checkout the Server PR
* Checkout as a logged-in user
* Checkout as a logged-out user
* Add a payment method as a brand new user on the site
* Check your Stripe dashboard - all of the customers should have extra data set on them, not just name/email

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

2021-02-17 13:23 UTC, kalessil commented on includes/class-wc-payments-customer-service.php
> +	public function create_customer_for_user( $user, $customer_data ) {
We can use parameter type hints here.

2021-02-17 13:30 UTC, kalessil requested changes
Did the first review round, will do functional after we tweak some code fragments.

2021-02-17 13:30 UTC, kalessil commented on includes/class-wc-payments-customer-service.php
> +	public function update_customer_for_user( $customer_id, $user, $customer_data ) {
Same here: parameter type hints + return type hint.

2021-02-17 13:30 UTC, kalessil commented on includes/class-wc-payments-customer-service.php
> +	public static function map_customer_data( $wc_order = null, $wc_customer = null ) {
Same here.

2021-02-17 13:30 UTC, kalessil commented on includes/class-wc-payments-customer-service.php
> +	private function recreate_customer( $user, $customer_data ) {
And here.

2021-02-17 13:30 UTC, kalessil commented on includes/wc-payment-api/class-wc-payments-api-client.php
> +	public function create_customer( $customer_data ) {
And here

2021-02-17 13:30 UTC, kalessil commented on includes/class-wc-payments-customer-service.php
> +			$data['shipping'] = [
That looks inconsistent, even if data are slightly duplicated, will it be possible to introduce `billing` analog (likely instead of `address`)?

2021-02-17 15:10 UTC, kalessil commented on includes/class-wc-payments-customer-service.php
> +			$data['shipping'] = [
I see, now. Thanks for clarifying.

2021-02-17 15:12 UTC, kalessil commented on includes/class-wc-payments-customer-service.php
> +	public function update_customer_for_user( $customer_id, $user, $customer_data ) {
Thanks!

I agree - normally I request the type hints for methods when we are changing the signature. Making it globally not an option at the moment - we need to reach some critical mass of type-hinted interfaces.

2021-02-17 15:14 UTC, kalessil commented
@marcinbot : the changes are looking great, on functional testing.

2021-02-18 15:25 UTC, dmallory42 approved these changes
Code looks good to me, and works well as described in the testing instructions. 👍

2021-02-18 15:27 UTC, merged