Fix the build for IE11
Automattic/woocommerce-payments pull request #1384
Opened 2021-03-10 12:08 UTC by DanReyLop

A few days ago, @reykjalin thought that maybe the switch to TypeScript had broken the build for older browsers. That fear wasn't entirely unfounded. The switch from Babel to TypeScript didn't break anything, but the upgrade from Webpack 4 to Webpack 5 (done months ago) did. WCPay hasn't been useable in IE11 all this time.

The problem is that Webpack 5 now can output its runtime using ES6, and that's the default option ([docs](https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11)). To force it to use ES5, we must specify a `BROWSERSLIST` config. There are many ways to do so, I just mirrored exactly [what WC-Admin does](https://github.com/woocommerce/woocommerce-admin/blob/main/.browserslistrc) (which includes [Gutenberg's config](https://github.com/WordPress/gutenberg/blob/trunk/packages/browserslist-config/index.js)).

Just for good measure, I also fixed [a IE11 error in WC Core](https://github.com/woocommerce/woocommerce/pull/29322) :)

Note that the IE11 experience in WC-Admin and WCPay is still incredibly broken. See a couple of examples:
<img width="745" alt="Screenshot 2021-03-09 at 23 21 34" src="https://user-images.githubusercontent.com/1715800/110627007-5b7f9780-8199-11eb-9ce0-681a98879d8a.png">
<img width="539" alt="Screenshot 2021-03-09 at 22 51 04" src="https://user-images.githubusercontent.com/1715800/110627013-5d495b00-8199-11eb-8c3a-a7f35f960cde.png">

2021-03-11 07:02 UTC, reykjalin requested changes
Just some minor comments 🙂 

I don't have an IE11 setup, so I just did a quick scan of all the WCPay pages and tried a test payment. Everything seems to work, so let's just address the comments and we're good 👏

2021-03-11 12:57 UTC, DanReyLop commented on webpack.config.js
> -	devtool: 'source-map',
`devtool` is already set a few lines above: https://github.com/Automattic/woocommerce-payments/blob/trunk/webpack.config.js#L9

Not directly related to the IE11 fix though.

2021-03-11 12:58 UTC, DanReyLop commented on package.json
> +    "@wordpress/browserslist-config": "^3.0.1",
Done

2021-03-11 13:02 UTC, merged

2021-03-12 07:59 UTC, reykjalin commented on webpack.config.js
> -	devtool: 'source-map',
omg, I can't believe I didn't see that when I added this on line 107 🤦‍♂️ 

Thanks for catching this!

2021-03-12 21:22 UTC, ricardo commented
Apparently this has introduced an error in settings.js:

```
Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
```

I didn't have the chance to dig into why it happens yet, but at least nothing breaks for me, it's just the error.