Fix: 1719 Columns are misaligned on Payments->Transactions/Disputes page
Automattic/woocommerce-payments pull request #1742
Opened 2021-05-06 21:35 UTC by naman03malhotra

Fixes #1719 

#### Changes proposed in this Pull Request
- override alignment for transactions list page
- override alignment for disputes list page

#### After fix

![image](https://user-images.githubusercontent.com/15019298/117368030-9aec0b00-aee0-11eb-953f-e3ef9a08ac67.png)
![image](https://user-images.githubusercontent.com/15019298/117368061-a7706380-aee0-11eb-8f96-cc50c914d41b.png)

#### Testing instructions
- checkout to `fix/1719-columns-misaligned`
- visit transactions and dispute pages
- Items should be aligned now.
-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

2021-05-07 06:06 UTC, naman03malhotra commented on changelog.txt
> +* Fix - Columns are misaligned on Payments->Transactions/Disputes page #1719.
Discussion to include the issue number in changelog is happening here: https://github.com/Automattic/woocommerce-payments/pull/1741#discussion_r627920439

2021-05-07 15:37 UTC, shendy-a8c requested changes
I tested and worked as expected. I left some feedback.

2021-05-07 15:37 UTC, shendy-a8c commented on client/disputes/style.scss
> +.disputes-list {
I wonder if this CSS class is better prefixed with `wcpay-` like the other classes below it.

2021-05-10 04:01 UTC, shendy-a8c approved these changes
LGTM.

2021-05-10 09:55 UTC, merged