Fix: #1719 Columns are misaligned on Payments->Deposits
Automattic/woocommerce-payments pull request #1838
Opened 2021-05-17 20:44 UTC by naman03malhotra

Fixes https://github.com/Automattic/woocommerce-payments/issues/1719#issuecomment-838517662

I had to reopen #1719 as GlobalStep observed misalignment on the deposits page as per the above comment.

#### Changes proposed in this Pull Request
- Override alignment for table header on the deposits list page.
- Slight adjustment in the transactiond table header margin.

After fix:
![image](https://user-images.githubusercontent.com/15019298/118553684-449f8780-b77e-11eb-972a-bf7451744fa1.png)
![image](https://user-images.githubusercontent.com/15019298/118553713-4ec18600-b77e-11eb-9e7a-9538e511468d.png)

#### Testing instructions
- Checkout to `fix/1719-desposit-col-alignment`
- Visit deposits pages and transactions page
- Columns should be aligned now.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

2021-05-18 11:29 UTC, kalessil commented
Hey @naman03malhotra, looks much better now!

Found a case related to currency conversion marker rendering (div with class converted-amount is getting added before the amount in the case): 
![Screenshot from 2021-05-18 13-25-11](https://user-images.githubusercontent.com/1577185/118643283-a098f900-b7dc-11eb-958c-2d8c843a1c76.png)

Would you please take a look into it?

2021-05-18 11:35 UTC, kalessil requested changes
See the screenshot.

2021-05-19 11:56 UTC, naman03malhotra commented
> Found a case on transactions listing related to currency conversion marker rendering (div with class converted-amount is getting added before the amount in the case)

Thanks, @kalessil for this, fixed it in https://github.com/Automattic/woocommerce-payments/pull/1838/commits/8c6f2cc9d543b8f984092abff202663fdd0de46f.
![image](https://user-images.githubusercontent.com/15019298/118807896-7b80b500-b8c6-11eb-90a7-a541346b3b1d.png)

2021-05-19 13:09 UTC, kalessil approved these changes
LGTM, :shipit: !

2021-05-19 13:13 UTC, kalessil commented
@naman03malhotra: this PR is approved, great job here! Would you please rebase it, to ensure the failed tests are getting green?

2021-05-19 13:28 UTC, naman03malhotra commented
> Would you please rebase it, to ensure the failed tests are getting green?

@kalessil looks like this \\/ workflow is failing for other PRs as well, the fix is not yet in the develop branch.
https://github.com/Automattic/woocommerce-payments/pull/1838/checks?check_run_id=2620519571

2021-05-19 14:08 UTC, kalessil commented
@naman03malhotra , oh I see now. Go ahead then!

2021-05-19 15:41 UTC, merged