Fixed Transaction listing to show deposit date when available
Automattic/woocommerce-payments pull request #1996
Opened 2021-06-02 09:02 UTC by jessy-p

Fixes #584 

#### Changes proposed in this Pull Request

The "transaction" has estimated or actual deposit date on the 'available_on' field, the current code was using the 'data_available' field.

- Changed code to use the 'available_on' field of transaction
- Changed the test data which was setting the 'date_available' field.

#### Testing instructions

1. Go to Payment >> Transactions.
2. Transactions that have deposit dates, should show the deposit date in the last column

<img width="1672" alt="Screenshot 2021-06-02 at 2 17 59 PM" src="https://user-images.githubusercontent.com/32092402/120451561-2e650e80-c3af-11eb-8555-b7ddb777d206.png">

-------------------

- [x] Added changelog entry (or does not apply)
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

2021-06-02 09:06 UTC, jessy-p commented
@LevinMedia 
After this fix, as all transactions have a deposit date, either estimated or actual, all the rows show the date. When should we show "Deposit Details" and "Pending"? Should we differentiate between the transactions with an estimated Deposit Date and transactions with actual deposits?

2021-06-03 18:42 UTC, LevinMedia commented
@jessy-p Thanks for tackling this issue! With this addition, we no longer need the "deposit details" string for the deposit column. Any deposits that are estimated, or pending should say Estimated + the date in the deposit column.  

Estimated June 4, 2021

The entire string should link to the deposit details screen which that specific transaction is a part of.

2021-06-09 09:08 UTC, dmvrtx requested changes
Overall looks good, just a minor change to use translations instead of hard-coded string.

2021-06-09 09:08 UTC, dmvrtx commented on client/transactions/list/deposit.js
> +			? 'Estimated'
`'Estimated'` should be a translated string here. Use `__` similar to the removed `'Pending'` indicator.

2021-06-09 15:29 UTC, dmvrtx approved these changes
Works like a charm! 🚀

2021-06-10 04:39 UTC, merged