Add p24 as an UPE payment method
Automattic/woocommerce-payments pull request #2652
Opened 2021-08-03 16:44 UTC by tpaksu

Fixes #2651

#### Changes proposed in this Pull Request

TBD

#### Testing instructions

* TBD

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

2021-08-09 10:58 UTC, tpaksu commented
The calculations on the refunded transactions detail seem a little bit off? Don't you think? While net should be 0, it shows $-2.79 USD.

2021-08-09 18:04 UTC, jessepearson requested changes
It looks like some legacy files and changes are still in here, I noted where those were.

There was a test that wasn't updated:
client/additional-methods-setup/methods-selector/test/add-payment-methods-task.test.js

There was stuff I missed in mine that I went back and fixed after seeing yours 😀 

I think once this has develop merged into it that some of the tests will fail due to they look for specific counts to calls and array indexes.

2021-08-10 06:41 UTC, tpaksu commented on includes/payment-methods/class-p24-payment-method.php
> +		$this->currencies  = [ 'EUR', 'PLN' ];
Yes it also shows on the PLN currency. I'll check those files.

2021-08-11 07:50 UTC, tpaksu commented on includes/payment-methods/class-p24-payment-method.php
> +		$this->currencies  = [ 'EUR', 'PLN' ];
I've changed the code checking for additional currencies to support multiple currencies in both JavaScript and PHP.

2021-08-11 11:35 UTC, jessepearson commented
> The calculations on the refunded transactions detail seem a little bit off? Don't you think? While net should be 0, it shows $-2.79 USD.

Fees do not get refunded, the merchant is still charged for the transaction.

2021-08-11 11:36 UTC, tpaksu commented
> > The calculations on the refunded transactions detail seem a little bit off? Don't you think? While net should be 0, it shows $-2.79 USD.
> 
> Fees do not get refunded, the merchant is still charged for the transaction.

Oh, I didn't know that. Thanks for the clarification. Then everything's normal I guess.

2021-08-11 12:48 UTC, jessepearson requested changes
Looking good! A few more changes and I think this will be ready to merge.

2021-08-11 12:59 UTC, tpaksu commented on client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
> +			screen.queryByText( /we\'ll add EUR to your store/ )
Do we have a sigma for this, or is this something we decided? I guess we don't have the symbol in the enabled currencies array on JS side.

2021-08-11 14:50 UTC, jessepearson commented on client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
> +			screen.queryByText( /we\'ll add EUR to your store/ )
> Do we have a Figma for this, or is this something we decided?
I can't find anything where it was decided by design, so I think it was something decided on the dev side. Either way, we should get input from design on it and open another issue if needed.

2021-08-11 20:33 UTC, tpaksu commented
Now the currencies and providers are merged into a single notice box (4901c11):

![image](https://user-images.githubusercontent.com/3295/129097110-99ba8cbc-fc52-4cc7-b684-294e53249a78.png)

2021-08-11 21:33 UTC, tpaksu commented on client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
> +			screen.queryByText( /we\'ll add EUR to your store/ )
Ok I've fixed that.

2021-08-12 13:08 UTC, jessepearson commented
Noting here that I created https://github.com/Automattic/woocommerce-payments/issues/2720 to address the copy phrasing for the notice regarding adding currencies.

2021-08-12 13:31 UTC, jessepearson approved these changes
Able to place orders and perform refunds.
Transaction data shows correct in admin.
Currencies get added as they should.
Good to go 👍  :shipit:

2021-08-12 15:07 UTC, merged