Add - split discount line into variable and fixed fee
Automattic/woocommerce-payments pull request #2684
Opened 2021-08-06 15:20 UTC by naman03malhotra

Fixes #2628 

#### Changes proposed in this Pull Request
This PR further splits the discount line into two for a better UX. More context: https://github.com/Automattic/woocommerce-payments/pull/2500#issuecomment-889330454

#### Testing instructions

- Make sure you have a discount enabled. You can do so by running `wp wcpay add_fee_structure_to_account <id> --fee_structure_id=promo-1`
- Make a transaction preferably which includes int. and fx fee.
- Make sure you see fee breakdown that includes discount line.

![image](https://user-images.githubusercontent.com/15019298/128533457-ea3c325c-27c7-427c-af4c-620f0baa71e7.png)

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

2021-08-09 02:56 UTC, htdat requested changes
Looks good to me in general. I have left an inline comment and a following question: 

- Is that necessary to make changes on `package-lock.json`? IMHO, if we'd like to make changes for this file, it should be in a separate issue?

2021-08-09 12:05 UTC, naman03malhotra commented on client/payment-details/timeline/map-events.js
> +				<li>Fixed fee: { fixedRateFormatted }</li>
Ah! right, addressed here: https://github.com/Automattic/woocommerce-payments/pull/2684/commits/81931637a91be31d2b28431b37145008dbf382e3

2021-08-09 12:08 UTC, naman03malhotra commented
>Is that necessary to make changes on package-lock.json

I did a fresh install for all the node modules, you are right, we shouldn't include this, so I removed it.

2021-08-09 12:12 UTC, naman03malhotra commented
Hey @htdat 👋

Thanks for the first round of review, this is ready for the second round of review.

2021-08-10 02:16 UTC, htdat approved these changes
LGTM 🚢

2021-08-10 08:23 UTC, merged