Add Terminal Locations REST API
Automattic/woocommerce-payments pull request #2830
Opened 2021-09-02 06:52 UTC by RadoslavGeorgiev

Fixes #2784

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

2021-09-03 04:28 UTC, htdat requested changes
Great work! 

✅ Followed up test steps and worked well. 
✅ Cleared up the transient, tried to change the store name and address, got expected results. 

I've left a few inline comments to address some small issues. Other than that, things look good.

2021-09-10 14:06 UTC, RadoslavGeorgiev commented on includes/wc-payment-api/class-wc-payments-api-client.php
> +				0
It should be exactly 400. I was looking at another manual exception somewhere else in the plugin, and blindly copied the 0 from it. Fixed in https://github.com/Automattic/woocommerce-payments/pull/2830/commits/8eeca56f2dbff6a242abbbb9496b0ec71d61e8ac

2021-09-10 14:07 UTC, RadoslavGeorgiev commented on includes/wc-payment-api/class-wc-payments-api-client.php
> +		];
Makes sense. In https://github.com/Automattic/woocommerce-payments/pull/2830/commits/8eeca56f2dbff6a242abbbb9496b0ec71d61e8ac I changed the default value to an empty array, and added it to the request.

2021-09-10 14:07 UTC, RadoslavGeorgiev commented on includes/wc-payment-api/class-wc-payments-api-client.php
> +		if ( ! is_array( $address ) || ! isset( $address['country'] ) || ! isset( $address['line1'] ) ) {
That's a cleaner syntax, added in https://github.com/Automattic/woocommerce-payments/pull/2830/commits/8eeca56f2dbff6a242abbbb9496b0ec71d61e8ac 👌

2021-09-10 14:24 UTC, RadoslavGeorgiev commented
Hey @htdat,

I've addressed your comments! Could you please take another look?

2021-09-13 05:22 UTC, htdat approved these changes
> I've addressed your comments! Could you please take another look?

Thank you! 🚢 LGTM now.

2021-09-13 07:27 UTC, vbelolapotkov commented
Hey @RadoslavGeorgiev ! I've noticed some e2e tests are failing. Do you know the reason? I know sometimes they are fragile, but worth double checking before merging to avoid breaking some flows.

2021-09-13 08:08 UTC, RadoslavGeorgiev commented
@vbelolapotkov I'm not sure why that's happening. This is a completely separate endpoint, which should not affect E2E tests in any way, and I mostly see time-outs. Out of curiosity, I re-ran the tests and I'm interested to see the result in a few minutes.

2021-09-13 12:04 UTC, RadoslavGeorgiev commented
It worked after re-running the tests, **and** after bringing it up to date with `develop`, without timeouts. I think it should be fine 🤞

2021-09-13 12:04 UTC, merged