Do not set UPE billing details when changing a subscription payment method
Automattic/woocommerce-payments pull request #2951
Opened 2021-09-21 03:37 UTC by aprea

Fixes #2917

#### Changes proposed in this Pull Request

Tweaks a condition in `upe.js` to ensure the `billingDetails` UPE config is not set when changing payment methods for an existing subscription.

Prior to this change, attempting to change the payment methods for an existing subscription would result in the following error when entering new card details.

<img width="829" alt="Screen Shot 2021-09-15 at 3 43 32 pm" src="https://user-images.githubusercontent.com/1527164/134107492-05952776-f1fe-45a0-b930-7a5943f27c60.png">

#### Testing instructions

* As a Merchant, ensure UPE checkout is enabled and the WooCommerce Subscriptions plugin is installed. 
* As a Shopper, purchase any subscription product.
* Navigate to **My account → Subscriptions** and open the newly created subscription entry.
* Observe 3 buttons for “Actions”. Click “Change payment” button.
* In the second block, select “Use a new payment method” option.
* Provide `4242424242424242` as the test card number, future expiration date, and a CVC code.
* Click “Change payment method” button.
* Ensure the payment method is updated successfully.

-------------------

- [x] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

2021-09-22 06:42 UTC, chickenn00dle commented on client/checkout/classic/upe.js
> +		const isChangingPayment = getConfig( 'isChangingPayment' );
This is a nitpick and not a blocker. 

I noticed this is defined a few times in this file. Is there a reason we can't define this once in the outermost scope of the main function?

2021-09-22 06:43 UTC, chickenn00dle requested changes
Nice work @aprea!

I tested and this resolves the error that appears on the change payment method 🙌 

I just had one nitpick that can be ignored. Other than that, it looks like there are still failing tests which need to be fixed.

2021-09-22 23:56 UTC, aprea commented
Looks like the "Compatibility - WC, WP and PHP / WC compatibility (4.0.0, 5.4, 7.0) (pull_request)" check will continue failing until https://github.com/Automattic/woocommerce-payments/pull/2945 is merged

2021-09-23 00:42 UTC, chickenn00dle commented
Ah. Good catch. In that case, this LGTM 👍

2021-09-23 00:42 UTC, chickenn00dle approved these changes

2021-09-23 00:46 UTC, merged