WCPay overview - display fees per payment method
Automattic/woocommerce-payments pull request #3055
Opened 2021-10-06 12:57 UTC by dpaun1985

Fixes #2377

#### Changes proposed in this Pull Request

This PR adds fees per payment method. The actual base fees should be removed. 
All information needed already exists, as it is served by the server `/accounts` endpoint . 

#### Testing instructions
- add more than 1 payment method
- go to Payments -> Overview
- check if the fees are displayed properly for each payment method

*

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

2021-10-13 06:29 UTC, dpaun1985 commented
> @dpaun1985 I'm a bit unclear about how to test. A screenshot or two would help me navigate the changes.
> 
> For example:
> 
> > add more than 1 payment method
> 
> Where to do this?
> 
> > check if the fees are displayed properly for each payment method
> 
> Where on the Overview page to look for this?

It was a draft with the purpose to have an idea on how I started implementing the issue.
I just added more context.

2021-10-14 06:27 UTC, kalessil requested changes
Look great overall! I left few comments and will do the final review+testing once those are addressed.

2021-10-14 06:27 UTC, kalessil commented on client/components/account-status/index.js
> +			{ 0 < discounts.length ? (
Also `0 < discounts.length` -> `discounts.length` should work here.

2021-10-14 06:27 UTC, kalessil commented on client/components/account-status/account-fees/index.js
> +				if (
`{}` are missing as well.

2021-10-14 13:49 UTC, dmvrtx approved these changes
Tested with account with no discount fees and then adding a discount fee and it worked as expected.

However couldn't test it with multiple discount fees: it looks like server doesn't return them properly.

2021-10-15 09:58 UTC, anu-rock commented
LGTM :shipit: 

I've added a minor nitpicky comment.

2021-10-15 09:59 UTC, kalessil approved these changes
LGTM ! Also a suggestion from Anurag looks good.

2021-10-15 10:20 UTC, kalessil commented
@dpaun1985, please add changelog entries before merging this PR. Thanks!

2021-10-18 08:02 UTC, merged