Add admin notice to warn about deactivating WC Subscriptions
Automattic/woocommerce-payments pull request #3061
Opened 2021-10-07 06:16 UTC by james-allan

#### Changes proposed in this Pull Request

This PR contains the changes to introduce a confirmation admin notice when users click the deactivate WC Subscriptions plugin.

Project: pdjTHR-35-p2
Notice feedback discussion: pdjTHR-aF-p2 

<img width="1013" alt="Screen Shot 2021-10-07 at 3 53 14 pm" src="https://user-images.githubusercontent.com/8490476/136327477-704feb09-4325-4504-b52a-8c7c98a0590b.png">

#### Testing instructions

1. Install and activate the WC Subscriptions plugin.
2. Make sure the WCPay Subscriptions feature is switched on via **WCPay Dev tools**. https://d.pr/HjtrhT
3. Go to the **Plugins** admin screen. 
4. Click the link to **Deactivate** WooCommerce Subscriptions. 
5. On this branch you should be prompted with a popup notice.
6. Clicking **Yes, deactivate WooCommerce Subscriptions** will deactivate the plugin, cancel will close the modal and subscriptions will remain active.

If you disable the WCPay Subscriptions feature via **WCPay Dev tools**, deactivating the plugin doesn't lead to this prompt. The result of this means that if your site isn't eligible for WC Pay Subscriptions (feature flag isn't on) then this prompt isn't shown - the plugin just deactivates as normal. 

**Important note:** WCPay Subscriptions will be enabled by default on eligible stores. Later we'll introduce a setting to disable it.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

closes #2963

2021-10-07 06:18 UTC, james-allan commented
I'm unsure how to write unit tests for this one. There's a single PHP class with 3 functions. 1 is private and the other two add scripts or the modal template.

Any advice you have would be awesome!

2021-10-07 19:39 UTC, haszari commented
> I'm unsure how to write unit tests for this one. There's a single PHP class with 3 functions. 1 is private and the other two add scripts or the modal template.

Tricky! It's going to be tough and generally not that useful to test the modal. 

If there's business logic to detect that the plugin has been deactivated, and it's fairly functional, you could test that perhaps. But … there isn't any such code, it's done on front end fairly trivially. 

Personally I'm ok with no tests for code like this – the most important code to unit test is stable APIs. 

Possibly related – what are we doing to capture subs getting deactivated via other means (CLI, API, etc)? I realise we can't show a modal, but can we do anything else to warn the merchant? Happy for this to be done as follow up.

2021-10-11 05:59 UTC, james-allan commented
> what are we doing to capture subs getting deactivated via other means (CLI, API, etc)? 

yeah, this will come later. It has been briefly discussed in GH https://github.com/Automattic/woocommerce-payments/issues/2963#issuecomment-928393307 and in p2 pdjTHR-aF-p2#comment-193.

The current approach is to revisit that down the track. Essentially we could catch deactivations handled by this popup and if Subscriptions was deactivated by some other means, handle them in some other way (admin notice next time viewing the dashboard or an admin email). Not sure exactly but there are options.

2021-10-12 01:53 UTC, chickenn00dle requested changes
Nice work @james-allan!

I tested and this LGTM.

There is just a small typo and nitpick, then this is good to go (once the learn more doc has been published) 👍

2021-10-12 01:53 UTC, chickenn00dle commented on includes/subscriptions/templates/html-subscriptions-plugin-notice.php
> +								esc_html__( 'Exisiting subscriptions will %1$s%3$srenew manually%4$s%2$s - subscribers will need to log in to pay for renewal. Access to premium features will also be removed. %5$sLearn more.
Typo: Existing

2021-10-12 01:53 UTC, chickenn00dle commented on includes/subscriptions/templates/html-subscriptions-plugin-notice.php
> +								esc_html__( 'By deactivating the %1$sWooCommerce Subscriptions%2$s plugin, your store will switch to use %1$sSubscriptions powered by WooCommerce Payments%2$s.', 'woocommerce-payments' ),
Nitpick: "switch to" or "use" is redundant. We can probably remove one or the other.

...your store will switch to Subscriptions powered by..., or
...your store will use Subscriptions powered by...

2021-10-12 03:58 UTC, james-allan commented
Parking this PR until we publish accompanying doc.

2021-10-13 01:31 UTC, haszari commented
The proposed URL is `docs.woocommerce.com/document/subscriptions/deactivation/` (see docs spreadsheet/thread pbDlC7-o0-p2#comment-650). 

This PR already uses correct URL – so it's good to merge when you're ready @james-allan 🎉

2021-10-13 06:33 UTC, merged