Display hardware costs in the transaction list and details page
Automattic/woocommerce-payments pull request #3149
Opened 2021-10-19 09:10 UTC by dpaun1985

Fixes #1138 

#### Changes proposed in this Pull Request

This PR updates the transactions list to include card reader costs, and also updates the details page to display information about charges for active reader.

Changes:
- add new endpoint to fetch card reader costs
- update the transactions list to include rows with card reader costs. 
![image (1)](https://user-images.githubusercontent.com/82826872/138443728-f16883ab-61d5-4b3f-9f92-be35bb9c0fb4.png)
- update details page to display information about charges for card readers. This screen will be shown when you click the card reader row from transactions list.
<img width="1493" alt="Screenshot 2021-10-22 at 14 06 56" src="https://user-images.githubusercontent.com/82826872/138443937-db0c30cb-480a-4a66-b517-e17048b6802f.png">

#### Testing instructions

* Debit merchant account for active Card Readers used in a month 
* Go to transactions screen and check if the hardware costs are displayed as above
* Click on the hardware costs raw and check if the details are displayed correctly.

-------------------

- [ ] Added changelog entry (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

2021-10-27 08:28 UTC, kalessil reviewed
On a high level, the approach looks good and feels consistent with other client parts !

2021-10-27 14:21 UTC, dmvrtx reviewed
Overall looks good, great job! I left a couple comments in places which were not clear to me.

2021-11-15 06:54 UTC, dpaun1985 commented on includes/admin/class-wc-rest-payments-reader-charges-controller.php
> +			'/' . $this->rest_base . '/summary',
indeed. added the transaction id param.

2021-11-15 07:52 UTC, anu-rock commented
@dpaun1985 The new changes LGTM! Thanks for taking care of 'reader' → 'card reader'. 

Question - Should the route for reader charges be `payments/readers/charges`? That would help implement the design as seen here HsXXAeasBmnvvYynYC29Je-fi-2%3A2810 without further refactoring changes in this PR later. Eg. to get a list of readers attached to an account - `GET payments/readers`. Feel free to ignore if it sounds like over-engineering.

2021-11-15 09:31 UTC, dpaun1985 commented
> @dpaun1985 The new changes LGTM! Thanks for taking care of 'reader' → 'card reader'.
> 
> Question - Should the route for reader charges be `payments/readers/charges`? That would help implement the design as seen here [HsXXAeasBmnvvYynYC29Je-fi-2%3A2810](https://href.li/?https://www.figma.com/file/HsXXAeasBmnvvYynYC29Je/?node-id=2%3A2810) without further refactoring changes in this PR later. Eg. to get a list of readers attached to an account - `GET payments/readers`. Feel free to ignore if it sounds like over-engineering.

Thank you for the remark. Indeed, the naming of the route should be changed. Just pushed the changes.

2021-11-15 10:10 UTC, anu-rock approved these changes
LGTM :shipit:

2021-11-15 10:17 UTC, kalessil requested changes
Yay, this PR is shaping really great!

2 notes:
- can we add a changelog entry, please?
- When rendering fee/amount I noticed we use 'N/A', is that by design?

EDIT: the last question is only half-actual: can we display Amount as 0.0 in the corresponding currency for transactions list, please (instead of N/A)?

2021-11-15 10:54 UTC, dpaun1985 commented
> Yay, this PR is shaping really great!
> 
> 2 notes:
> 
> * can we add a changelog entry, please?
> * When rendering fee/amount I noticed we use 'N/A', is that by design?
> 
> EDIT: the last question is only half-actual: can we display Amount as 0.0 in the corresponding currency for transactions list, please (instead of N/A)?

Thank you.  Pushed the changes.

2021-11-15 14:05 UTC, kalessil approved these changes
LGTM, thanks for the amount tweak!

2021-11-16 07:45 UTC, merged