Include deposit status in Transaction exports
Automattic/woocommerce-payments pull request #3473
Opened 2021-12-06 09:14 UTC by malithsen

Fixes #2715

#### Changes proposed in this Pull Request
As mentioned in #2715, this adds a deposit_status column to Transaction exports. Additionally, this change replaces `client/deposits/strings.js` with a typescript file.
There's a separate server PR to expose deposit_status in the transaction response at 1385-gh-Automattic/woocommerce-payments-server

#### Testing instructions

*

-------------------

- [ ] Added changelog entries to both `readme.txt` and `changelog.txt` (or does not apply)
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Added testing instructions to the [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) (or does not apply)

2021-12-07 17:00 UTC, leonardola requested changes
I am able to see the deposit_status inside the response.
I am able to download the CSV and see the deposit_status inside it.
I am able to see Estimated before the date inside Payments > Transactions.
I am able to click on the deposit link and see Estimated on the link.
I am able to see Estimated inside Payments > Deposits.

There is only a minor change about a duplicated status that I commented during review.

Other than that nice job. I am still reviewing the server PR

2021-12-07 18:01 UTC, leonardola commented
Server PR is approved. After you solve the comment left during review you can merge it. I'll pre approve this

2021-12-07 18:01 UTC, leonardola approved these changes

2021-12-21 10:06 UTC, malithsen commented on client/data/transactions/hooks.ts
> +		| 'estimated';
Fixed in https://github.com/Automattic/woocommerce-payments/pull/3473/commits/994ca3926bbf9c303f10c2b32c8a1772f5370e22

2021-12-21 10:06 UTC, malithsen commented
Thanks for the review @leonardola. Now that the server change is deployed, I'm merging this as well.

2021-12-21 10:07 UTC, merged