TS migration for deposit list
Automattic/woocommerce-payments pull request #3918
Opened 2022-03-08 15:02 UTC by dpaun1985

Fixes #

#### Changes proposed in this Pull Request

Migrate JS for deposit list to TS

#### Testing instructions
- all tests should pass

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : _Add link here / 'QA Testing Not Applicable'_

2022-03-11 13:27 UTC, kalessil requested changes
Looks great! I left a few minor comments to address before we can go ahead.

2022-03-11 13:27 UTC, kalessil commented on client/deposits/list/index.tsx
> +// import { formatStringValue } from 'util';
Looks like dead code to me.

2022-03-11 13:27 UTC, kalessil commented on client/globals.d.ts
> +interface Window {
Let's drop it and use `wcTracks` instead of `window.wcTracks` where it's required.

2022-03-16 15:34 UTC, dpaun1985 commented on client/data/deposits/hooks.ts
> +	overview: unknown;
I didn't update `useDepositsOverview ` because I could not find any place where it is used and I expect to be removed at some point..

2022-03-16 16:49 UTC, mgascam approved these changes
LGTM! I did not test it though :)

2022-03-17 07:52 UTC, kalessil approved these changes
LGTM!

2022-03-17 07:54 UTC, merged