HACK week: migration to TypeScript (client/utils/currency)
Automattic/woocommerce-payments pull request #3921
Opened 2022-03-08 19:14 UTC by mgascam

Fixes #

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) : _Add link here / 'QA Testing Not Applicable'_

2022-03-10 10:33 UTC, kalessil requested changes
Nice! Left some comments around adding more types.

2022-03-10 10:33 UTC, kalessil commented on client/utils/currency/index.ts
> +const currencyNames: CurrencyNames = {
IMO we should inline the type here: `: Record< string, string >`

2022-03-10 10:33 UTC, kalessil commented on client/utils/currency/index.ts
> +} from 'wcpay/types/utils/currency';
This import should be under the internal dependencies block.

2022-03-10 10:33 UTC, kalessil commented on client/utils/currency/index.ts
> +) {
We can declare return type here.

2022-03-10 10:33 UTC, kalessil commented on client/utils/currency/index.ts
> +const appendCurrencyCode = ( formatted: string, currencyCode: string ) => {
We can declare return type here.

2022-03-10 10:33 UTC, kalessil commented on client/utils/currency/index.ts
> +function removeCurrencySymbol( formatted: string ) {
We can declare return type here.

2022-03-10 10:33 UTC, kalessil commented on client/utils/currency/index.ts
> +function trimEndingZeroes( formattedCurrencyAmount = '' ) {
We can declare return type here.

2022-03-10 10:33 UTC, kalessil commented on client/utils/currency/index.ts
> +) {
We can declare return type here.

2022-03-10 15:13 UTC, mgascam commented on client/utils/currency/index.ts
> +const appendCurrencyCode = ( formatted: string, currencyCode: string ) => {
Done

2022-03-10 15:13 UTC, mgascam commented on client/utils/currency/index.ts
> +function trimEndingZeroes( formattedCurrencyAmount = '' ) {
Done

2022-03-10 15:13 UTC, mgascam commented on client/utils/currency/index.ts
> +) {
Done

2022-03-11 10:40 UTC, kalessil approved these changes
LGTM!

2022-03-11 10:57 UTC, merged