Extend create intentions endpoint
Automattic/woocommerce-payments pull request #4354
Opened 2022-06-16 10:06 UTC by dpaun1985

Fixes #4196 

#### Changes proposed in this Pull Request
Implement support for payment_method_types, metadata, customer and capture_method parameters.

#### Testing instructions

* create an order
* make an api call to `payments/orders/<order_id>/create_terminal_intent` endpoint with `payment_methods`, `metadata` and `customer_id` fields
* check the new created payment intent . The payment methods, metadata and customer should have been updated.
<img width="945" alt="Screenshot 2022-06-16 at 13 05 16" src="https://user-images.githubusercontent.com/82826872/174047094-fa2dec72-6132-4a48-959d-3cef685f2978.png">

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2022-06-16 12:30 UTC, anu-rock commented on includes/class-wc-payments-order-service.php
> +				throw new \Exception( 'Invalid param \'payment_methods\'!' );
Should we instead return a more specific message like "one or more payment methods are not supported."

2022-06-16 12:32 UTC, anu-rock commented on tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
> +		$this->assertEquals( 500, $data['status'] );
assertSame :)

2022-06-16 12:33 UTC, anu-rock approved these changes
LGTM ✅

2022-06-16 12:34 UTC, anu-rock commented
We should also update the API docs at https://github.com/Automattic/woocommerce-payments/blob/develop/docs/rest-api/source/includes/wp-api-v3/order.md

2022-06-17 06:46 UTC, kalessil commented on changelog/add-extend-create-intentions-endpoint
> +IPP: Extend terminal intent creation to support payment_method_types, metadata, customer and capture_method parameters.
Can we expand the abbreviation here, please?

2022-06-17 06:46 UTC, kalessil commented on tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
> +		$this->assertEquals( 500, $data['status'] );
Here and  in the new test case, `assertEquals` -> `assertSame`, please.

2022-06-17 06:46 UTC, kalessil commented on includes/constants/class-payment-method.php
> +	const ALLOWED_PAYMENT_METHODS = [
In context of IPP, we only support CARD_PRESENT and INTERAC_PRESENT.

2022-06-17 06:46 UTC, kalessil commented on includes/class-wc-payments-order-service.php
> +		if ( null === $request->get_param( 'capture_method' ) ) {
I'd suggest to introduce a local variable for value of `$request->get_param( 'capture_method' )`.

2022-06-17 06:46 UTC, kalessil commented on includes/class-wc-payments-order-service.php
> +		if ( null === $request->get_param( 'payment_methods' ) ) {
I'd suggest to introduce a local variable for value of `$request->get_param( 'payment_methods' )`.

2022-06-17 13:10 UTC, dmvrtx approved these changes
Looks good to me! Vlad beat me with naming suggestion 🙂

2022-06-17 13:19 UTC, kalessil requested changes

2022-06-17 13:19 UTC, kalessil commented on docs/rest-api/source/includes/wp-api-v3/order.md
> +### Optional parameters
Lovely, thanks for updating the docs!

2022-06-17 13:19 UTC, kalessil commented on includes/class-wc-payments-order-service.php
> +	public function get_terminal_intent_capture_method( $request, string $default_value = 'manual' ) : string {
This method doesn;t belong to the service (same for the previous one). Perhaps it can be moved into the controller?

2022-06-17 16:07 UTC, mgascam commented
I am getting a 500 error when I call `payments/orders/<order_id>/create_terminal_intent`

`2022-06-17T16:01:01+00:00 ERROR Failed to create an intention via REST API: Exception: One or more payment methods are not supported! in /var/www/html/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-order-service.php:820
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce-payments/includes/admin/class-wc-rest-payments-orders-controller.php(265): WC_Payments_Order_Service->get_terminal_intent_payment_method(Object(WP_REST_Request))
#1 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1143): WC_REST_Payments_Orders_Controller->create_terminal_intent(Object(WP_REST_Request))
#2 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(990): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/v3/payments...', Array, NULL)
#3 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(414): WP_REST_Server->dispatch(Object(WP_REST_Request))
#4 /var/www/html/wp-includes/rest-api.php(394): WP_REST_Server->serve_request('/wc/v3/payments...')
#5 /var/www/html/wp-includes/class-wp-hook.php(307): rest_api_loaded(Object(WP))
#6 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)
#7 /var/www/html/wp-includes/plugin.php(524): WP_Hook->do_action(Array)
#8 /var/www/html/wp-includes/class-wp.php(398): do_action_ref_array('parse_request', Array)
#9 /var/www/html/wp-includes/class-wp.php(770): WP->parse_request('')
#10 /var/www/html/wp-includes/functions.php(1330): WP->main('')
#11 /var/www/html/wp-blog-header.php(16): wp()
#12 /var/www/html/index.php(17): require('/var/www/html/w...')
#13 {main}`

The body of the request I used:
`{"payment_methods": ["card","card_present"], "metadata": {"test": "test"}, "customer_id": "cus_LMXhn1nDFTimOf"}`

Please note that the request is successful when I remove 'card' from the payment_methods array i.e:
`{"payment_methods": ["card_present"], "metadata": {"test": "test"}, "customer_id": "cus_LMXhn1nDFTimOf"}`

In that case, the payment_intent contains the correct customer and metadata in the Stripe dashboard.

Am I doing something wrong maybe? Or is this expected errror? Thanks

2022-06-17 18:00 UTC, dmvrtx commented
> I am getting a 500 error when I call `payments/orders/<order_id>/create_terminal_intent`

@mgascam, I believe that's expected. This change is designed for In-Person Payments and it accepts only two payment methods related to IPP:

```php
	const IPP_ALLOWED_PAYMENT_METHODS = [
 		self::CARD_PRESENT,
 		self::INTERAC_PRESENT,
 	];
```

2022-06-20 11:20 UTC, mgascam approved these changes
LGTM!

2022-06-20 12:28 UTC, kalessil approved these changes
LGTM!

2022-06-20 12:31 UTC, merged