Fix errors for apple pay registration
Automattic/woocommerce-payments pull request #4551
Opened 2022-08-09 11:41 UTC by dpaun1985

Fixes #4511

#### Changes proposed in this Pull Request
- when merchant is not in the Apple Pay [supported country list](https://support.apple.com/en-us/HT207957
), or `apple-developer-merchantid-domain-association` file has different permissions than 644, the apple domain registration is not called anymore
- for the conditions above, a notice is shown in the WooCommerce Payments admin panel

<img width="1733" alt="Screenshot 2022-08-09 at 14 37 20" src="https://user-images.githubusercontent.com/82826872/183638041-92a07470-717e-47f0-b1a8-5265774d169b.png">

#### Testing instructions
1. Set the merchant country other than the ones listed in https://support.apple.com/en-us/HT207957 .
2. Enable Apple Pay
3. `Apple Pay: You are not in the countries and regions that support Apple Pay. You can find a full list of countries and regions at https://support.apple.com/en-us/HT207957` should be displayed in Payment methods panel
4. Rename `docker/wordpress/.well-known/apple-developer-merchantid-domain-association` file
5. `Apple Pay: Invalid domain association file permissions. /var/www/html/.well-known needs to have 755 permissions and /var/www/html/.well-known/apple-developer-merchantid-domain-association 644. Set the proper permissions and disable/enable Apple Pay.`  should be displayed in Payment methods panel

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2022-08-10 08:56 UTC, kalessil requested changes
Looks good overall, left some suggestions related to readability.

2022-08-10 08:56 UTC, kalessil commented on changelog/fix-4511-apple-pay-registration
> +Fix errors for apple pay registration
Can we add here what causes the errors please?

2022-08-10 08:56 UTC, kalessil commented on includes/class-wc-payment-gateway-wcpay.php
> +		$fullpath                                = $well_known_dir . '/' . WC_Payments_Apple_Pay_Registration::DOMAIN_ASSOCIATION_FILE_NAME;
`full_path` perhaps?

2022-08-10 08:56 UTC, kalessil commented on includes/class-wc-payment-gateway-wcpay.php
> +		$has_domain_association_file_permissions = is_dir( $well_known_dir ) &&
Would it be possible to use `is_writable` and `is_readable` here?

2022-08-10 08:56 UTC, kalessil commented on includes/class-wc-payment-gateway-wcpay.php
> +					<?php esc_html_e( 'You are not in the countries and regions that support Apple Pay. You can find a full list of countries and regions at', 'woocommerce-payments' ); ?>
Would the following be a good alternative `Your account is registered in a country or region not supported by Apply Pay.` where `not supported` is the link.

2022-08-10 08:56 UTC, kalessil commented on includes/class-wc-payment-gateway-wcpay.php
> +				<?php esc_html_e( 'Invalid domain association file permissions.', 'woocommerce-payments' ); ?>
`Domain association file is not readable, please check its access permissions.`

2022-08-10 08:56 UTC, kalessil commented on includes/class-wc-payment-gateway-wcpay.php
> +						__( '%1$s needs to have 755 permissions and %2$s 644.', 'woocommerce-payments' ),
@`The recommended access permissions for %1$s is 0755 and for %2$s 0644.`

2022-08-10 08:56 UTC, kalessil commented on includes/class-wc-payment-gateway-wcpay.php
> +				<?php esc_html_e( 'Set the proper permissions and disable/enable Apple Pay. ', 'woocommerce-payments' ); ?>
`Please re-enable Apple Pay after applying the new access permissions.`

2022-08-10 08:56 UTC, kalessil commented on includes/class-wc-payments-apple-pay-registration.php
> +		$fullpath                                = $well_known_dir . '/' . self::DOMAIN_ASSOCIATION_FILE_NAME;
`full_path`

2022-08-10 08:56 UTC, kalessil commented on includes/class-wc-payments-apple-pay-registration.php
> +		$has_domain_association_file_permissions = is_dir( $well_known_dir ) &&
Would it be possible to use `is_writable` and `is_readable` here?

2022-08-10 08:56 UTC, kalessil commented on includes/class-wc-payments-apple-pay-registration.php
> +	private function can_merchant_register_to_applepay(): bool {
`can_merchant_register_domain_with_applepay`

2022-08-12 06:52 UTC, mordeth approved these changes
LGTM!

2022-08-12 06:52 UTC, mordeth commented on includes/class-wc-payment-gateway-wcpay.php
> +		}
We are missing an empty line between if statements.

2022-08-16 14:13 UTC, dmvrtx commented on includes/class-wc-payments-apple-pay-registration.php
> +	private function can_merchant_register_domain_with_applepay(): bool {
May I suggest to move this code into the utilities file below? It is repeated here and above, and it'd be better to be in one place.

2022-08-23 15:51 UTC, mgascam approved these changes
LGTM! 
✅ Code looks good
✅ Followed testing instructions and works as expected

2022-08-24 06:19 UTC, merged