add link payment method for capture later option
Automattic/woocommerce-payments pull request #4822
Opened 2022-09-29 09:51 UTC by dpaun1985

Fixes #4821 

#### Changes proposed in this Pull Request
At this point Link payment method is not enabled when capture later flag is on. Since payments with Link can also be captured later, we should enable Link also when capture later flag is on.

#### Testing instructions

* Enable Link payment method
* Set 'Capture later' flag to on. (`WC -> Settings -> Payments-> Transactions->Issue an authorization on checkout, and capture later`) 
* create an order and pay it with Link
* no errors should occur.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2022-09-30 07:35 UTC, kalessil commented on changelog/fix-4821-link-enabled-capture-later
> +Add link payment method for capture later option
Can we tweak the wording? 

As I read, the change is about enabling Link to support authorization/capture scenarios.
And the changelog entry is misleading from this angle.

2022-09-30 07:38 UTC, kalessil requested changes
Good catch folks! I like the simplicity of fix and left some comments to address before we can move forward.

2022-09-30 07:38 UTC, kalessil commented on includes/payment-methods/class-upe-payment-gateway.php
> +		$capturable_payment_methods = $capture ? $this->get_upe_enabled_payment_method_ids() : [ 'card', 'link' ];
We have constants available for the payment methods see `Payment_Method` for reference.

2022-09-30 07:38 UTC, kalessil commented on includes/payment-methods/class-upe-payment-gateway.php
>  		$capture                    = empty( $this->get_option( 'manual_capture' ) ) || $this->get_option( 'manual_capture' ) === 'no';
While we are touching on this, the variable name is misleading. Can you tweak the name, please?

2022-09-30 12:18 UTC, kalessil commented
Can we also create a PR for updating PM docs to mention auth/capture support?

2022-10-14 12:39 UTC, kalessil commented
@dpaun1985, are we ready for the next review round here?

2022-10-14 12:40 UTC, dpaun1985 commented
> @dpaun1985, are we ready for the next review round here?

yep.

2022-10-14 12:52 UTC, kalessil requested changes
Did we consider a testing scenario when UPE is disabled (for both US and non-US merchants)?
If not, please ensure the checkout is functional for new cases and update testing instructions in the PR.

2022-10-14 12:56 UTC, dpaun1985 commented
> Did we consider a testing scenario when UPE is disabled (for both US and non-US merchants)?

I think Link works only with UPE. I will double-check.

2022-10-14 12:57 UTC, kalessil commented
You know, you are right - the change is in UPE gateways. Sorry for the false-alarm, I'll test now.

2022-10-14 13:18 UTC, kalessil requested changes
Found a bug - please comment below.

2022-10-14 13:18 UTC, kalessil commented on includes/payment-methods/class-upe-payment-gateway.php
> +		$capturable_payment_methods = $automatic_capture ? $this->get_upe_enabled_payment_method_ids() : [ Payment_Method::CARD, Payment_Method::LINK ];
Okay, this way, independently of whether Stripe Link is enabled or not in the settings - the link will be available.

While `capturable_payment_methods` naming is also misleading (please rename it to reflect the reality of what's happening there), I still suggest a pseudo-code to consider:
```php
		$automatic_capture = empty( $this->get_option( 'manual_capture' ) ) || $this->get_option( 'manual_capture' ) === 'no';
		if ( $automatic_capture ) {
			$capturable_payment_methods = $this->get_upe_enabled_payment_method_ids();
		} else {
			$capturable_payment_methods = array_intersect( $this->get_upe_enabled_payment_method_ids(), ['card', 'link'] );
		}
```

My change ensures that the hardcode PMs will be available only if those are enabled.

2022-10-18 11:40 UTC, kalessil approved these changes
LGTM!

2022-10-21 05:52 UTC, mordeth approved these changes
Looking good. Tested it, works well and no errors are displayed.

2022-10-24 09:09 UTC, merged