Remove "new checkout experience" setting + Enable using WooPay and UPE at the same time
Automattic/woocommerce-payments pull request #4919
Opened 2022-10-12 15:51 UTC by gpressutto5

Fixes #4724

#### Changes proposed in this Pull Request

Remove "new checkout experience" setting

This PR removes the need to enable UPE and any banner, button, or message related to disabling it or referencing "Early access". This was done because now UPE methods are separate methods on checkout, and the credit card element being used is the legacy one, which works with WooPay, so there's no need to ever disable UPE entirely, as disabling each method individually would achieve the same goal.

#### Testing instructions

1. Before checking out this branch, disable UPE for testing.
1. Go to WooCommerce Payments settings and notice there's no UPE banner, and all payment methods are displayed.
1. Enable some of these UPE methods and WooPay.
1. Change the store currency to EUR.
1. Make a purchase using a UPE method and ensure it works.
1. Make a purchase using WooPay and ensure it works.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2022-10-14 13:13 UTC, Mayisha commented on includes/notes/class-wc-payments-notes-additional-payment-methods.php
> - * to inform them that they can enable additional payment methods.
In this implementation the methods are listed in the settings from the beginning but in disabled state. Shouldn't we still let the merchant's know that they can enable some additional payment methods?

2022-10-14 13:14 UTC, Mayisha commented on tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
> +		$request->set_param( 'enabled_payment_method_ids', [] );
Just curious why it was made empty.

2022-10-14 13:26 UTC, Mayisha commented on client/payment-methods/index.js
> -				path: '/payments/additional-payment-methods',
After removing this, there is no other place in the codebase that can take user to this `/payments/additional-payment-methods` page. Though I can directly access the page with the URL which looks a little off without `step 1`

![additional](https://user-images.githubusercontent.com/33387139/195858084-4c807403-237a-4741-8ed9-0eb54ee2d85e.png)

If there is no button or any option to redirect user to that page, I think everything related to that page can also be deleted safely.

2022-10-14 13:41 UTC, Mayisha requested changes
I am noting down observations though some of them are not related to this specific PRs or can be handled in a follow up ticket.

- If I disable the credit card/debit card method from the settings page, it still appears on the checkout page. This does not happen on `develop` branch.
- On the shortcode checkout everything looks fine but on the blocks checkout the payment methods does not load for me.
![blocks error](https://user-images.githubusercontent.com/33387139/195859139-8d10e3f3-d655-4ce5-a708-24eed89f34ce.png)

- There was a `Learn More` link on the settings page and the additional methods page which would take the user to https://woocommerce.com/document/payments/additional-payment-methods/. Should we have this link somewhere on the settings for self guided user onboarding?
![learn more 1](https://user-images.githubusercontent.com/33387139/195859989-5fcb0c37-134d-4bc9-9341-719a86543427.png)
![learn more 2](https://user-images.githubusercontent.com/33387139/195860004-534cf718-4214-4f1f-844e-1d5b09e76193.png)

- We need to update the docs https://woocommerce.com/document/payments/additional-payment-methods/ (details and screenshots there) once these changes make their way to the production.

- On the `payment/additiona-payment-methods` page there [used to be a message](https://woocommerce.com/wp-content/uploads/2021/07/wcpay-additional-payment-methods-onboarding.gif) saying we are adding additional currencies to the merchant store to support the selected payment method. I think we somewhere should inform the merchants about this kind of changes.

I am hitting request changes in case you want to address some of them in this PR.

2022-10-24 12:28 UTC, gpressutto5 commented on includes/notes/class-wc-payments-notes-additional-payment-methods.php
> - * to inform them that they can enable additional payment methods.
Well thought. I think we can use the old task we had to enable additional methods, but instead of enabling UPE, it will be used only to review the enabled methods in the wizard.

2022-10-24 12:39 UTC, gpressutto5 commented on tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
> +		$request->set_param( 'enabled_payment_method_ids', [] );
We used to use [this method](https://github.com/Automattic/woocommerce-payments/blob/346c3d5881241c9d87c938c386ebfaccc488106a/includes/class-wc-payment-gateway-wcpay.php#L3121-L3131), which returns `[ 'card' ]` with no additional logic.
Now we use [this one](https://github.com/Automattic/woocommerce-payments/blob/task/remove-unused-option/includes/payment-methods/class-upe-payment-gateway.php#L986-L1016), which will filter to return only methods that have a fee set in Stripe, and we can't mock them because we are testing an endpoint.

2022-10-24 12:41 UTC, gpressutto5 commented on client/payment-methods/index.js
> -				path: '/payments/additional-payment-methods',
Elizabeth asked us not to remove it so we can improve it and reuse it later. She also mentioned the tasks that I removed that redirect to this page. We can reuse them to solve the issue you raised above.

2022-12-12 16:50 UTC, gpressutto5 commented
This feature has been postponed indefinitely. See this comment: https://github.com/Automattic/woocommerce-payments/issues/4724#issuecomment-1344986490

2022-12-12 16:50 UTC, closed without merging