Add Tap to Pay icon on the transactions list page for Tap to Pay transactions
Automattic/woocommerce-payments pull request #5744
Opened 2023-03-10 15:56 UTC by mordeth

Fixes #5377

#### Changes proposed in this Pull Request
Adding a Tap to Pay icon on the transactions list page for Tap to Pay transactions.

#### Testing instructions
- Create an order and pay it with Tap to Pay
- Navigate to Transactions list page
- Verify a Tap to Pay icon is displayed next to the `In Person` value in `Channel` column. 

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-03-14 09:32 UTC, anu-rock approved these changes
✅ Code changes are neat. LGTM
✅ I was able to see the TTP icon.

![image](https://user-images.githubusercontent.com/1288616/224957526-8e56a2bf-8ae0-4f59-a6e4-341c5ad05c4b.png)

2023-03-14 09:32 UTC, anu-rock commented on client/data/transactions/hooks.ts
> +	source_device?: null | string;
`source_device` is declared as a nullable property. Do we need to explicitly add `null` to its list of possible values?

2023-03-20 15:00 UTC, elazzabi requested changes
Thanks for working on this! I added a few minor comments 🙇 

To test this locally without having Tap to Pay setup, you can "force" the `source_device` using:

```js
// Include in client/transactions/list/index.tsx, line 372
txn.source_device = 'ios';
```

2023-03-20 15:00 UTC, elazzabi commented on client/data/transactions/hooks.ts
> +	source_device?: null | string;
Agree, I think we can leave it out

2023-03-20 15:00 UTC, elazzabi commented on client/transactions/list/index.tsx
> +			: __( 'Tap to Pay on Android', 'woocommerce-payments' );
I wonder if we should explicitly test for "android" and leave a default state for all non-ios and non-android devices.

```js
'ios' => __( 'Tap to Pay on iPhone', 'woocommerce-payments' )
'android' => __( 'Tap to Pay on Android', 'woocommerce-payments' )
default => __( 'Tap to Pay', 'woocommerce-payments' )
```

I think it's worth it given we can add server changes in the future without worrying of displaying incorrect information in the client.

2023-03-20 15:00 UTC, elazzabi commented on client/transactions/list/index.tsx
> +						{ txn.source_device ? getSourceDeviceIcon( txn ) : '' }
```suggestion
						{ txn.source_device && getSourceDeviceIcon( txn ) }
```

2023-03-20 15:14 UTC, anu-rock commented on client/transactions/list/index.tsx
> +						{ txn.source_device ? getSourceDeviceIcon( txn ) : '' }
I had the same suggestion in mind and then forgot all about it :p

2023-03-22 14:02 UTC, botwoo commented
### Test the build on Jurassic Ninja 

This feature is only available for A12s. Please log in into https://jurassic.ninja/specialops/ before clicking the link below:

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/ttp-logo-transactions-page) :rocket:

- Latest commit: da221aaf6a35c9c291cc4af17be8c254ebc07a79
- Build time: 2023-03-22 14:02:47 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-03-22 15:09 UTC, mordeth commented on client/transactions/list/index.tsx
> +						{ txn.source_device ? getSourceDeviceIcon( txn ) : '' }
Good catch, updated! :)

2023-03-22 15:10 UTC, mordeth commented on client/transactions/list/index.tsx
> +			: __( 'Tap to Pay on Android', 'woocommerce-payments' );
It makes sense, updated.

2023-03-22 15:10 UTC, mordeth commented on client/data/transactions/hooks.ts
> +	source_device?: null | string;
Updated!

2023-03-23 10:03 UTC, elazzabi approved these changes

2023-03-23 19:46 UTC, merged