[POC] Use Store API Cookie for requests to the Store API
Automattic/woocommerce-payments pull request #5853
Opened 2023-03-24 05:26 UTC by asumaran

Fixes #

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-03-24 05:29 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5853` or branch name `use-store-api-token` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=use-store-api-token) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 501d2a8fbae1366b5096398d32eefc0e0d45f003
- Build time: 2023-03-24 05:29:57 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-03-24 18:30 UTC, c-shultz requested changes

2023-03-24 18:30 UTC, c-shultz commented on includes/class-wc-payments.php
> +class WooPay_Store_Api_Token extends AbstractCartRoute {
Presumably, this class is present here because this is a PoC, so it will need to be moved out?

2023-03-24 18:30 UTC, c-shultz commented on includes/class-wc-payments.php
> +class WooPay_Store_Api_Token extends AbstractCartRoute {
When it does get moved out, please ensure that it's only loaded when absolutely necessary (when store is WooPay eligible and opted-in)

2023-03-24 19:25 UTC, asumaran commented on includes/class-wc-payments.php
> +class WooPay_Store_Api_Token extends AbstractCartRoute {
> Presumably, this class is present here because this is a PoC, so it will need to be moved out?

Yes, that's correct. It was placed here just to quickly build the POC.

2023-03-24 20:48 UTC, c-shultz commented
I understand from @senadir that stores will need WooCommerce 7.1+ to support this approach, so two things:
- Make sure we are testing against older versions of WooCommerce and handling errors correctly
- Let's just disable WooPay if a merchant doesn't have a minimum version of WooCommerce installed

@pierorocca any thoughts on how we would want to gracefully handle an incompatibility with an older version of WooCommerce? For context, this is one of several approaches to fix WooPay, so we shouldn't over-invest here until we decide on the final approach.


1. My preferred approach would would be to just simply hide WooPay settings altogether for lower versions of WooCommerce. We do have WooCommerce 7.1+ listed as the minimum version for WooPay compatibility already.

1. Alternatively, we could uncheck/disable the opt-in checkbox for WooPay and display a simple note that WooCommerce 7.1+ being required for WooPay. Given that this is targeted as patch fix.

Given that this is targeting a patch fix, I might suggest we do number 1 now, and consider if number 2 is needed in a future release.

2023-03-24 20:49 UTC, c-shultz commented
Speaking of patch fixes, @asumaran, this should be based off of `trunk` instead of `develop` so it's ready for a patch.

2023-03-24 20:54 UTC, rafaelzaleski commented on includes/class-wc-payments.php
> +class WooPay_Store_Api_Token extends AbstractCartRoute {
One suggestion I have is to consider moving the platform checkout code out of `class-wc-payments.php` (we have many functions for platform checkout functionality inside this class). This could help to reduce the file size, make it easier to maintain, and improve code readability. 
Overall, I think this change would help to organize our codebase better and make it more manageable in the long term.

2023-03-28 17:27 UTC, closed without merging

2023-03-30 19:13 UTC, pierorocca commented
> My preferred approach would would be to just simply hide WooPay settings altogether for lower versions of WooCommerce. We do have WooCommerce 7.1+ listed as the minimum version for WooPay compatibility already

Apologies as I'm not seeing my GH notifications. @c-shultz option 1 makes it clean while option 2 creates a visual incentive for a merchant to upgrade. Over time however, I think the need for Option 2 is low to nil so it would be a short lived benefit.