Add cart item count to fraud metadata
Automattic/woocommerce-payments pull request #5859
Opened 2023-03-25 23:45 UTC by tpaksu

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-03-25 23:48 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `5859` or branch name `add/cart-items-count-to-fraud-metadata` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/cart-items-count-to-fraud-metadata) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 17f9bae1c52042bfaa311c1995ec15410d617b70
- Build time: 2023-03-25 23:48:42 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-03-26 14:02 UTC, eduardoumpierre requested changes
I've tested the "Purchase Price Threshold" rule and it worked as expected!

I added a suggestion for the `PaymentDetails` loading management that I believe will improve the overall loading experience.

Thanks for adding the timeline texts!

2023-03-26 14:02 UTC, eduardoumpierre commented on client/payment-details/timeline/map-events.js
> +		.filter( ( [ , status ] ) => 'allow' !== status )
Nice catch!

2023-03-26 14:02 UTC, eduardoumpierre commented on client/payment-details/index.tsx
> +			! isLoadingLatestFraudOutcome &&
The fraud outcome loading didn't work as expected – as the summary component was being rendered before finishing the fraud outcome request.

https://user-images.githubusercontent.com/16882226/227780876-3ce9df91-6e32-4773-be73-fa159adbbc3c.mp4

---

What do you think about removing this logic from the `PaymentDetails` component? I discovered a function from `select` that is called `hasFinishedResolution` that we can use to determine if the loading has finished.

I think we can achieve that by:
- Updating both `useLatestFraudOutcome` and `usePaymentIntentWithChargeFallback` to use `hasFinishedResolution`
  - I found some usage occurrences of `isResolving` and `hasFinishedResolution` together, so we can stick with this pattern

Below is my suggestion on how to improve the current loading state:

<details><summary>Diff suggestion</summary>

```diff
diff --git a/client/data/fraud-outcomes/hooks.ts b/client/data/fraud-outcomes/hooks.ts
index c7e8638a3..f6120c266 100644
--- a/client/data/fraud-outcomes/hooks.ts
+++ b/client/data/fraud-outcomes/hooks.ts
@@ -9,7 +9,6 @@ import { useSelect } from '@wordpress/data';
  */
 import { STORE_NAME } from '../constants';
 import { LatestFraudOutcomeResponse } from './types';
-import { FraudOutcome } from '../../types/fraud-outcome';

 export const useLatestFraudOutcome = (
 	id: string
@@ -18,13 +17,14 @@ export const useLatestFraudOutcome = (
 		( select ) => {
 			const {
 				isResolving,
+				hasFinishedResolution,
 				getLatestFraudOutcome,
 				getLatestFraudOutcomeError,
 			} = select( STORE_NAME );

 			if ( ! id || ! wcpaySettings.isFraudProtectionSettingsEnabled ) {
 				return {
-					data: {} as FraudOutcome,
+					data: undefined,
 					error: undefined,
 					isLoading: false,
 				};
@@ -33,7 +33,9 @@ export const useLatestFraudOutcome = (
 			return {
 				data: getLatestFraudOutcome( id ),
 				error: getLatestFraudOutcomeError( id ),
-				isLoading: isResolving( 'getLatestFraudOutcome', [ id ] ),
+				isLoading:
+					isResolving( 'getLatestFraudOutcome', [ id ] ) ||
+					! hasFinishedResolution( 'getLatestFraudOutcome', [ id ] ),
 			};
 		},
 		[ id ]
diff --git a/client/data/fraud-outcomes/reducer.ts b/client/data/fraud-outcomes/reducer.ts
index a631b6287..ad8530880 100644
--- a/client/data/fraud-outcomes/reducer.ts
+++ b/client/data/fraud-outcomes/reducer.ts
@@ -29,6 +29,7 @@ const receiveFraudOutcomes = (
 					[ id ]: {
 						...state.latestFraudOutcome[ id ],
 						data: ( action as UpdateLatestFraudOutcomeAction ).data,
+						error: undefined,
 					},
 				},
 			};
@@ -38,6 +39,7 @@ const receiveFraudOutcomes = (
 				latestFraudOutcome: {
 					[ id ]: {
 						...state.latestFraudOutcome[ id ],
+						data: undefined,
 						error: ( action as UpdateErrorForLatestFraudOutcomeAction )
 							.error,
 					},
diff --git a/client/data/fraud-outcomes/selectors.ts b/client/data/fraud-outcomes/selectors.ts
index bb44d9d17..26d1dcd4a 100644
--- a/client/data/fraud-outcomes/selectors.ts
+++ b/client/data/fraud-outcomes/selectors.ts
@@ -18,11 +18,9 @@ const getLatestFraudOutcomeState = ( { fraudOutcomes }: State, id: string ) => {
 export const getLatestFraudOutcome = (
 	state: State,
 	id: string
-): FraudOutcome =>
-	getLatestFraudOutcomeState( state, id )?.data || ( {} as FraudOutcome );
+): FraudOutcome | undefined => getLatestFraudOutcomeState( state, id )?.data;

 export const getLatestFraudOutcomeError = (
 	state: State,
 	id: string
-): ApiError =>
-	getLatestFraudOutcomeState( state, id )?.error || ( {} as ApiError );
+): ApiError | undefined => getLatestFraudOutcomeState( state, id )?.error;
diff --git a/client/data/fraud-outcomes/types.d.ts b/client/data/fraud-outcomes/types.d.ts
index 4d0032bb0..3c8ce6153 100644
--- a/client/data/fraud-outcomes/types.d.ts
+++ b/client/data/fraud-outcomes/types.d.ts
@@ -33,7 +33,7 @@ export type FraudOutcomesActions =
 	| UpdateErrorForLatestFraudOutcomeAction;

 export interface LatestFraudOutcomeResponse {
-	data: FraudOutcome;
+	data?: FraudOutcome;
 	error?: ApiError;
 	isLoading: boolean;
 }
diff --git a/client/data/payment-intents/hooks.ts b/client/data/payment-intents/hooks.ts
index 47bc5e965..61f51442f 100644
--- a/client/data/payment-intents/hooks.ts
+++ b/client/data/payment-intents/hooks.ts
@@ -37,6 +37,7 @@ export const usePaymentIntentWithChargeFallback = (
 				getPaymentIntent,
 				getPaymentIntentError,
 				isResolving,
+				hasFinishedResolution,
 			} = selectors;

 			const paymentIntent: PaymentIntent = getPaymentIntent( id );
@@ -44,7 +45,9 @@ export const usePaymentIntentWithChargeFallback = (
 			return {
 				data: paymentIntent || ( {} as PaymentIntent ),
 				error: getPaymentIntentError( id ),
-				isLoading: isResolving( 'getPaymentIntent', [ id ] ),
+				isLoading:
+					isResolving( 'getPaymentIntent', [ id ] ) ||
+					! hasFinishedResolution( 'getPaymentIntent', [ id ] ),
 			};
 		},
 		[ id ]
diff --git a/client/payment-details/index.tsx b/client/payment-details/index.tsx
index eecb73160..d3f1aee02 100644
--- a/client/payment-details/index.tsx
+++ b/client/payment-details/index.tsx
@@ -1,7 +1,7 @@
 /**
  * External dependencies
  */
-import React, { useEffect, useState } from 'react';
+import React, { useEffect } from 'react';
 import { __ } from '@wordpress/i18n';
 import { Card, CardBody } from '@wordpress/components';
 import { getAdminUrl } from 'wcpay/utils';
@@ -49,29 +49,10 @@ const PaymentChargeDetails: React.FC< PaymentChargeDetailsProps > = ( {
 	const orderId = paymentIntent?.metadata?.order_id;

 	const {
-		data: latestFraudOutcome,
-		error: latestFraudOutcomeError,
-		isLoading: isLoadingLatestFraudOutcome,
+		data: fraudOutcome,
+		isLoading: isLoadingFraudOutcome,
 	} = useLatestFraudOutcome( orderId );

-	// Additional loading state prevent flashing while the data is not available.
-	const [ isLoadingFraudOutcome, setIsLoadingFraudOutcome ] = useState(
-		true
-	);
-
-	useEffect( () => {
-		if (
-			! isLoadingLatestFraudOutcome &&
-			! Object.keys( latestFraudOutcome || {} ).length &&
-			'undefined' !== typeof latestFraudOutcomeError
-		)
-			setIsLoadingFraudOutcome( false );
-	}, [
-		isLoadingLatestFraudOutcome,
-		latestFraudOutcome,
-		latestFraudOutcomeError,
-	] );
-
 	const isChargeId = getIsChargeId( id );
 	const isLoading = isChargeId || isLoadingData || isLoadingFraudOutcome;

@@ -124,7 +105,7 @@ const PaymentChargeDetails: React.FC< PaymentChargeDetailsProps > = ( {
 					charge={ charge }
 					metadata={ metadata }
 					isLoading={ isLoading }
-					fraudOutcome={ latestFraudOutcome }
+					fraudOutcome={ fraudOutcome }
 					paymentIntent={ paymentIntent }
 				/>
 			</ErrorBoundary>

```
</details> 

Let me know what you think about it!

2023-03-26 14:38 UTC, tpaksu commented on client/payment-details/index.tsx
> +			! isLoadingLatestFraudOutcome &&
Yes, loading dependent on error and data variables also didn't make sense, and I was trying to fix the modified snapshot to match the previous one. Thanks for making this suggestion and releasing me from more work :D Addressed in [e3206bb](https://github.com/Automattic/woocommerce-payments/pull/5859/commits/e3206bbcf88d332a31f315b1de9d0c94b39ead44).

2023-03-26 18:18 UTC, eduardoumpierre commented
@tpaksu I've updated the fraud outcome selectors tests to match the latest changes. Sorry for not including those in the diff. It was addressed on [a41bcd0](https://github.com/Automattic/woocommerce-payments/pull/5859/commits/a41bcd06285b66e95cf84e330ceda8c19af1d9b4).

2023-03-26 18:23 UTC, tpaksu commented
@eduardoumpierre I have added those tests myself? Guess I missed the selector tests. Thanks for including those.

2023-03-26 18:46 UTC, eduardoumpierre approved these changes
I've tested the rules affected by the changes and they worked as expected. The PaymentDetails loading is working smoothly too. The code is easy to understand and it's well-tested.

Thanks for working on those items. LGTM! :shipit:

2023-03-26 19:42 UTC, merged