Hide WooPay button when logged out and subscriptions involved
Automattic/woocommerce-payments pull request #6133
Opened 2023-04-22 02:13 UTC by reykjalin

Fixes #6131 

## Changes proposed in this Pull Request

> **Note**
> "Subscription product" here refers to both WC Subscriptions products and WCPay Subscriptions products.

Do not show WooPay button when:

- The customer is not logged into the merchant store and a subscription product is in the cart.
- The customer is not logged into the merchant store and is looking at a subscription product page.

| \ | Logged In | Logged Out |
|:---:|:---:|:---:|
| Product | <img width="843" alt="image" src="https://user-images.githubusercontent.com/13835680/233756374-2c3b5e6e-877c-472b-8255-80cc7b36e703.png"> | <img width="843" alt="image" src="https://user-images.githubusercontent.com/13835680/233756440-e0912e7c-a476-4ac0-b4ad-ec9f1b1750df.png"> |
| Cart | <img width="843" alt="image" src="https://user-images.githubusercontent.com/13835680/233756396-26878ee1-0c28-4ced-9454-f02afb7cfb31.png"> | <img width="843" alt="image" src="https://user-images.githubusercontent.com/13835680/233756455-4ab75c9e-9a7d-4edb-977e-8553a806cef9.png"> |
| Checkout | <img width="843" alt="image" src="https://user-images.githubusercontent.com/13835680/233756418-0d7bc347-1cd4-416d-82f5-7f90b6fbea77.png"> | <img width="843" alt="image" src="https://user-images.githubusercontent.com/13835680/233756471-cc15fce6-3b95-43d5-b3bb-570540091106.png"> |

## Testing instructions

> **Warning**
> The following testing instructions assume you have the WooPay button enabled everywhere it can possibly be:
>
> <img width="481" alt="image" src="https://user-images.githubusercontent.com/13835680/233755952-936ae028-98ca-4668-b96d-4f36b968b3e9.png">

### Logged-out customer

#### Doesn't see WooPay button on subscription product page

1. Create a **Simple Subscription** product if you haven't already.
2. Navigate to that product's page.
3. Make sure the WooPay button isn't visible.

Repeat the test with a **Variable Subscription** product.

#### Does see WooPay button on a non-subscription product page

1. Create a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Navigate to that product's page.
3. Make sure the WooPay button is visible.

Repeat the test with all non-subscription type products.

#### Doesn't see WooPay button on cart page when a subscription product is in the cart

1. Create a **Simple Subscription** product and a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add that product to the cart.
3. Navigate to the **Cart** page.
4. Make sure the WooPay button isn't visible.
5. Add another non-subscription product to the cart and navigate back to the **Cart** page.
6. Make sure the WooPay button isn't visible.

Repeat the test with a **Variable Subscription** product and 2-3 different sets and amounts of subscription and non-subscription products.

Check with a mix of subscription and non-subscription products as well.

#### Does see WooPay button on cart page when all products in the cart are non-subscription products

1. Create a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add any number of non-subscription products to the cart.
3. Navigate to the **Cart** page.
4. Make sure the WooPay button is visible.

#### Doesn't see WooPay button on checkout page when a subscription product is in the cart

1. Create a **Simple Subscription** product and a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add that product to the cart.
3. Navigate to the **Checkout** page.
4. Make sure the WooPay button isn't visible.
5. Add another non-subscription product to the cart and navigate back to the **Checkout** page.
6. Make sure the WooPay button isn't visible.

Repeat the test with a **Variable Subscription** product and 2-3 different sets and amounts of subscription and non-subscription products.

Check with a mix of subscription and non-subscription products as well.

#### Does see WooPay button on checkout page when all products in the cart are non-subscription products

1. Create a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add any number of non-subscription products to the cart.
3. Navigate to the **Checkout** page.
4. Make sure the WooPay button is visible.

### Logged-in customer

#### Does see WooPay button on a subscription product page

1. Create a **Simple Subscription** product if you haven't already.
2. Navigate to that product's page.
3. Make sure the WooPay button is visible.

Repeat the test with a **Variable Subscription** product.

#### Does see WooPay button on cart page when a subscription product is in the cart

1. Create a **Simple Subscription** product and a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add that product to the cart.
3. Navigate to the **Cart** page.
4. Make sure the WooPay button isn't visible.
5. Add another non-subscription product to the cart and navigate back to the **Cart** page.
6. Make sure the WooPay button is visible.

Repeat the test with a **Variable Subscription** product and 2-3 different sets and amounts of subscription and non-subscription products.

Check with a mix of subscription and non-subscription products as well.

#### Does see WooPay button on checkout page when a subscription product is in the cart

1. Create a **Simple Subscription** product and a product that **is not** a Simple or Variable Subscription if you haven't already.
2. Add that product to the cart.
3. Navigate to the **Checkout** page.
4. Make sure the WooPay button isn't visible.
5. Add another non-subscription product to the cart and navigate back to the **Checkout** page.
6. Make sure the WooPay button is visible.

Repeat the test with a **Variable Subscription** product and 2-3 different sets and amounts of subscription and non-subscription products.

Check with a mix of subscription and non-subscription products as well.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-04-22 02:16 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6133` or branch name `add/woopay-unavailable-for-subscriptions-when-logged-out` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=add/woopay-unavailable-for-subscriptions-when-logged-out) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 4e4d17e2f6aaae88693befa4c708db63d279e3ed
- Build time: 2023-04-22 02:16:54 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-04-24 18:40 UTC, asumaran commented
@reykjalin Button shows up for Variable Subscriptions. It only happens on the product page, though. 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/1025173/234086537-62610498-9cf1-4651-b9ec-b4ab66de8a73.png">

2023-04-24 18:51 UTC, asumaran requested changes
Code looks good overall. I just left a comment for you @reykjalin

2023-04-24 18:51 UTC, asumaran commented on includes/class-wc-payments-platform-checkout-button-handler.php
> +		return 'subscription' === $product->get_type() || 'subscription_variation' === $product->get_type();
We also need to consider `variable-subscription` here

2023-04-24 19:10 UTC, asumaran commented on includes/class-wc-payments-platform-checkout-button-handler.php
> +		return 'subscription' === $product->get_type() || 'subscription_variation' === $product->get_type();
Where the `subscription_variation` product type comes from? I've tried creating a variable subscription with and without WC Subcriptions enabled both had `variable-subscription` as the product type.

2023-04-24 22:30 UTC, reykjalin commented on includes/class-wc-payments-platform-checkout-button-handler.php
> +		return 'subscription' === $product->get_type() || 'subscription_variation' === $product->get_type();
I got it from [the code in subscriptions core](https://github.com/Automattic/woocommerce-subscriptions-core/blob/a923da64ef4e5c4b7747fa81f4b496ca4dfb6298/includes/class-wc-product-subscription-variation.php#L64-L71) 🤔 

I just figured it was the type for the variable subscription type, but maybe I'm wrong? I'll keep it in and add `variable-subscription`, thanks for catching that!

2023-04-24 22:48 UTC, reykjalin commented on includes/class-wc-payments-platform-checkout-button-handler.php
> +		return 'subscription' === $product->get_type() || 'subscription_variation' === $product->get_type();
Fixed in c2b61b2f2c8fba6712e582317b0e3cf0e8cc4caf 🙌

2023-04-24 22:50 UTC, asumaran approved these changes
LGTM! 🚀

2023-04-25 06:52 UTC, merged