Fix dispute naming inconsistencies
Automattic/woocommerce-payments pull request #6475
Opened 2023-06-07 01:32 UTC by brucealdridge

Fixes #6474 

> **Warning**
> This PR is currently set to merge into #6472 rather than trunk. This is no longer required and will be updated to point to trunk.

#### Changes proposed in this Pull Request

When an order is disputed in WCPay, an order note is generated showing the reason for the dispute. Previously, this reason did not match the descriptions given in emails (server) and in the Dispute details.

**Before**
![image](https://github.com/Automattic/woocommerce-payments/assets/57298/09782297-e3b0-49d9-afbd-d3b0168b1588)

**After**
![image](https://github.com/Automattic/woocommerce-payments/assets/57298/76cda103-168c-4030-bf4c-186d4936c8c4)

--
Question for the reviewer:
The capitalization of the order note is incorrect in the screenshot. There is a parallel change to this order note in #6381. However, this will not rectify the issue. The options I see to resolve this are as follows

1. Store the descriptions in `get_dispute_reason_description()` in lowercase format.
2. Use `str_to_lower( $reason )` inside `generate_dispute_created_note()` to force this to lowercase
3. Wrap the given reason inside quotes. eg `__( 'Payment has been disputed as "%1$s". See <a>dispute overview</a> for more details.', 'woocommerce-payments' )`

Given the possible issues with i18n, I think it makes sense to go with option 3. This may make sense to tackle as part of #6381 

#### Testing instructions

1. Purchase a product using a ["dispute" test card](https://stripe.com/docs/testing#disputes) `4000000000000259` will automatically create a dispute with a reason of `fraudulent`
2. Viewing the dispute details under `Payments > Disputes`, will show `Transaction unauthorized` with #6472.
3. View the relevant order.
5. Order note will show the dispute reason is `Transaction unauthorized`

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-06-07 01:36 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6475` or branch name `fix/6474-consistent-dispute-naming` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=fix/6474-consistent-dispute-naming) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 18b68c32ebe56743eb8bd355de81f18019cd0b1f
- Build time: 2023-06-07 01:36:35 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-06-19 03:30 UTC, Jinksi requested changes
Thanks @brucealdridge, looking good 👍

I've requested changes to address some inconsistencies that remain between PHP & JS dispute reasons.

2023-06-19 03:30 UTC, Jinksi commented on includes/class-wc-payments-utils.php
> +				return __( 'Bank can not process', 'woocommerce-payments' );
I think this should be `Bank cannot process` which is consistent with `client/disputes/strings.ts` and the changes you've proposed in https://github.com/Automattic/woocommerce-payments-server/pull/3436.

https://github.com/Automattic/woocommerce-payments/blob/7cef6df74173a4d6e278f08ec4346b588e48bb5d/client/disputes/strings.ts#L22

```suggestion
				return __( 'Bank cannot process', 'woocommerce-payments' );
```

2023-06-19 03:30 UTC, Jinksi commented on includes/class-wc-payments-utils.php
> +				return __( 'Subscription cancelled', 'woocommerce-payments' );
As above, I think this should be `Subscription canceled` which is consistent with `client/disputes/strings.ts` and the changes you've proposed in https://github.com/Automattic/woocommerce-payments-server/pull/3436.

https://github.com/Automattic/woocommerce-payments/blob/7cef6df74173a4d6e278f08ec4346b588e48bb5d/client/disputes/strings.ts#L254


```suggestion
				return __( 'Subscription canceled', 'woocommerce-payments' );
```

2023-06-19 03:30 UTC, Jinksi commented on changelog/fix-6474-consistent-dispute-naming
> +Dispute reasons inconsistencies have been fixed.
Should we mention that this includes a change to order notes, perhaps as an additional changelog entry?
```suggestion
Show descriptive dispute reasons in order notes.
```

2023-06-19 03:30 UTC, Jinksi commented on includes/class-wc-payments-utils.php
> +				return __( 'Transaction unauthorized', 'woocommerce-payments' );
To keep this PR changelog correct, should this be `Fraudulent` to remain consistent with `client/disputes/strings.ts`?

https://github.com/Automattic/woocommerce-payments/blob/7cef6df74173a4d6e278f08ec4346b588e48bb5d/client/disputes/strings.ts#L112

I see that this is being changed to `Transaction unauthorized` in #6472, so perhaps that PR could handle the change across both files.

```suggestion
				return __( 'Fraudulent', 'woocommerce-payments' );
```

2023-06-20 01:01 UTC, brucealdridge commented on includes/class-wc-payments-utils.php
> +				return __( 'Transaction unauthorized', 'woocommerce-payments' );
Good thinking, I'll update the other PR

2023-06-20 01:03 UTC, brucealdridge commented
> Thanks @brucealdridge, looking good 👍
> 
> I've requested changes to address some inconsistencies that remain between PHP & JS dispute reasons.

😃 Good spotting, I'm not sure how I missed those changes given the title of the PR. I think I was focused on the order notes change!

2023-06-21 04:09 UTC, Jinksi approved these changes
LGTM @brucealdridge 🙌 

I've tested this locally using the fraudulent dispute test card number and see the "Fraudulent" display reason rendered in the order note.

![image](https://github.com/Automattic/woocommerce-payments/assets/3147296/c0e16061-b064-4d27-ad61-454b2d3d8996)

2023-06-23 02:23 UTC, merged