Enable WC Pay Subscriptions during WC onboarding when US merchant selects subscriptions as product type
Automattic/woocommerce-payments pull request #6643
Opened 2023-06-30 06:50 UTC by mattallan

Fixes #6512

### Changes proposed in this Pull Request

In https://github.com/Automattic/woocommerce-payments/pull/6635 we changed the default behavior of our WCPay Subscriptions feature so that it is no longer enabled by default for all US-based stores.

The changes in this pull request make it so that when a US merchant goes through the WooCommerce onboarding wizard and selects the "free" subscriptions option (see screenshot below), the WCPay Subscriptions feature will be enabled.

![image](https://github.com/Automattic/woocommerce-payments/assets/2275145/9f53c89d-fd22-498d-b31a-7c7c3822003a)

> **Note** - The WooCommerce onboarding wizard is changing in the upcoming 7.9.0 release, so the changes in this PR are only for stores running versions < 7.9.0.

#### Implementation 
This pull request introduces a new function `maybe_enable_wcpay_subscriptions_after_onboarding()` that is hooked onto `woocommerce_onboarding_profile_data_updated` which is fired whenever the `woocommerce_onboarding_profile` wp-option is updated. On this hook, I'm checking if the `product_types` data is being updated and includes the `'subscriptions'` product type, if so, I verify the store is eligible for WC Pay Subscriptions before enabling the feature.

We only need this code to run on stores with WC versions < 7.9.0 so I've surrounded adding the `woocommerce_onboarding_profile_data_updated` hook with a version check.

### Testing instructions

There are a few key flows that these changes need to be tested on:

#### 1. Onboarding a US Store with WC <= 7.8.1

1. Spin up a fresh JN site with WooCommerce
2. Upload this branch and activate WC Payments
3. [Manually trigger the WC onboarding wizard](https://woocommerce.com/document/woocommerce-setup-wizard/#reusing-the-setup-wizard)
4. On the Product Types step make sure you select at least "Subscriptions"
![image](https://github.com/Automattic/woocommerce-payments/assets/2275145/f5957fec-47c7-4f96-90e4-13bbac954f43)
5. After completing the WC Onboarding, confirm WCPay Subscriptions is enabled either by confirming the **WooCommerce > Subscriptions** menu item is loading.
6. Go into the wp-options table and delete the `_wcpay_feature_subscriptions` row
7. Confirm the Subscriptions menu item is no longer there
8. Go through the WC Onboarding Wizard again and don't select Subscriptions
9. Confirm WCPay Subscriptions feature is not enabled.

#### 2. Onboarding a non-US store running WC <= 7.8.1

1. Spin up a fresh JN site with WooCommerce
2. Go into **WooCommerce > Settings** and change your **Country / State** to Australia - Queensland
3. Upload this branch and activate WC Payments
4. [Manually trigger the WC onboarding wizard](https://woocommerce.com/document/woocommerce-setup-wizard/#reusing-the-setup-wizard)
5. On the Product Types step make sure you select at least "Subscriptions" (same screenshot above)
6. After completing the WC Onboarding, confirm WCPay Subscriptions is not enabled
7. Go into the wp-options table and delete the `_wcpay_feature_subscriptions` row

#### 3. Onboarding a store with WC > 7.9.0

1. Install and activate the latest [WC 7.9.0-beta-2](https://downloads.wordpress.org/plugin/woocommerce.7.9.0-beta.2.zip) zip
2. Install this branch of WC Payments
3. [Manually trigger the WC onboarding wizard](https://woocommerce.com/document/woocommerce-setup-wizard/#reusing-the-setup-wizard)
4. You'll notice the onboarding process looks a little different
![image](https://github.com/Automattic/woocommerce-payments/assets/2275145/ae59fc96-bd0f-471d-a96a-32c03859aa67)
5. Complete the new onboarding and make sure WCPay Subscriptions is not enabled.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-06-30 06:55 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `6643` or branch name `issue/6512` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&branches.woocommerce-payments=issue/6512) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f09ca75d41e702710282ed6f8cdda3b22f8dba29
- Build time: 2023-06-30 06:55:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-07-03 06:44 UTC, james-allan requested changes
Changes look good. I still need to go through all the possible flows but I reached EOD so I'll leave these suggestions and retest tomorrow.

2023-07-03 06:44 UTC, james-allan commented on changelog/issue-6512
> +Check WCPay Subscriptions eligibility after store completes WC onboarding wizardd.
```suggestion
Check WCPay Subscriptions eligibility after store completes WooCommerce onboarding wizard.
```

2023-07-03 06:44 UTC, james-allan commented on woocommerce-payments.php
>  	// Do not take any action if activated in a REST request (via wc-admin).
```suggestion
	// When WooCommerce Payments is installed and activated from the WooCommerce onboarding wizard (via wc-admin REST request), check if the site is eligible for subscriptions.
```

This comment is no longer correct when it says "do not take any action" now that there is some action taken during that flow. So I've suggested we replaced it with a tweaked version of your new comment.

2023-07-03 06:44 UTC, james-allan commented on woocommerce-payments.php
> +		// When WooCommerce Payments is installed and activated from the WooCommerce onboarding wizard, check if the site is eligible for subscriptions.
```suggestion
```

2023-07-12 00:54 UTC, james-allan approved these changes
Changes look good and work well for me. 

I had to hack it a bit to test the flow where the WC onboarding flow installs Woo Payments. Because I needed to test this version of the plugin, if this version of WC Payments is installed, then the WC onboarding flow won't activate the plugin.

Anyway, I hacked the WC onboarding flow to make sure it does activate WC Payments and confirmed that this code does enable the subscriptions feature.

2023-07-13 00:25 UTC, merged