Multicurrency: Do not modify deposit percentage for display.
Automattic/woocommerce-payments pull request #6930
Opened 2023-08-04 05:12 UTC by peterwilsoncc

Fixes: WooCommerce Deposits #\506

#### Changes proposed in this Pull Request

As reported in  WooCommerce Deposits #\506, enabling multi-currency modifies the display of percentage deposits.

The issue comes from `WooCommerceDeposits::modify_cart_item_deposit_amount_meta()` attempting to convert a percentage number although it were currency.

A store with a USD base selling a product with a 20% deposit results in the following displaying for select currencies:

AUD: 31%
CAD: 27%
INR: 1656%

I haven't written any tests and the new change relies on detecting a backtrace to the Deposits extension. 

**Before**
<img width="667" alt="Screen Shot 2023-08-04 at 2 58 01 pm" src="https://github.com/Automattic/woocommerce-payments/assets/519727/b062b4e6-4676-40f5-8600-2f666b739a85">

**After**
<img width="699" alt="Screen Shot 2023-08-04 at 2 58 52 pm" src="https://github.com/Automattic/woocommerce-payments/assets/519727/0fe15528-e2cc-450f-8c2e-3ae6f4998680">

#### Testing instructions

1. Configure Multi-currency Payments: using USD (default) and INR will best demonstrate the bug
2. Enable the WooCommerce Deposits extension
3. Configure and publish product to accept deposits:
    * Enable Deposits: Yes - Deposits are optional
    * Deposit Type:: percentage
    * Deposit Amount: 20
    * Default Deposit Selected Type: Pay Deposit
4. View the product on the front end
5. Switch to USD if required, observe the deposit amount is displayed as 20%
6. Switch the currency from USD to INR
7. Observe the deposit amount is displayed as significantly over 100% (the exact amount will vary according to currency fluctuations)

*

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-08-28 08:03 UTC, Mayisha requested changes
Thanks @peterwilsoncc for working on this. The deposit percentage on the individual product page is showing up correctly now. However, the charged amount is still incorrect resulting in a negative future payment after checkout.

Here is the flow I tested and the purchase with incorrectly charged amount with currency INR.
![deposits](https://github.com/Automattic/woocommerce-payments/assets/33387139/eb411a48-5a5f-415a-a10c-8680c9ba2799)

2023-08-31 05:40 UTC, peterwilsoncc commented
Thanks for catching that @Mayisha, it looks like that string comes from the deposits extension and requires a sibling branch in the other repo.

Once I have that set up, I'll let you know which branch to check out.

2023-09-05 10:14 UTC, iamdharmesh commented
Hi @peterwilsoncc, 

I have checked on this and figured out that the issue happening due to a double conversion of the deposit amount.

Deposits extension use [`$product->get_price()`](https://github.com/woocommerce/woocommerce-deposits/blob/trunk/includes/class-wc-deposits-product-manager.php#L251C49-L251C70) function to get deposit amount. Since it uses the product's get_price function in the view context, currency conversion is already handled by default (via the `woocommerce_product_get_price` filter [here](https://github.com/Automattic/woocommerce-payments/blob/635e38668f37d49143703f2bbb4a76d644e48cdd/includes/multi-currency/FrontendPrices.php#L44)). However, a [filter](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/multi-currency/Compatibility/WooCommerceDeposits.php#L27) added for Deposits' multicurrency compatibility is converting the currency again, which is causing problems with the cart and order totals.

**Solution:**
Since the Deposits extension already calculates deposit amounts using the product's get_price function, currency conversion will work fine without any additional compatibility code for `percentage` and `payment plan` based deposit products. However, for the `fixed_amount` deposit product, we need to utilize the `woocommerce_deposits_fixed_deposit_amount` filter to convert the deposit amount to a specific currency.

Therefore, replacing the entire current compatibility code with the following code will resolve the issue.

```php
add_filter( 'woocommerce_deposits_fixed_deposit_amount', function( $amount ) {
    return $this->multi_currency->get_price( $amount, 'product' );
}, 10 );
```

Thanks.

2023-09-06 19:18 UTC, jeffpaul commented
@iamdharmesh so is that a change still needed here in WooCommerce Payments or merely in Deposits?

2023-09-07 13:06 UTC, iamdharmesh commented
@jeffpaul Changes are needed here in WooCommerce Payments. However, we can move this fixed_amount filter to the deposits side but in that case as well, we need to remove legacy compatibility functions from the WooCommerce Payments

2023-09-21 02:43 UTC, closed without merging

2023-09-21 04:30 UTC, peterwilsoncc commented
@Mayisha @iamdharmesh @jeffpaul I've replaced this PR with https://github.com/Automattic/woocommerce-payments/pull/7247 as I'd pushed to the wrong branch in my fork of the repository.