Fix/5188 duplicate charges delay webhook processing
Automattic/woocommerce-payments pull request #7004
Opened 2023-08-15 19:20 UTC by zmaglica

Fixes #

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-08-15 19:26 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7004` or branch name `fix/5188-duplicate-charges-delay-webhook-processing` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/5188-duplicate-charges-delay-webhook-processing) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 66720354873010b827ae05a33733d4f2f7b2b381
- Build time: 2023-08-15 19:26:28 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-08-16 19:45 UTC, RadoslavGeorgiev requested changes
Thank you for moving this forward @zmaglica! I left a couple of comments, but I want to make sure we're on the same page regarding the general approach before we focus on them.

One big piece that is missing here is checking for stored webhooks at the end of the payment process. Successful or failed, we should load related events immediately, and either delete them or process them. There are two reasons for this:

1. Even though we will be storing all webhooks of a given type, we want to do it in the shortest possible timeframe. High-traffic sites might receive plenty of webhooks, and those should be processed as quickly as possible / immediately to keep the DB lightweight.
2. Simply delaying webhooks will likely open the gate for a flood of duplicate charges because if something fails during checkout, the same order could be paid again before the webhook gets processed. We want to avoid the concurrency of webhooks by delaying them, but delaying them too much could have more negative than positive effects. Even if we remove the emphasis away from duplicate orders, this would simply degrade customers' experiences.

This needs to be added, and tested in his PR, before we start delaying webhooks. For now, we could simply try processing the webhook within the `catch` block of process payment. Once we have states working well (payment process re-engineering), we could plug in the intent in the middle of the process as well.

---

Another significant issue is that currently all stored events will be processed at once. Webhooks are only fetched from the server each couple of hours, and will be stored at once. This could mean hundreds of orders being processed in one go. Keeping in mind that completing an order is an expensive operation, I can all but guarantee that there will be timed-out processes, or ones exceeding the allowed memory limit.

Do you have any plans regarding how to handle this issue?

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments.php
> +		add_action( 'init', [ self::$webhook_reliability_service, 'init' ] ); // Add custom post type and taxonomies.
To be consistent with the rest of this method, let's move this `add_action()` call to an `init_hooks` method within the service, and call that method here instead.

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +	const LIVEMODE_TAXONOMY                  = 'wcpay-webhook-livemode';
We have many types of webhooks, which warranted a taxonomy for them. Do you think something with two options deserves a whole taxonomy? Keep in mind that `get_posts()` will need to perform an additional `INNER JOIN` with a potentially huge table.

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +	const PAYMENT_INTENT_SUCCEEDED_EVENT     = 'payment_intent.succeeded';
Have you considered another place for this constant? Right now we have the single event type here, but we'll likely have more and more in the future.

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +		add_action( 'woocommerce_payments_account_refreshed', [ $this, 'maybe_schedule_failed_webhook_events' ] );
I don't think this change makes sense. We're scheduling a simple fetch from the server here.

Context: To avoid overloading the account details endpoint (and cache), we simply serve a flag, which indicates whether there are events to fetch. We are not scheduling their processing within the linked method.

With that in mind, let's restore its name?

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +			as_schedule_recurring_action( time(), 60, self::WEBHOOK_PROCESS_EVENTS_ACTION );
Let's use the `MINUTE_IN_SECONDS` constant here.

Also, do you think that one minute is a meaningful interval? On most sites, this will likely mean booting too many PHP processes, which wouldn't really do much. IMO the interval could be a few minutes, if not even an hour here.

Also, maybe we should consider only scheduling the action whenever an event is stored? This way it will never run until it's actually needed.

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +		if ( isset( $event['data']['object']['payment_method_details']['type'] ) && Sepa_Payment_Method::PAYMENT_METHOD_STRIPE_ID === $event['data']['object']['payment_method_details']['type'] ) {
Shouldn't we check for `data`, `object`, `payment_method_details`, and `type` individually?

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +			Logger::error( 'Could not store event in CPT. Event data: ' . var_export( $event, true ) ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_var_export
Instead of just logging this, should we maybe force the event to be processed immediately?

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +			$livemode = WC_Payments::mode()->is_live() ? 1 : 0;
If we decide to use the taxonomy, let's use unique strings here. I imagine a discrepancy between `0`, `false`, `null` and etc.

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +			$args['tax_query']['relation'] = 'AND';
`AND` is and has always been the default relation for tax queries. We can remove this bit.

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +			'post_date'    => $this->get_event_processing_time_from_event_type( $event['type'] ?? '' ),
I'm not sure how WP would handle post dates in the future, as they are used for post status and whatnot. Can't we achieve the same query with normal dates, but while changing the query to retrieve events?

2023-08-16 19:45 UTC, RadoslavGeorgiev commented on includes/class-wc-payments-webhook-reliability-service.php
> +		add_action( self::WEBHOOK_PROCESS_EVENTS_ACTION, [ $this, 'load_and_process_events' ] );
Hooking the event this way is dangerous. All parameters of the hook would be passed to `get_events`, leading to potential side effects.

2026-04-17 14:32 UTC, dmvrtx commented
Thanks a lot for the work on this one — there’s clearly been a lot of thoughtful effort here, especially around storing webhook data more reliably and trying to recover successful payments from the failure path. That context is still useful, and the PR helped clarify the shape of the problem.

At this point, though, I think it makes more sense to close this draft and start over with a fresh PR instead of trying to bring it up to date. The branch is quite old, develop has moved on in the duplicate-payment area, and this change touches core webhook and payment-processing behavior deeply enough that resolving conflicts would likely turn into a partial redesign anyway.

Starting fresh should make it easier to:

1. Re-evaluate whether delaying payment_intent.succeeded is still the right remedy for the problem we want to solve today.
2. Build on top of the current process_payment() and duplicate-payment-prevention flow instead of reconciling 2023 assumptions with 2026 code.
3. Keep the new implementation narrower, easier to review, and better covered by current tests.

Closing this PR is not a reflection on the quality of the work here — it’s mainly about the age of the branch and how much the surrounding code has changed since it was opened.

2026-04-17 14:32 UTC, closed without merging