Add Woo Subscription Stripe Billing settings and migration status notices
Automattic/woocommerce-payments pull request #7105
Opened 2023-08-31 06:29 UTC by james-allan

Fixes #6508

### Changes proposed in this Pull Request

This PR adds a new "Subscriptions" setting section to the WooPayments setting screen. This new section is only shown if you have the Woo Subscriptions plugin active. 

It contains a simple checkbox to enable/disable Stripe Billing along with an array of notices that are shown depending on the Stripe Billing migration status. 

<img width="1100" alt="Screenshot 2023-08-31 at 2 20 41 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/5ff396b8-10fd-4519-be2e-c0ec93c973de">

### Testing

<details><summary><strong>No Settings</strong></summary>
<p>

**Setup:**

1. No Woo Subscriptions plugin installed. 

**Testing instructions:**

1. Go to **WooCommerce → Settings → Payments → Woo Payments**
2. Note there isn't any **"Subscriptions"** section. 

</p>
</details>

<details><summary><strong>No Stripe Billing subscriptions</strong></summary>
<p>

**Setup:**

1. Woo Subscriptions plugin installed. 
2. No pre-existing Stripe billing subscriptions. 

**Testing instructions:**

1. Go to **WooCommerce → Settings → Payments → Woo Payments**
2. Note there is a new **"Subscriptions"** section with a single setting.
   - The setting should be disabled by default. 
3. Enable/disabling the setting and saving should set the `_wcpay_feature_stripe_billing` option to `1`/`0`.

<img width="1120" alt="Screenshot 2023-08-31 at 2 59 35 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/d956b36c-69a1-444a-9591-474bd6711031">
</p>
</details>

<details><summary><strong>Enable Stripe Billing</strong></summary>
<p>

**Setup:**

1. Woo Subscriptions plugin installed. 
2. A subscription product of any type. 

**Testing instructions:**

1. Go to **WooCommerce → Settings → Payments → Woo Payments**
3. Enable the Stripe Billing setting.
4. Purchase a subscription. 
5. Check that the subscription is set up with Stripe Billing.
    - Go to **WooCommerce → Subscriptions**
    - Edit the subscription. 
    - You should notice it has a WCPay subscription ID.
6. This subscription should behave like a Stripe Billing subscription.

<img width="475" alt="Screenshot 2023-08-31 at 3 06 00 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/97f1a979-5087-40f0-aacf-ef7241bc70bd">

</p>
</details>

<details><summary><strong>Disable Stripe Billing with Subscriptions</strong></summary>
<p>

**Setup:**

1. Woo Subscriptions plugin installed. 
2. Stripe Billing enabled.
3. At least 1 Stripe Billing subscription from:
   - A previous test,
   - Created with WCPay Subscriptions built in functionality, or
   - The test generator - see tools on the project thread peNR48-2u-p2

**Testing instructions:**

1. Go to **WooCommerce → Settings → Payments → Woo Payments**
2. Disable the Stripe Billing setting.
4. You should see a warning notice pop up explaining that Subscriptions will be migrated.

<img width="1058" alt="Screenshot 2023-08-31 at 3 35 24 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/f48984b8-63be-4908-a571-cc0f959eec67">

5. Save settings.
6. A new notice should appear indicating that the migration is in-progress. 

<img width="722" alt="Screenshot 2023-08-31 at 3 44 17 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/260380ac-5267-41a9-a2f3-83102edb22a5">

7. Wait for the migration to complete.
    - You can track the migration on the **Tools → Scheduled Actions** screen. Search for `wcpay_schedule_subscription_migrations` and `wcpay_migrate_subscription` actions. 
9. Refresh the settings page and it should so the migration complete notice. 

<img width="711" alt="Screenshot 2023-08-31 at 3 47 56 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/e26be989-9f4d-4857-8346-1d11b51e5ecc">
</p>
</details>

<details><summary><strong>Choose migrate option</strong></summary>
<p>

**Setup:**

1. Woo Subscriptions inactive.
2. WCPay Subscriptions feature enabled. 
4. Delete the `_wcpay_feature_stripe_billing` option we want to simulate a merchant that has upgraded from WCPay Subscriptions to Woo Subscriptions for the first time.

**Testing instructions:**

1. Purchase a subscription (this will be a Stripe Billing subscription).
1. Enable the Woo Subscriptions plugin.
3. Go to **WooCommerce → Settings → Payments → Woo Payments**
4. You should see the following

<img width="1067" alt="Screenshot 2023-08-31 at 4 14 09 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/d780c460-0681-4dcd-9f5e-7efd8d6eb56b">

5. Click the button to begin migration. 
6. You should see the in-progress notice.

<img width="705" alt="Screenshot 2023-08-31 at 4 17 18 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/1667b7ff-ed61-43ec-a941-a23f9e6d04a7">

7. Wait for the migration to complete. Refresh. 
8. You will see a completed notice. 

<img width="707" alt="Screenshot 2023-08-31 at 4 20 01 pm" src="https://github.com/Automattic/woocommerce-payments/assets/8490476/20ffd4d6-a7cc-4d67-9689-4d413d5af824">
</p>
</details>

There's a lot of depth to these settings and the notices that are shown. They aren't all described above. 

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-09-05 02:38 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7105` or branch name `issue/6508` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=issue/6508) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 3f006861e43b5f57de8d275905082f31c1b31e02
- Build time: 2023-09-05 02:37:59 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-09-07 03:22 UTC, james-allan commented
@diegocurbelo this is the PR I mentioned in our 1:1 last week. Do you mind giving the JS a review just to make sure I'm not breaking any obvious JS rules. 😄 

There's a lot going on in this PR and @mattallan is going to review the whole PR too.

2023-09-07 03:35 UTC, mattallan requested changes
I haven't done any testing of the settings yet but while review the code and discussing [these changes](https://github.com/Automattic/woocommerce-payments/pull/7105/files#diff-61d838bb73eba5daad8c16c1a6b535141ec17a004f0cf7e577b522c20f98d2b3L140-L142) specifically we have come to the agreement that this area needs to be updated to cater for stores that have:
1. disabled the Stripe Billing feature and,
2. is in the middle of migrating over to tokenized WooPayments Subscriptions

For these cases, we would still want the Subscription services to load so that merchants can continue to manage their Stripe Billing subscriptions before it's migrated, but also we continue to process any payments while it's in a pre-migrated state.

For this, we discussed two necessary changes to this:

1. Inside the `WC_Payments_Subscriptions_Service::__construct()` function, bring back the [`if ( ! $this->is_subscriptions_plugin_active() )`](https://github.com/Automattic/woocommerce-payments/blob/4f75334f1cd97b77969b54db83a9a5fa62ada0d0/includes/subscriptions/class-wc-payments-subscription-service.php#L140) condition, but change it to check for `if ( WC_Payments_Features::is_wcpay_subscriptions_enabled() || WC_Payments_Features::is_stripe_billing_enabled() )`
2. Update the `should_load_wcpay_subscriptions()` so that we still load Stripe Billing/WCPay Subscription service classes if we are still migrating subscriptions, i.e. check if the store has existing subscriptions with `_wcpay_subscription_id` metadata

2023-09-07 03:35 UTC, mattallan commented on client/data/settings/selectors.js
> +export const getIsStripeBillingMigrationInProcess = ( state ) => {
Should this be `getIsStripeBillingMigrationInProgress`?

```suggestion
export const getIsStripeBillingMigrationInProgress = ( state ) => {
```

2023-09-07 03:35 UTC, mattallan commented on client/settings/advanced-settings/stripe-billing-notices/migration-progress-notice.tsx
> +import Loadable from 'wcpay/components/loadable';
`Loadable` isn't used

2023-09-07 03:35 UTC, mattallan commented on client/settings/advanced-settings/stripe-billing-notices/migration-progress-notice.tsx
> +	// Don't show the notice it's not eligible.
```suggestion
	// Don't show the notice if it's not eligible.
```

2023-09-08 01:59 UTC, mattallan commented
Hey @james-allan I have a question: There are a handful of `! is_subscriptions_plugin_active()` checks found within the `includes/subscriptions` directory, should these be updated to

```
WC_Payments_Features::is_wcpay_subscriptions_enabled() || WC_Payments_Features::is_stripe_billing_enabled()
```

Some instances:
- [Product service construct](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/subscriptions/class-wc-payments-product-service.php#L96C3-L101C4)
- [limit_subscription_variation_intervals](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/subscriptions/class-wc-payments-product-service.php#L491)
- [limit_subscription_product_intervals](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/subscriptions/class-wc-payments-product-service.php#L449C18-L449C54)

I'm not sure if all of them can be replaced with checking for either wcpay or stripe billing settings, like some instances in the onboarding class.

2023-09-08 05:05 UTC, james-allan commented
> Hey @james-allan I have a question: There are a handful of ! is_subscriptions_plugin_active() checks found within the includes/subscriptions directory, should these be updated to

Good spotting! 

After discussing this together I think we've landed on the right approach here now. We've both reviewed all the uses of `is_subscriptions_plugin_active()` and made a determination in each case if we need to update it. There  were some that should be changed to reflect whether Stripe Billing is in use or not. Some of the cases where we use the check `is_subscriptions_plugin_active()` should stay.

2023-09-08 06:31 UTC, mattallan commented
### Testing

#### WCPay Subscriptions (legacy) + Woo Subscriptions deactivated

- [x] Confirm correct WooPayments setting is shown
- [x] Confirm disabling the setting removes Subscriptions features bundled in WooPayments
- [x] Purchase a subscription product, confirm Stripe Billing subscription
- [x] Process renewal with AS, confirm no payment is processed
- [x] Process renewal with billing clocks, confirm new charge and new order
- [x] Pay for failed order
- [x] Change payment method
- [x] Suspend and cancel subscription
  

#### Stripe Billing + Woo Subscriptions activated

- [x] Confirm new Stripe Billing setting is deactivated by default with a begin migration option
- [x] From having WCPay Subscriptions to activating Woo Subscriptions, purchase a subscription and confirm it's tokenized.
- [x] Enable Stripe Billing and confirm existing tokenized subscription is still tokenized
- [x] Purchase a subscription product and confirm Stripe billing subscription is created
- [x] Process a scheduled action and confirm no payment is taken
- [x] Process renewal, change payment method, suspend and cancel subscription
- [x] Pay for failed renewal
  

#### Regular subscriptions /w Woo Subscriptions activated

- [ ] Purchasing a subscription and confirm no Stripe Billing subscription is created
- [ ] Processing tokenized renewal
    

#### Mid-migration Testing

- [ ] While migrating, purchase a subscription and make sure it's not created as a Stripe Billing
- [ ] With Stripe Billing disabled and subscriptions scheduled for migration, confirm the Stripe billing subscriptions continue to renew
- [ ] ...
  

#### Settings Notice

- [x] No notice when store is using Stripe Billing
- [x] "Begin Migration" notice shown on stores that have the setting disabled at page load but have existing WCPay Subscriptions
- [ ] "Migration starting automatically" notice shown to stores that have existing WCPay Subscriptions and deactivate the feature
- [ ] "Migrated subscriptions" shows

2023-09-11 03:38 UTC, mattallan approved these changes
Awesome work on these changes @james-allan!
I've put this PR through a wide range of tests ([see this comment](https://github.com/Automattic/woocommerce-payments/pull/7105#issuecomment-1711147327)) to test the migration notices on the settings page but also to test stores in different states of the setting enabled and disabled and with existing WCPay Subscriptions, Stripe Billing subscriptions and tokenized 🥴

Let's ship it!

2023-09-11 06:35 UTC, merged