Tmp/check logging changes
Automattic/woocommerce-payments pull request #7503
Opened 2023-10-18 04:09 UTC by jessy-p

2023-10-18 04:15 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7503` or branch name `tmp/check-logging-changes` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=tmp/check-logging-changes) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 253b7cefc5d7b19d5ed49b8126c059a898b2aa76
- Build time: 2023-10-18 04:15:26 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-10-18 16:03 UTC, RadoslavGeorgiev requested changes
The direction looks great, I left a few minor comments.

In general, I'd also like to make sure that all state changes are logged as well. What are your thoughts on dumping and clearing the log every time the state changes? This way we'd store transitions as well, but we'll also be able to see the timestamps of transitions. Keeping API calls in mind, those might be helpful.

2023-10-18 16:03 UTC, RadoslavGeorgiev commented on src/Internal/Payment/Change.php
> +	public function jsonSerialize(): array {
Let's avoid JSON as an idea for now, we can remove this method. The `var_export` in `__toString()` should do the job better, because we'd be seeing times as well.

2023-10-18 16:03 UTC, RadoslavGeorgiev commented on src/Internal/Payment/Change.php
> +		);
Let's wait until https://github.com/Automattic/woocommerce-payments/pull/7471 is merged, and revisit this string generation. The context will also contain serializable objects (intents), and this format might not work, or at least be insufficient.

2023-10-18 16:03 UTC, RadoslavGeorgiev commented on src/Internal/Payment/PaymentContext.php
> +	 * @return array
Let's change this to `@return Change[]` to make it more explicit.

2023-10-18 16:03 UTC, RadoslavGeorgiev commented on src/Internal/Payment/PaymentContext.php
> +	public function get_changes_log(): string {
Let's do this in the `PaymentProcessingService` instead. In the future, when payments are stored in the DB, it will be a class there that stores everything needed, incl. changes/logs.

2023-10-18 16:03 UTC, RadoslavGeorgiev commented on src/Internal/Payment/PaymentContext.php
> +				return (string) $change;
Wouldn't `implode` trigger the conversion to string automatically?

2023-10-18 16:03 UTC, RadoslavGeorgiev commented on src/Internal/Payment/PaymentContext.php
> +		$this->changes[]    = new Change( $key, $this->get( $key ) ?? '', $value );
1. Let's only log _changes_. Presently, everything is only set once, but in the future, we might do the same thing multiple times (ex. extract order data), and we should only log the things that actually changed.
2. `get` would return `null`, let's keep it `null`. In various cases, empty strings are a different thing.

2023-10-19 03:52 UTC, closed without merging

2023-10-19 03:53 UTC, jessy-p commented
Refer #7503