Add WC_Logger_Interface to Logger service to make it backward compatible
Automattic/woocommerce-payments pull request #7614
Opened 2023-11-02 17:07 UTC by zmaglica

Fixes #7612 

#### Changes proposed in this Pull Request

This PR adds a logger interface instead of a concrete logger class to prevent critical errors when logger is overwritten by other plugins.

#### Testing instructions

Make sure to check linked issue on how to reproduce an error. With this change, the error should not be thrown if you follow steps to reproduce on linked issue.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-11-02 17:10 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7614` or branch name `fic/7612-fix-issue-with-logger-class` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fic/7612-fix-issue-with-logger-class) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9b4933e65b387780c4d97171ad4b38fa4afc453c
- Build time: 2023-11-02 17:10:44 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-11-02 17:16 UTC, jessepearson commented
This fixes the issue, thanks for the quick work 😁 

Do we want to change the references for `WC_Logger` to `WC_Logger_Interface` and add a note as to why it's like that?

2023-11-03 03:36 UTC, htdat requested changes
✅ Confirm that this change fixes the issue. 
❓ Suggest some other changes here https://gist.github.com/htdat/200abc0be5037bb48beb6cc437e2846f
❓ May add changelog too. 

❗❗❗ Also note: depends on whether or not we decide to have a patch release for this issue, we may need to rebase it to the patch release branch such as `release/6.7.1`

2023-11-03 09:46 UTC, naman03malhotra reviewed
As per the patch release guide, this PR must branch off from trunk.

2023-11-03 10:23 UTC, jessy-p approved these changes

2023-11-03 10:27 UTC, zmaglica commented
Closing this PR in favor of: https://github.com/Automattic/woocommerce-payments/pull/7623

2023-11-03 10:27 UTC, closed without merging