Calculate next deposit date rather than relying on estimated deposits
Automattic/woocommerce-payments pull request #7648
Opened 2023-11-07 03:32 UTC by brucealdridge

Fixes #7628

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-11-07 03:35 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7648` or branch name `fix/7628-calculate-next-deposit-date` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/7628-calculate-next-deposit-date) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 2776139bbafbc45c0e9ded362b15e66b446e7664
- Build time: 2023-11-07 03:35:15 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-11-08 01:54 UTC, brucealdridge commented
PHP tests are currently failing which is unrelated to this PR.

2023-11-08 12:17 UTC, Jinksi commented
> As this code is not used anywhere it is covered in unit tests.

@brucealdridge  This looks like one PR that we had planned for 6.8 that can safely be merged.

2023-11-09 04:06 UTC, Jinksi approved these changes
This tests well @brucealdridge and the code and tests written are clear and easy to follow. 🙌 I've also tested this in context within the new UI in PR https://github.com/Automattic/woocommerce-payments/pull/7656/files#diff-4c94aa3bacf97fd4b7e483719d334e36d72734af83e88b83cd1fc528e88347f9R29, so you can checkout that branch to see it in action.

Since this is not used by any existing logic, this is safe to merge for a 6.8 release.

I've left some code quality suggestions that (assuming you agree) we can resolve now or in a follow-up PR.

2023-11-09 04:06 UTC, Jinksi commented on client/types/account-overview.d.ts
> +		 */
Nit, non-blocking: it might be worth adding annotations to the other two properties: `interval` and `delay_days`.

2023-11-09 04:06 UTC, Jinksi commented on client/deposits/utils/test/index.ts
> +import * as AccountOverview from 'wcpay/types/account-overview';
Nit: explicitly `import type` to make this easier to understand what's being imported.
```suggestion
import type * as AccountOverview from 'wcpay/types/account-overview';
```

2023-11-09 04:06 UTC, Jinksi commented on client/deposits/utils/index.ts
> +// Internal dependencies
Nit: use the `/**` comment syntax for consistency.
```suggestion
/**
 * Internal dependencies
 */
```

2023-11-09 04:06 UTC, Jinksi commented on client/deposits/utils/test/index.ts
> +		[ '2023-01-01', { interval: 'daily' }, 'January 2nd, 2023' ],
Suggestion: add a case for the `manual` interval.
```suggestion
		[ '2023-01-01', { interval: 'manual' }, '—' ],
		[ '2023-01-01', { interval: 'daily' }, 'January 2nd, 2023' ],
```

2023-11-09 04:06 UTC, Jinksi commented on client/types/account-overview.d.ts
> +		/**
Not a concern for this PR, but I realise we should make this a union type to improve devex and help catch bugs.
```suggestion
		interval: 'manual' | 'daily' | 'weekly' | 'monthly';
```

2023-11-10 00:46 UTC, Jinksi requested changes
I caught a bug during testing – the function returns `undefined`

![image](https://github.com/Automattic/woocommerce-payments/assets/3147296/32c9b3c8-d12f-4503-a9cd-4e1471394b3c)

2023-11-10 00:51 UTC, Jinksi approved these changes
Ignore my last comment! The bug was introduced downstream. 🙃

2023-11-10 01:55 UTC, merged