Update international IP address rule card behavior when the rule is being affected by another configuration
Automattic/woocommerce-payments pull request #7827
Opened 2023-12-04 16:36 UTC by allie500

Fixes #6320 

#### Changes proposed in this Pull Request

This PR modifies the behavior and display of the international IP address rule card if the rule is being affected by the WooCommerce core selling locations general option. Previously, if the WooCommerce core selling locations option was set to 'sell to all countries' we'd show a notice at the bottom of the card but still display the toggle to enable the rule as shown in the screenshot below:

![275852485-4e80f817-04e9-415a-ab7a-4baa484daf8f](https://github.com/Automattic/woocommerce-payments/assets/60988591/d446d6c3-2133-47d3-ab25-f6c9354b1564)

The changes in this PR have updated the rule card display to not show the rule toggle and instead show the notice in the toggle's place with updated text indicating that filter is disabled because the WooCommerce core selling locations option is set to 'sell to all countries'. See the screenshot below:

![Screenshot on 2023-12-04 at 11_35_30](https://github.com/Automattic/woocommerce-payments/assets/60988591/3dd7a533-1b0e-49c7-8eef-c2cdb858bbeb)

The behavior and display of the rule card has not been changed if the the WooCommerce core selling locations option is set to the 'specific countries' or 'all countries except' options.

#### Testing instructions

* Check out this branch.
* All tests should pass.
* Go to WooCommerce > Settings
* Select 'Sell to all countries' in the Selling location(s) dropdown.
* Save.
* Go to Payments > Settings
* Scroll down to the fraud protection section, click advanced, then click configure.
* Scroll down to the International IP Address card and confirm that it looks like the second screenshot above. 
* Next, bring up your Jurassic Tube tunnel and confirm that the card looks okay on mobile.
* Go back to WooCommerce > Settings
* Select 'Sell to specific countries' in the Selling location(s) dropdown.
* Add a country or two to the 'Sell to specific countries' field if needed.
* Save.
* Scroll down to the fraud protection section, click advanced, then click configure.
* Scroll down to the International IP Address card and confirm that the toggle is present and that you have an info notice stating that orders from outside your specific countries will be blocked by the filter.
* Go back to WooCommerce > Settings
* Select 'Sell to all countries, except for...' in the Selling location(s) dropdown.
* Add a country or two to the 'Sell to all countries, except for...' field if needed.
* Save.
* Scroll down to the fraud protection section, click advanced, then click configure.
* Scroll down to the International IP Address card and confirm that the toggle is present and that you have an info notice stating that orders from the following countries will be blocked by the filter.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-12-04 16:41 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7827` or branch name `update/6320-rule-card-behavior-if-affected-by-other-config` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=update/6320-rule-card-behavior-if-affected-by-other-config) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f6d68a3f1f23c855e58b4110e9a0c8ab585df947
- Build time: 2023-12-04 16:41:22 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2023-12-05 15:41 UTC, jessepearson requested changes
I had a question about a variable declaration that was done. I tested and it works either way, so it's not a necessary change if it's better for clarity.

There's the issue of the country names with extended ascii characters not displaying correctly. Do you think you can fix that in this PR without much hassle, or do you think it needs another issue and separate PR?

![Screenshot 2023-12-05 at 11 22 27 AM](https://github.com/Automattic/woocommerce-payments/assets/4634416/6249901a-0942-4c6d-a7c8-d4646c8d4dc1)

2023-12-05 15:41 UTC, jessepearson commented on client/settings/fraud-protection/advanced-settings/cards/international-ip-address.tsx
> +	const supportsAllCountries = 'all' === supportedCountriesType;
Is there a benefit to adding the variable `supportedCountriesType` vs just doing it this way:

```
const supportsAllCountries = 'all' === getSupportedCountriesType();
```

2023-12-05 16:17 UTC, allie500 commented on client/settings/fraud-protection/advanced-settings/cards/international-ip-address.tsx
> +	const supportsAllCountries = 'all' === supportedCountriesType;
No, there is no benefit. I think the one liner is perfectly clear and or course cleaner. Thanks for the suggestion. I've updated it in https://github.com/Automattic/woocommerce-payments/pull/7827/commits/2c9afd5ed76b4bd0952ca489a42a8815362d47e0.

2023-12-05 16:48 UTC, allie500 commented
> There's the issue of the country names with extended ascii characters not displaying correctly. Do you think you can fix that in this PR without much hassle, or do you think it needs another issue and separate PR?
> 
> ![Screenshot 2023-12-05 at 11 22 27 AM](https://private-user-images.githubusercontent.com/4634416/288101115-6249901a-0942-4c6d-a7c8-d4646c8d4dc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTE5MzcsIm5iZiI6MTcwMTc5MTYzNywicGF0aCI6Ii80NjM0NDE2LzI4ODEwMTExNS02MjQ5OTAxYS0wOTQyLTRjNmQtYTdjOC1kNDY0NmM4ZDRkYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDVUMTU1MzU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdhZjZhYTJiYjUwMzA2OTllYzY0ZTNjZWZlZTc5MWMwNGY5MmIwYzQ0YzBiODliZjQ0ZTE4ZDZmMjY2NWY1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.arYwjZK0mn1zlVG2Vmejf24Qdx783l81ldV9ATmvit8)

Thanks for catching this! I looked in to this and it needs to be fixed in Woo core. In the [WooPayments code](https://github.com/Automattic/woocommerce-payments/blob/develop/client/settings/fraud-protection/advanced-settings/allow-countries-notice.tsx#L77) we are getting the countries from `wcSettings.countries`. 

```
...
return (
		<FraudProtectionRuleCardNotice type={ 'info' }>
			{ getNoticeText( supportedCountriesType, isBlocking ) }
			<strong>
				{ settingCountries
					.map(
						( countryCode ) =>
							wcSettings.countries[ countryCode ] ?? false
					)
					.filter( ( element ) => element )
					.join( ', ' ) }
			</strong>
		</FraudProtectionRuleCardNotice>
	);
...
```

If you run `wcSettings.countries['ST']` in the browser console, you get the following value returned:
`'S&atilde;o Tom&eacute; and Pr&iacute;ncipe'`

That is hardcoded in the core countries file:
https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/countries.php#L208

I can open an issue in core to track this.

2023-12-05 17:11 UTC, allie500 commented
> If you run `wcSettings.countries['ST']` in the browser console, you get the following value returned: `'S&atilde;o Tom&eacute; and Pr&iacute;ncipe'`
> 
> That is hardcoded in the core countries file: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/i18n/countries.php#L208
> 
> I can open an issue in core to track this.

Actually, it does look like something on our end as core does properly decode the entities on their end. I'll open a separate issue for it in this repo.

2023-12-06 12:56 UTC, jessepearson approved these changes
Thanks for updating the variable declaration and opening the issue related to the country display. This is good to go 😁

2023-12-07 21:26 UTC, merged