Add active plugin list to compatibility service
Automattic/woocommerce-payments pull request #7933
Opened 2023-12-19 19:41 UTC by allie500

Fixes https://github.com/Automattic/woocommerce-payments-server/issues/3942

#### Changes proposed in this Pull Request

This PR adds the merchant site's active plugin list to the compatibility service.

#### Testing instructions

* TBD

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2023-12-19 19:44 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `7933` or branch name `add/server-3942-compatibility-service-include-active-plugins` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/server-3942-compatibility-service-include-active-plugins) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: b3193729e80248856e1b261728b3fa48d609801c
- Build time: 2023-12-19 19:44:31 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-01-09 16:33 UTC, jessepearson requested changes
Just the one (well, two because of the tests) change as a "just in case" approach.

2024-01-09 16:33 UTC, jessepearson commented on includes/class-compatibility-service.php
> +		$active_plugins = get_option( 'active_plugins' );
It should never happen, but `get_option` can return `false`. We should add a check and if `$active_plugins` is not an array, it should be changed to an empty array to match what's expected to be received at the server. 

A test would be needed to make sure that's working correctly, as well.

2024-01-09 16:57 UTC, jessepearson commented on includes/class-compatibility-service.php
> +		$active_plugins = get_option( 'active_plugins' );
Resolving this per our discussion in slack: p1704818339032419-slack-C01B8KNUYSW

2024-01-09 16:58 UTC, jessepearson approved these changes
Approving pending updates on the server PR.

2024-01-10 12:51 UTC, jessepearson commented
@allie500 I think a test like this can be added:

```php
	public function test_update_compatibility_data_active_plugins_false() {
		// Arrange: Create the expected value to be passed to update_compatibility_data.
		$expected = [
			'woopayments_version' => WCPAY_VERSION_NUMBER,
			'woocommerce_version' => WC_VERSION,
			'active_plugins'      => [],
		];

		$this->break_active_plugins_option();

		// Arrange/Assert: Set the expectations for update_compatibility_data.
		$this->mock_api_client
			->expects( $this->once() )
			->method( 'update_compatibility_data' )
			->with( $expected );

		// Act: Call the method we're testing.
		$this->compatibility_service->update_compatibility_data();

		$this->fix_active_plugins_option();
	}

	private function break_active_plugins_option() {
		update_option( 'temp_active_plugins', get_option( 'active_plugins' ) );
		delete_option( 'active_plugins' );
	}

	private function fix_active_plugins_option() {
		update_option( 'active_plugins', get_option( 'temp_active_plugins' ) );
		delete_option( 'temp_active_plugins' );
	}
```

2024-01-10 13:54 UTC, allie500 commented
> @allie500 I think a test like this can be added:
> 
> ```
> 	public function test_update_compatibility_data_active_plugins_false() {
> 		// Arrange: Create the expected value to be passed to update_compatibility_data.
> 		$expected = [
> 			'woopayments_version' => WCPAY_VERSION_NUMBER,
> 			'woocommerce_version' => WC_VERSION,
> 			'active_plugins'      => [],
> 		];
> 
> 		$this->break_active_plugins_option();
> 
> 		// Arrange/Assert: Set the expectations for update_compatibility_data.
> 		$this->mock_api_client
> 			->expects( $this->once() )
> 			->method( 'update_compatibility_data' )
> 			->with( $expected );
> 
> 		// Act: Call the method we're testing.
> 		$this->compatibility_service->update_compatibility_data();
> 
> 		$this->fix_active_plugins_option();
> 	}
> 
> 	private function break_active_plugins_option() {
> 		update_option( 'temp_active_plugins', get_option( 'active_plugins' ) );
> 		delete_option( 'active_plugins' );
> 	}
> 
> 	private function fix_active_plugins_option() {
> 		update_option( 'active_plugins', get_option( 'temp_active_plugins' ) );
> 		delete_option( 'temp_active_plugins' );
> 	}
> ```

Thanks for the suggestion. I've added the test in https://github.com/Automattic/woocommerce-payments/pull/7933/commits/afdb9b7855f098cdc3c9e06e238213898941a3fe.

2024-01-11 13:19 UTC, jessepearson approved these changes
Everything is working as expected. Thanks for all of the updates done here 😁

2024-01-11 15:48 UTC, merged