[WIP] Format fee description pill for zero fixed rate
Automattic/woocommerce-payments pull request #8044
Opened 2024-01-18 13:28 UTC by KarlisJ

Fixes #6531 

#### Changes proposed in this Pull Request

Right now we use `formatMethodFeesDescription` method to format fee description in the settings pill. The info in the Pill is very simple, just a  "From {fixed} + {percentage}" however the `formatMethodFeesDescription` contains long and complicated logic which is used in `payments->overview` (see https://github.com/Automattic/woocommerce-payments/pull/6949) and potentially other places.

This PR introduces a simple one-use function to perform the simple formatting for the pill. 

WIP. We still need:
- tests
- clean up of `formatMethodFeesDescription` so that it serves only for the actual callers
- some variable renaming can be beneficial 
- Pull up `discountAdjustedFeeRate` calculation as it's duplication from the same file.

#### Testing instructions

- Open `Payments->settings`
- Observe that iDeal pill says "From $0.80" without the percentage part.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-01-18 13:31 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8044` or branch name `fix/6531-calculate-zero-fees-in-settings-pill` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/6531-calculate-zero-fees-in-settings-pill) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a33ad33e4cbf95687e971b6d3ca11e8106eaeb6f
- Build time: 2024-01-18 13:31:15 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-01-30 07:55 UTC, kalessil requested changes

2024-01-30 07:55 UTC, kalessil commented on client/components/payment-methods-list/payment-method.tsx
> +											formatMethodMinimalFee(
Will break injection of ToS link into a pill for incentives.

2024-01-30 07:55 UTC, kalessil commented on client/components/payment-methods-list/payment-method.tsx
> +											formatMethodMinimalFee(
I encourage you to look into `// Some payment methods doesn't have base percentage rate. In this case, the lowest rate will be shown as a start value` comment, that could point to the bug source.

2024-01-31 11:50 UTC, KarlisJ commented
@kalessil 
Thanks for the pointer! The problem here is that all logic of fee formatting is tied to having two variables in the format string - percentage and then fixed. If we want to get `From $0.8`, then we'd have to refactor quite a lot. 

Could we opt in for saying `From 0% + $0.8`?

<img width="697" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/24650518/e721d972-bba1-4c42-b870-874075599ad5">

2024-02-01 13:26 UTC, kalessil commented
@KarlisJ: you are welcome! That's looking better. 

@elizaan36, what are design expectations on the fee pill rendering when the fee is like on the screenshot (.`From 0% + $0.80` or `From $0.80` )?

2024-02-01 16:18 UTC, elizaan36 commented
@kalessil The way this is shown is confusing, however the fee pill will likely be updated to an icon in upcoming design changes so we can rely on the tooltip to provide more context.

So for now, I think this is fine unless @rogermattic has additional feedback to share on the interim display. We're going to take a high level look at how fees are displayed and make design recommendations.

2024-02-02 11:11 UTC, kalessil commented
Thank you @elizaan36 !

2024-02-02 11:13 UTC, kalessil commented
@KarlisJ: `From $0.8` is to go but without a big refactor. If you need more ideas, we can brainstorm this together.

2024-02-05 12:36 UTC, KarlisJ commented
@kalessil `From $0.8` will require refactoring and re-testing `payment->details` screen various options of formatting fees.

> So for now, I think this is fine

I gather from this, that `0% + $0.8` is fine ...

2024-02-05 15:56 UTC, rogermattic commented
@elizaan36  thanks for pinging me on this issue!

@kalessil what Elizabeth suggested is great. I'm just starting to look into all-things-fees so will slowly be taking over these issues related to fees. 

Thanks for working on this!

2024-02-07 09:04 UTC, KarlisJ commented
Thank you, @rogermattic, for looking into this!

> what Elizabeth suggested is great.

Can we clarify what Elizabeth suggested? Is the suggestion to go for `0% + $0.8` until the re-design?

2024-02-07 11:16 UTC, rogermattic commented
> Can we clarify what Elizabeth suggested? Is the suggestion to go for 0% + $0.8 until the re-design?

Yes, I think so:)

2024-02-08 12:46 UTC, kalessil commented
@KarlisJ: is this PR is still relevant?

2024-02-08 12:47 UTC, KarlisJ commented
closed in favor of https://github.com/Automattic/woocommerce-payments/pull/8149#top

2024-02-08 12:48 UTC, closed without merging

2024-02-08 12:48 UTC, KarlisJ commented
closed in favor of https://github.com/Automattic/woocommerce-payments/pull/8149