Add changelog
Automattic/woocommerce-payments pull request #8142
Opened 2024-02-06 18:46 UTC by tpaksu

Fixes #8141

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-02-06 18:49 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8142` or branch name `fix/8141-fraud-prevention-token-site-editor-problem` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8141-fraud-prevention-token-site-editor-problem) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 33fd274bc24c11de5bd3c47b099f44374e52c8e5
- Build time: 2024-02-06 18:49:01 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-02-08 17:03 UTC, allie500 requested changes
Thanks for working on this fix, Taha! I've reviewed the code and manually tested it a bit and I've found an issue. I left inline comments in the three JS files where `const fraudPreventionToken = window.wcpayFraudPreventionToken ?? null;` is used. That is where the issue is. 

If `card_testing_prevention_enabled` is enabled for the account and if the `fraudPreventionToken` token is `null` then the POST request returns a 400 response and the following error is returned on the checkout:

> payment_data[2][value] is not of type string,boolean.

If `null` is replaced with `false` then the POST request returns a 402 response and we get the following:

> We're not able to process this payment. Please refresh the page and try again.

I think this is the better outcome in a rare instance where the token could not be generated or retrieved. That way the shopper will hopefully at least refresh and retry the order and (also hopefully) the error that prevented the token from being generated or retrieved was just a one-off anomaly that won't occur a second time.

All that said, I ran into a bigger issue related to the `null` value. After testing `null` versus `false` with `card_testing_prevention_enabled` enabled, I then disabled `card_testing_prevention_enabled` and refreshed my account cache on the client. Testing with `card_testing_prevention_enabled` disabled then `null` is always passed as the value of `fraudPreventionToken` and the POST request always returns a 400 and the error:

> payment_data[2][value] is not of type string,boolean.

The checkout is broken for shoppers when `card_testing_prevention_enabled` meta is disabled for the account as a result. However if `false` is passed instead the order is processed successfully.

2024-02-08 17:03 UTC, allie500 commented on client/checkout/blocks/generate-payment-method.js
> +		const fraudPreventionToken = window.wcpayFraudPreventionToken ?? null;
I think we should fallback to `false` here instead of `null`. I've included the reasoning in the main review comment.

2024-02-08 17:03 UTC, allie500 commented on client/checkout/blocks/payment-processor.js
> +	return window.wcpayFraudPreventionToken ?? null;
I think we should fallback to `false` here instead of `null`. I've included the reasoning in the main review comment.

2024-02-08 17:03 UTC, allie500 commented on client/checkout/blocks/saved-token-handler.js
> +				window.wcpayFraudPreventionToken ?? null;
I think we should fallback to `false` here instead of `null`. I've included the reasoning in the main review comment.

2024-02-08 19:32 UTC, tpaksu commented on client/checkout/blocks/payment-processor.js
> +	return window.wcpayFraudPreventionToken ?? null;
Yep, this was the one that's causing 400 to be returned. Nice catch! Addressed in [008817f](https://github.com/Automattic/woocommerce-payments/pull/8142/commits/008817fdfd8f563d611c406bc4c28f586a58acb3).

2024-02-08 19:32 UTC, tpaksu commented on client/checkout/blocks/saved-token-handler.js
> +				window.wcpayFraudPreventionToken ?? null;
Thanks for catching this! It is being converted to an empty string when sending to the server. No changes needed on this one too.

2024-02-08 19:32 UTC, tpaksu commented on client/checkout/blocks/generate-payment-method.js
> +		const fraudPreventionToken = window.wcpayFraudPreventionToken ?? null;
Thanks for catching this! It is being converted to an empty string when sending to the server. No changes needed on this one.

2024-02-12 20:16 UTC, allie500 requested changes
Thanks for fixing the issues that I reported earlier. The latest code changes look good. I've run through the testing and everything is working except for card payments on the `twentytwentyfour` theme with `card_testing_prevention_enabled` set to `true`. I also skipped testing Apple Pay as I don't have an iPhone. I think we can get a fellow team member to test that.

Testing Results:

Storefront theme with card testing prevention disabled:

| Payment Method | Result |
| -------------- | ------ |
| Regular checkout using test card | ✅ |
| Regular checkout using saved card | ✅ |
| Regular checkout using one UPE method | ✅ |
| ApplePay | ⏭️ |
| GooglePay | ✅ |
| WooPay | ✅ |


Storefront theme with card testing prevention enabled:

| Payment Method | Result |
| -------------- | ------ |
| Regular checkout using test card | ✅ |
| Regular checkout using saved card | ✅ |
| Regular checkout using one UPE method | ✅ |
| ApplePay | ⏭️ |
| GooglePay | ✅ |
| WooPay | ✅ |


TwentyTwentyFour theme with card testing prevention disabled:

| Payment Method | Result |
| -------------- | ------ |
| Regular checkout using test card | ✅ |
| Regular checkout using saved card | ✅ |
| Regular checkout using one UPE method | ✅ |
| ApplePay | ⏭️ |
| GooglePay | ✅ |
| WooPay | ✅ |


TwentyTwentyFour theme with card testing prevention enabled:

| Payment Method | Result |
| -------------- | ------ |
| Regular checkout using test card | ❌ |
| Regular checkout using saved card | ❌ |
| Regular checkout using one UPE method | ✅ |
| ApplePay | ⏭️ |
| GooglePay | ✅ |
| WooPay | ✅ | 

**Debugging TwentyTwentyFour theme with card testing prevention enabled:**

POST https://my-test-site-domain/wp-json/wc/store/v1/checkout?_locale=user 

Response: 402 (Payment Required)

Console error:
VM474:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

<details><summary>Response body:</summary>

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>Site has been temporarily disabled</title>
		<meta name="description" content="">
		<meta name="author" content="">

		<style>
		body {
			background-color: #f8f8f8;
			font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
			color: #333;
			padding-top: 20px;
		}
		div {
			display: block;
		}
		.container {
			width: 1100px;
			padding-top: 50px;
			margin-left: auto;
			margin-right: auto;
		}
		.error-msg, .support-msg {
			text-align: center;
		}
		.error-msg {
			margin-bottom: 40px;
		}
		.error-msg h1 {
			font-size: 52px;
			display: block;
			margin: 0px;
		}
		.error-msg p {
			font-size: 20px;
			display: block;
			margin: 10px 0;
		}
		.support-msg p {
			font-size: 14px;
			color: #888;
		}
		</style>
	</head>

	<body>
		<div class="container">
			<div class="error-msg">
				<p>This site has been disabled pending subscription renewal.</p>
			</div>
			<div class="support-msg">
				<p>Website owner? If you think you have reached this message in error, please contact support.</p>
			</div>
		</div>
	</body>
</html>
```

</details>

The console error and response body above seem to be a symptom and not the cause. This highjacked response is a known issue and there's an open PR to deal with it: #8102.

That said, I checked the POST request payload and the data looks good. I don't know why Stripe is returning it as a failed payment. In all tests I was using the `4242` card. 

I'll keep digging on this on my end but wanted to share it now to get it on your radar as well.

2024-02-13 13:48 UTC, allie500 approved these changes
I've re-tested the card and saved card payment flows on the JN test site using the twentytwentyfour theme and the payments are now going through. I'm not sure why Stripe was returning a 402 response on those yesterday, but it seems to have been an intermittent issue. With those two tests passing, now all tests are passing. So I think we can ship this.

LGTM

2024-02-13 14:39 UTC, merged