chore: convert payment request CTA to select
Automattic/woocommerce-payments pull request #8155
Opened 2024-02-08 13:50 UTC by frosso

Fixes https://github.com/Automattic/woocommerce-payments/issues/6470

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-02-08 13:53 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8155` or branch name `chore/convert-payment-request-cta-to-select` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=chore/convert-payment-request-cta-to-select) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a920abdca8624cd96174c1aeba277835e6cdd564
- Build time: 2024-02-08 13:53:07 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-02-08 13:55 UTC, frosso commented on client/settings/card-body/styles.scss
> +		margin-bottom: 10px;
I updated this value to slightly better match the designs

2024-02-08 13:55 UTC, frosso commented on client/settings/express-checkout-settings/test/payment-request-button-preview.test.js
> +				id="wcpay-express-checkout-settings-container"
This element is rendered here ( https://github.com/Automattic/woocommerce-payments/blob/a920abdca8624cd96174c1aeba277835e6cdd564/includes/class-wc-payment-gateway-wcpay.php#L883-L883 ), and I needed to add this wrapper to more closely match the behavior of the components when in a non-test environment.

2024-02-12 15:51 UTC, mdmoore requested changes
Nice one! I just noticed that the core select component is setting a `max-width: 25rem` that's preventing the dropdown from working when trying to click on it outside of that width, such as on the down arrow.

<img width="1290" alt="Screenshot 2024-02-12 at 10 39 28 AM" src="https://github.com/Automattic/woocommerce-payments/assets/3473953/21df7744-1c17-4198-8639-af158d2dfe9a">

Otherwise, it's working well!

2024-02-12 15:56 UTC, frosso commented
@mdmoore good eyes, thanks for pointing that out! I'll take a look momentarily by my EOD.

2024-02-13 16:23 UTC, mdmoore approved these changes
LGTM! :shipit:

2024-02-13 16:34 UTC, merged