Add Loading Spinner to “Proceed to Checkout” Button, in Shortcode Cart
Automattic/woocommerce-payments pull request #8379
Opened 2024-03-13 20:15 UTC by lovo-h

Fixes 2561-gh-Automattic/woopay.

#### Changes proposed in this Pull Request

This PR ensures the "Proceed to Checkout" button in the shortcode cart has a loading state. Additionally, it ensures the button (in both the shortcode and the wc-blocks cart) cannot be spam-clicked to unintentionally enque a series of HTTP requests.

#### Testing instructions

**Regression Test: Ensure the Woopay Direct Checkout Flow Continues to Work as Intended**
* Ensure the WooPay Direct Checkout flow is enabled by running `npm run wp option update _wcpay_feature_woopay_direct_checkout 1`.
* Ensure a valid WooPay user is authenticated on WooPay.
* As a shopper, navigate to the Merchant store, add an item to your cart, and navigate to the cart.
* Click the `Proceed to checkout` button.
* Ensure you are navigated to the WooPay checkout.
* Click the `Place Order` button.
* Ensure you have checked out successfully.

**Regression Test: Ensure the Loading Spinner Continues to Appear on the Checkout Button in the wc-blocks Cart**
* As a merchant, navigate to `Pages > Cart` and ensure the Cart page contains the `Cart` wc-block.
* As a shopper, navigate to the Merchant store, add an item to your cart, and navigate to the cart.
* Click the `Proceed to checkout` button.
* Ensure a loading spinner appears on the button.

**Test: Ensure the Loading Spinner Appears in the Checkout Button in the shortcode Cart**
* As a merchant, navigate to `Pages > Cart` and ensure the Cart page contains the `Classic Cart` shortcode.
* As a shopper, navigate to the Merchant store, add an item to your cart, and navigate to the cart.
* Click the `Proceed to checkout` button.
* Ensure a loading spinner appears on the button.

**Test: Ensure Spam Clicking the Checkout Button Does Not Result in Multiple HTTP Requests**
* As a shopper, navigate to the Merchant store, add an item to your cart, and navigate to the cart.
* Open the `Network` tab in the browser's developer tools.
* Spam click the `Proceed to checkout` button multiple times.
* Ensure only one `POST https://woopay.com/wp-json/platform-checkout/v1/sessions` request is created.
* Repeat these steps in the wc-blocks cart or shortcode cart, as needed.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-03-13 20:22 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8379` or branch name `add/2561-woopay-load-spinner-to-button-in-shortcode-cart` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/2561-woopay-load-spinner-to-button-in-shortcode-cart) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: a303fd94662636244ad965f94ac306ac37071b64
- Build time: 2024-03-13 20:22:06 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-03-14 16:19 UTC, rafaelzaleski requested changes
The direct to WooPay flow is not working in the shortcode cart. 
The loading spinner does not appear, and I'm not redirected to WooPay despite being logged in.

✅  Regression Test: Ensure the Woopay Direct Checkout Flow Continues to Work as Intended
✅ Regression Test: Ensure the Loading Spinner Continues to Appear on the Checkout Button in the wc-blocks Cart
❌ Test: Ensure the Loading Spinner Appears in the Checkout Button in the shortcode Cart
✅ Test: Ensure Spam Clicking the Checkout Button Does Not Result in Multiple HTTP Requests



https://github.com/Automattic/woocommerce-payments/assets/4153905/58d28ae3-b953-48cd-a471-30d39025f6b3

2024-03-15 19:13 UTC, lovo-h commented
@rafaelzaleski, as we discussed on Slack, the reason the `Test: Ensure the Loading Spinner Appears in the Checkout Button in the shortcode Cart` failed in your environment was that the WooPay Express button was disabled on the Cart page.

This is a separate issue that is now being tracked on 2593-gh-Automattic/woopay. Good find.

Since the issue you encountered is out of the scope of this issue, I will request a second review as-is.

2024-03-15 19:50 UTC, rafaelzaleski approved these changes
LGTM! 🚀

2024-03-15 19:59 UTC, merged