Resolve collision between WooPayments header and Woo Express survey banner
Automattic/woocommerce-payments pull request #8400
Opened 2024-03-15 16:03 UTC by mordeth

Fixes #8093

#### Changes proposed in this Pull Request
This PR fixes the collision between WooPayments Onboarding header and Woo Express survey banner where the Woo Express Survey header is obscured by the WooPayments header.

<img width="1709" alt="Screenshot 2024-03-15 at 17 46 49" src="https://github.com/Automattic/woocommerce-payments/assets/8667118/14a9652c-b38e-444c-a105-8eef9c6480eb">
<img width="1699" alt="Screenshot 2024-03-15 at 18 00 34" src="https://github.com/Automattic/woocommerce-payments/assets/8667118/066bb6ac-b336-4157-850d-ba540e09d925">

#### Testing instructions
- Start Woo Express trial.
- Make sure that you don't finish Woo Express survey. It should be on the top of the page.
- Once the initial setup is finished, click on the action item to start with setting up WooPayments.
- Use the following [gist](https://gist.githubusercontent.com/ilyasfoo/a2901efacd62f69be737778ba7721e69/raw/5e18c6fc82f52ecf4c552cec5bc3b092540338dd/jQueryJITM) to force show the survey banner.
- Verify on the wizard page the survey banner is below WooPayments header.

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-03-15 16:06 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8400` or branch name `fix/8093-onboarding-collides-with-jitm-banners` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8093-onboarding-collides-with-jitm-banners) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: e3a89f1037544455ac699be5689be625ba1e7e79
- Build time: 2024-03-15 16:06:21 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-03-21 02:02 UTC, elazzabi requested changes
Left a small request to make the comment clearer.

Also, for my curiosity, I asked on Slack for more details about this decision p1710986366846829/1710986315.983159-slack-C03KTTK2YMA

2024-03-21 02:02 UTC, elazzabi commented on client/onboarding/style.scss
> +	// Reposition JITM banners below the fixed onboarding header.
Just to make it clearer 😄 
```suggestion
	// Reposition Jetpack's JITM (Just in time messages) banners below the fixed onboarding header.
```

2024-03-26 22:35 UTC, elazzabi approved these changes
After the discussion on Slack, it's up to the team to decide what's the best approach here. Removing my block to merge if we decide to do so.

2024-03-27 16:14 UTC, elizaan36 commented
imo this survey should be removed. There shouldn't be any competing calls to action during WooPayments onboarding, especially non-essential ones like this. It's a distraction that can impact activation.

2024-03-28 07:45 UTC, vladolaru commented
> imo this survey should be removed. There shouldn't be any competing calls to action during WooPayments onboarding, especially non-essential ones like this. It's a distraction that can impact activation.

Totally agree, @elizaan36

2024-03-28 09:07 UTC, mordeth commented
I've revised the initial approach and eliminated the JITM notices entirely from the onboarding page to ensure there are no distractions.

2024-03-28 11:16 UTC, oaratovskyi approved these changes
It was tricky to test, but it works! :shipit: 
Testing instructions are slightly different, see p1711623868207219-slack-C03KTTK2YMA

2024-03-28 11:18 UTC, elazzabi approved these changes
Removing it completely looks like a better choice! Approving :shipit:

2024-03-28 12:16 UTC, merged