Increase unit test coverage for WooPay direct checkout flow
Automattic/woocommerce-payments pull request #8407
Opened 2024-03-16 20:12 UTC by ricardo

Fixes 2554-gh-Automattic/woopay

#### Changes proposed in this Pull Request

TBD

#### Testing instructions

* Run `npm run test:php` and ensure all tests pass.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [x] Covered with tests (or have a good reason not to test in description ☝️)
- [x] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-03-16 20:16 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8407` or branch name `dev/increase-woopay-direct-checkout-unit-test-coverage` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/increase-woopay-direct-checkout-unit-test-coverage) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 66640ca76753e68598ea6aee37bfb38443c856fe
- Build time: 2024-03-16 20:16:06 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-04-04 05:15 UTC, ricardo commented
Assigning @cesarcosta99 as reviewer based on the WooPay PR round-robin assignment.

2024-04-04 22:31 UTC, cesarcosta99 requested changes
All tests passed 🎉

 Just a couple of points:
- It was mentioned in the test coverage that we've added `WC_Payments_WooPay_Direct_Checkout` tests but I haven't seen any. Did we decide not adding any tests for that class, or maybe missed it?
- I left a suggestion below about doing another test case for completeness.

2024-04-04 22:31 UTC, cesarcosta99 commented on tests/unit/test-class-wc-payments-features.php
> +	public function test_is_woopay_direct_checkout_enabled_returns_true() {
To get complete coverage on this we should have a `test_is_woopay_direct_checkout_enabled_returns_false_when_first_party_auth_is_disabled` test. Do we have a reason for not including it?

2024-04-05 19:36 UTC, ricardo commented on tests/unit/test-class-wc-payments-features.php
> +	public function test_is_woopay_direct_checkout_enabled_returns_true() {
Good call. Fixed in https://github.com/Automattic/woocommerce-payments/pull/8407/commits/aa95fc740e95bee97bebfdd2152a95a7a0af4698.

2024-04-05 19:36 UTC, ricardo commented
> It was mentioned in the test coverage that we've added `WC_Payments_WooPay_Direct_Checkout` tests but I haven't seen any. Did we decide not adding any tests for that class, or maybe missed it?

@cesarcosta99, The description on 2595-gh-Automattic/woopay was actually outdated about this one. I listed this test as a TODO for myself, but later realized there weren't any meaningful tests I could write about that class since it basically just enqueues the direct checkout scripts.

> I left a suggestion below about doing another test case for completeness.

Good call! I have added the test and requested a re-review.

2024-04-08 20:24 UTC, cesarcosta99 approved these changes
LGTM and tests well :shipit:

2024-04-08 21:09 UTC, merged