Fix charm pricing and rounding for non-decimal currencies
Automattic/woocommerce-payments pull request #8723
Opened 2024-04-26 23:17 UTC by reykjalin

Fixes #7724

## Changes proposed in this Pull Request

* Use `WC_Payments_Localization_Service` to determine the number of decimals for a given currency.
    * This means decimals are now based on information in WC Core.

## Testing instructions

> [!NOTE]
> This section is incomplete.

Buy a product with the following types of currencies and make sure the charged amounts match what is shown to the customer on the frontend:

1. The store's default currency.
2. A currency with decimals that's not the store currency (e.g. `EUR`, `USD`, `CAD`).
3. A currency that has no decimals in WC Core or Stripe (e.g. `JPY`).
4. A currency that has decimals in Stripe, but no decimals in WC Core (e.g. `ISK`, `TWD`).

Repeat the above tests with at least the following combinations of rounding and charm pricing applied and make sure the charged amounts match what is shown to the customer on the frontend:

1. No charm pricing, no rounding.
2. Some charm pricing, no rounding.
3. No charm pricing, some rounding.
4. Some charm pricing, some rounding.

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-04-26 23:20 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8723` or branch name `fix/mccy-charm-and-rounding-for-non-decimal-currencies` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/mccy-charm-and-rounding-for-non-decimal-currencies) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: eec3955288b48702692925d7ed11ab8c62ef6d5a
- Build time: 2024-04-26 23:20:16 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-04-27 05:01 UTC, reykjalin reviewed
I've added comments noting where the actual impactful changes are in this PR because the changes introduced _a lot_ of noise.

It'd be nice to make sure whoever reviews this checks over the tests to make sure I'm not doing anything wrong there, but those changes are just to:

1. Instantiating a localization service class; and
2. Providing that service to any `Currency` class instantiations.

No functionality in the tests was changed.

There were a couple tests that needed a more involved set of changes; `test-class-multi-currency.php` and `test-class-frontend-currencies.php`, but the changes still follow that same theme of making sure a localization service is available to `Currency` instances.

2024-04-27 05:01 UTC, reykjalin commented on includes/multi-currency/Currency.php
> +		$this->is_zero_decimal = 0 === $this->localization_service->get_currency_format( $code )['num_decimals'];
This is the real meat of the change here. Instead of relying on our tailor-made list of "0-decimal currencies" based on Stripe's list we instead rely on the currency information defined by WC Core.

The rest of the changes are all reacting to the additional `$localization_service` parameter that's passed into the class constructor.

2024-04-27 05:01 UTC, reykjalin commented on includes/multi-currency/Currency.php
> +		$this->rate                 = $rate;
Even though it's possible to just instantiate the localization service via `new WC_Payments_Localization_Service();` I chose to pass the `$localization_service` to the constructor for 2 reasons:

1. It matches the general pattern we use when classes depend on services; and
2. There are a couple of tests that make mocking the localization service necessary, and it's much easier when the localization service is passed as a parameter to the constructor.

2024-05-05 16:15 UTC, cesarcosta99 requested changes
Good work here! Changes look good and test well 💯 I only left a 🤏 request about an argument description.

- Buy products in all those currencies ✅ 
    - USD, EUR, JPY and ISK
- Subscriptions compatibility ✅ 
    - USD, EUR, JPY and ISK
- Make sure the rounding and charm pricing options are correct ✅ 
    - EUR, JPY and ISK
- Make sure different combinations of rounding and charm pricing options are shown correctly in the preview ✅ 
    - EUR, JPY and ISK 
- Process payments ✅
    - Buy simple product ✅ 
        - USD as default currency
        - EUR with some rounding and no charm pricing
        - JPY with no rounding and some charm pricing
        - ISK with some rounding and some charm pricing
    - Buy subscription product and process renewal ✅ 
        - USD as default currency
        - EUR with some rounding and no charm pricing
        - JPY with no rounding and some charm pricing
        - ISK with some rounding and some charm pricing

2024-05-05 16:15 UTC, cesarcosta99 commented on includes/multi-currency/Currency.php
> +	 * @param WC_Payments_Localization_Service $localization_service Three letter currency code.
Fixing the argument description.

```suggestion
	 * @param WC_Payments_Localization_Service $localization_service Localization service instance.
```

2024-05-07 01:15 UTC, reykjalin commented on includes/multi-currency/Currency.php
> +	 * @param WC_Payments_Localization_Service $localization_service Three letter currency code.
Thank you for catching this, I've applied your suggested changes 💯

2024-05-07 01:16 UTC, reykjalin commented
@cesarcosta99 I've triggered the "merge when ready" flow, so this should be merged upon your approval 🙂

2024-05-07 13:50 UTC, cesarcosta99 approved these changes
LGTM

2024-05-07 13:57 UTC, merged

2024-06-07 23:55 UTC, pierorocca commented
Awesome work here @reykjalin.