Revert Add Multi-Currency Support to Page Caching via Cookies
Automattic/woocommerce-payments pull request #8738
Opened 2024-04-30 05:01 UTC by ricardo

#### Changes proposed in this Pull Request

- Revert Automattic/woocommerce-payments#8534

#### Testing instructions

**Prerequisites**

- Switch to this branch.
- Enable the multi-currency feature in WooPayments settings and configure a few different currencies.

**Test 1: Ensure the `wcpay_currency` cookie is no longer set**

1. Clear your browser cookies to ensure a fresh start for this test.
2. Visit your site and switch to a different currency using the currency switcher provided by WooPayments.
3. After switching currencies, check your browser's developer tools under the Application > Storage tab and ensure there is no `wcpay_currency` cookie.

**Test 2: Ensure product pages are served from Batcache**

1. Clear your browser cookies to ensure a fresh start for this test.
2. Follow the instructions on how to set up Batcache on your local environment: pcrvl0-1cG-p2
3. Visit a product page and refresh it once.
4. Ensure the page is served from Batcache by inspecting the page source code.

**Note:** It's expected that the page is not served from cache if there's an active WP session, or if you have switched the store currency. To ensure a clear state for this test, clear your browser cookies.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-04-30 05:06 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8738` or branch name `revert-8534-8130/add-cookie-product-cache-per-currency` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=revert-8534-8130/add-cookie-product-cache-per-currency) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 5fc6512428304c3724cc3f4f91dc62d9b302bed4
- Build time: 2024-04-30 05:06:03 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-05-01 05:46 UTC, reykjalin requested changes
The code changes look good aside from a log file I don't think you meant to commit.

I wasn't able to follow the testing instructions because I ran into issues setting up memcached and batcache. We can continue to discuss that in pcrvl0-1cG-p2#comment-604

2024-05-01 05:46 UTC, reykjalin commented on logstash.log
I don't think this file is supposed to be here, so I suggest we remove this? 🤔

2024-05-01 16:35 UTC, ricardo commented on logstash.log
I might have added it accidentally when committing the changelog entry.

2024-05-01 20:41 UTC, reykjalin approved these changes
Looks good and tests well 🎉 

I had to make sure the PRBs were not shown on product pages to make sure there was no WC session created, and after doing that the test worked as expected. Batcache is able to cache both the front page and product pages 🙌

2024-05-01 21:32 UTC, merged