Fix Shortcode Orders When Using WooPay Direct Checkout
Automattic/woocommerce-payments pull request #8802
Opened 2024-05-08 18:13 UTC by lovo-h

Fixes #8775 
Fixes #8628 

#### Changes proposed in this Pull Request

The changes in this PR ensure that when we reuse a draft order, it is updated with all necessary details (address, currency, etc.). 

Previously, when a draft order was created through the Direct Checkout flow, it was re-used to avoid a "stock: 1" bug (see https://github.com/Automattic/woocommerce-payments/issues/7256 for details). However, when reusing the draft order, the order did not include all the necessary information. 

Now, when a draft order is created through the Direct Checkout flow, it will still be re-used to avoid the "stock: 1" bug but the order will also be marked as "pending" so that it gets updated (as it normally would) during checkout.

#### Testing instructions

**Confirm issue: Shortcode orders are missing address**
* Switch over to the `develop` branch.
* Confirm the issue is reproducible when following the steps outlined in #8775.

**Confirm solution: Shortcode orders are not missing address**
* Switch over to this branch: `fix/8775-direct-checkout-shortcode-orders`.
* Confirm the issue is not reproducible when following the steps outlined in #8775.

**Confirm issue: Currency switcher doesn't work with shortcode checkout**
* Switch over to the `develop` branch.
* Confirm the issue is reproducible when following the steps outlined in #8628.

**Confirm solution: Currency switcher works with shortcode checkout**
* Switch over to this branch: `fix/8775-direct-checkout-shortcode-orders`.
* Confirm the issue is not reproducible when following the steps outlined in #8628.

**Regression Test: Ensure Purchasing a Product With 1 Stock Does Not Fail** (see #7256 for details)
* Ensure the WooPay Direct Checkout flow is enabled.
* Create an item with only 1 stock and run the following test scenarios (you will have to update the stock back to 1 after each test):
    * Use the WooPay button from the cart page and pay through the WooPay checkout.
    * Navigate to the cart page before going to the Merchant checkout and pay through the Merchant checkout (make sure not to type a valid WooPay address in the email field).
    * Navigate to the cart page before navigating to the Merchant checkout and pay through the WooPay Button.
    * Navigate to the cart page before navigating to the Merchant checkout and pay using the WooPay email input.
    * Navigate directly to the Merchant checkout and pay through the Merchant checkout (make sure not to type a valid woopay address in the email field).
    * Navigate directly to the Merchant checkout and pay through the WooPay button.
    * Navigate directly to the Merchant checkout and pay through the WooPay email input.
* Repeat these tests for both the shortcode cart/checkout and, optionally, the wcBlocks cart/checkout.
* As a merchant, ensure the address appears on each order, in the admin dashboard. 

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-05-08 18:16 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8802` or branch name `fix/8775-direct-checkout-shortcode-orders` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/8775-direct-checkout-shortcode-orders) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 4d1a8926b447b034a7cd84108a98e1af8be7c3fe
- Build time: 2024-05-08 18:16:00 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-05-09 02:48 UTC, lovo-h commented
@reykjalin, I made a minor change to fully address the following issue:
* #8628

[The change](https://github.com/Automattic/woocommerce-payments/pull/8802/commits/fdc538f53a394e015f2859913757499c6d9b80ab) ensures that an order is considered to be in one single state (either "draft" or "pending payment") in the current session.

2024-05-10 04:30 UTC, reykjalin requested changes
Looks great and all the tests pass 💯 

Had one small nitpick, but otherwise this is looking fiiiine 👌

2024-05-10 04:30 UTC, reykjalin commented on includes/class-wc-payments-woopay-direct-checkout.php
> +		if ( ! $is_checkout || $is_already_defined_order_id || $is_order_awaiting_payment || ! $is_draft_order_exists ) {
> [!NOTE]
> This is a nitpick.

Can we call this variable either `$does_draft_order_exist` or `$has_draft_order`? The `is` at the start here makes it a bit weird to read 😅 

```suggestion
		$does_draft_order_exist = ! empty( WC()->session->get( 'store_api_draft_order' ) );
		if ( ! $is_checkout || $is_already_defined_order_id || $is_order_awaiting_payment || ! $does_draft_order_exist ) {
```

```suggestion
		$has_draft_order = ! empty( WC()->session->get( 'store_api_draft_order' ) );
		if ( ! $is_checkout || $is_already_defined_order_id || $is_order_awaiting_payment || ! $has_draft_order ) {
```

2024-05-10 20:28 UTC, reykjalin approved these changes

2024-05-10 21:22 UTC, merged