WIP: Render ECE buttons
Automattic/woocommerce-payments pull request #8818
Opened 2024-05-14 14:07 UTC by rafaelzaleski

Fixes #

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-05-14 14:10 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `8818` or branch name `feat/8772-render-ece-buttons` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=feat/8772-render-ece-buttons) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 163d070774d7b68926d965c3690fe3b54cd02475
- Build time: 2024-05-14 14:10:15 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-05-16 20:37 UTC, cesarcosta99 requested changes
Code looks good overall! Before I dive into testing, I wanted to point out some suggestions. Mostly are about renaming some methods and variables, which is reasonable since we're splitting the approaches.

2024-05-16 20:37 UTC, cesarcosta99 commented on client/express-checkout/blocks/index.js
> +const ApplePayPreview = () => <img src={ applePayImage } alt="" />;
Perhaps would be better to declare and export the `ApplePayPreview` component inside the `apple-pay-preview` file?

2024-05-16 20:37 UTC, cesarcosta99 commented on includes/express-checkout/class-wc-payments-express-checkout-button-handler.php
> +use WCPay\Logger;
Suggestion to put all imports together.

```suggestion
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use WCPay\Exceptions\Invalid_Price_Exception;
use WCPay\Fraud_Prevention\Fraud_Prevention_Service;
use WCPay\Logger;
```

2024-05-16 20:37 UTC, cesarcosta99 commented on client/express-checkout/index.js
> +	const trackPaymentRequestButtonClick = ( source ) => {
Should we rename this to `trackExpressCheckoutButtonClick`?

2024-05-16 20:37 UTC, cesarcosta99 commented on client/express-checkout/index.js
> +	let paymentRequestType;
Should we rename this to `expressCheckoutType`?

2024-05-16 20:37 UTC, cesarcosta99 commented on client/express-checkout/index.js
> +		const paymentRequestTypeEvents = {
Should we rename this to `expressCheckoutTypeEvents`?

2024-05-16 20:37 UTC, cesarcosta99 commented on client/express-checkout/index.js
> +		createPaymentRequestButton: ( elements, options ) => {
Should we rename this to `createExpressCheckoutButton`

2024-05-16 20:37 UTC, cesarcosta99 commented on client/express-checkout/index.js
> +	const wcpayPaymentRequest = {
Should we rename this to `wcpayExpressCheckout`?

2024-05-16 20:37 UTC, cesarcosta99 commented on client/express-checkout/index.js
> +		startPaymentRequest: ( options ) => {
Should we rename this to `startExpressCheckout`?

2024-05-16 20:37 UTC, cesarcosta99 commented on client/express-checkout/index.js
> +		attachPaymentRequestButtonEventListeners: (
I don't want to sound too repetitive here but from this point forward, we still have a lot of references to "payment request" that we may want to rename.

2024-05-17 01:01 UTC, rafaelzaleski commented on client/express-checkout/index.js
> +	const trackPaymentRequestButtonClick = ( source ) => {
It's unclear how much of this code will be retained once we start processing payments. 
I also plan to refactor these files once I jump into payment processing. I'll assess whether it's easier to delete everything that is currently unused or simply rename everything 🤔

2024-05-17 13:09 UTC, rafaelzaleski commented on client/express-checkout/index.js
> +	const trackPaymentRequestButtonClick = ( source ) => {
I've updated some variable names and cleaned up the JavaScript to achieve a near-minimal implementation. I've requested another review.

2024-05-17 19:12 UTC, cesarcosta99 requested changes
Thanks for the latest changes and cleaning things up a bit. I've tested it and everything worked as expected, except for ApplePay which I can't test it. I left one  last (and minor 🤏) suggestion before giving the final approval.

**Before enabling ECE**

- Checkout with GooglePay at the checkout page ✅ 
- Checkout with GooglePay in the product page ✅
- Checkout with ApplePay ⚠️
    - I don't have ApplePay set up, if needed, feel free to ask someone else from the team to test it.
- Checkout with the WooPay button from the checkout page ✅
- Checkout with the WooPay button from the product page ✅
- Ensure the ECE buttons are not rendered when the feature flag is disabled ✅
    - Checked product page, shortcode cart, shortcode checkout, cart Block and checkout Block.

**After enabling ECE**

- Confirm that the ECE buttons are rendering ✅
    - Checked product page, shortcode cart, shortcode checkout, cart Block and checkout Block.
- Ensure that the PRB buttons are not rendered ✅
    - Checked product page, shortcode cart, shortcode checkout, cart Block and checkout Block.

2024-05-17 19:12 UTC, cesarcosta99 commented on client/express-checkout/blocks/apple-pay-preview.js
> +export const ApplePayPreview = () => <img src={ applePayImage } alt="" />;
Here I'd export the component as default as this is the main and only component of this file.

```suggestion

const ApplePayPreview = () => <img src={ applePayImage } alt="" />;

export default ApplePayPreview;
```

2024-05-17 19:12 UTC, cesarcosta99 commented on client/express-checkout/blocks/index.js
> +import { ApplePayPreview } from './apple-pay-preview';
By updating how that component is exported, we need to update the import too.

```suggestion
import ApplePayPreview from './apple-pay-preview';
```

2024-05-17 20:11 UTC, cesarcosta99 approved these changes
LGTM :shipit:

2024-05-20 13:23 UTC, merged