feat: tokenized cart PRB PDP session handler
Automattic/woocommerce-payments pull request #9021
Opened 2024-06-26 09:06 UTC by frosso

Fixes #

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-06-26 09:09 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9021` or branch name `feat/tokenized-cart-pdp-session-handler` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=feat/tokenized-cart-pdp-session-handler) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: e06789087aedc6b33620ebf6e678c16c807d6bcf
- Build time: 2024-06-26 09:09:13 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-07-18 16:04 UTC, frosso reviewed
Sorry for the notification galore - I forgot to publish these comments as inline explanation of the changes

2024-07-18 16:04 UTC, frosso commented on client/tokenized-payment-request/cart-api.js
> -			'Cart-Token': response.headers.get( 'Cart-Token' ),
No longer necessary to save this for anonymous carts.

2024-07-18 16:04 UTC, frosso commented on client/tokenized-payment-request/cart-api.js
> -					: undefined,
In the case of PDPs, the cart will no longer be "anonymous" - we'll always provide cookies to identify the customer.

2024-07-18 16:04 UTC, frosso commented on client/tokenized-payment-request/cart-api.js
> -					: undefined,
In the case of PDPs, the cart will no longer be "anonymous" - we'll always provide cookies to identify the customer.

2024-07-18 16:04 UTC, frosso commented on client/tokenized-payment-request/cart-api.js
> -			credentials: 'omit',
In the case of PDPs, the cart will no longer be "anonymous" - we'll always provide cookies to identify the customer.

2024-07-18 16:04 UTC, frosso commented on client/tokenized-payment-request/cart-api.js
> -				credentials: 'omit',
In the case of PDPs, the cart will no longer be "anonymous" - we'll always provide cookies to identify the customer.

2024-07-18 16:04 UTC, frosso commented on includes/class-wc-payments-payment-request-button-handler.php
> -			add_filter( 'rest_pre_dispatch', [ $this, 'tokenized_cart_store_api_nonce_overwrite' ], 10, 3 );
We no longer need to overwrite the nonce value

2024-07-18 16:04 UTC, frosso commented on includes/class-wc-payments-payment-request-button-handler.php
> +				'tokenized_cart_session_nonce' => wp_create_nonce( 'tokenized_cart_session_nonce' ),
I added a new nonce for product pages

2024-07-18 16:04 UTC, frosso commented on includes/class-wc-payments-payment-request-button-handler.php
> -				'tokenized_order_nonce'     => wp_create_nonce( 'wc_store_api' ),
Here I just added the `tokenized_cart_session_nonce` nonce and renamed the `pay_for_order` nonce to a more generic `store_api_nonce`.
The rest of the changes are just indentation.

2024-07-18 16:04 UTC, frosso commented on client/tokenized-payment-request/payment-request.js
> +			this.paymentRequestCartApi.useSeparateCart();
I renamed the `createAnonymousCart()` method to `useSeparateCart()` - since the cart is no longer "anonymous" (we're sending cookies this time - we weren't before)

2024-07-24 16:27 UTC, brettshumaker requested changes
Confirmed that this is all working as expected.  Do you know what's going on with these failing tests, though?

```
1) WC_Payments_Payment_Request_Session_Test::test_restores_cart_data_on_order_received_page
Exception: Invalid token: cookie and session customer mismatch

2) WC_Payments_Payment_Request_Session_Test::test_does_not_restore_cart_data_when_missing_query_parameter
Exception: Invalid token: cookie and session customer mismatch
```

2024-07-29 12:01 UTC, frosso commented
> Do you know what's going on with these failing tests, though?

@brettshumaker thank you for pointing it out, I'm not sure why the tests were passing before. In any case, after debugging, I noticed that the incorrect session handler was lingering across test cases. So I added some cleanup steps in 6f1d7613846f76ca46735288650b8150888358d1 to solve for it.

2024-07-29 15:42 UTC, brettshumaker approved these changes

2024-07-30 08:23 UTC, merged