Pass Blocks checkout appearance on init WooPay
Automattic/woocommerce-payments pull request #9075
Opened 2024-07-09 18:59 UTC by hsingyuc

#### Changes proposed in this Pull Request
This PR is part of [Spike – Global Themes Support](https://woopayp2.wordpress.com/2024/07/01/spike-global-themes-support/) [proof of concept](https://woopayp2.wordpress.com/2024/07/01/spike-global-themes-support/#proof-of-concept-for-option-3-preferred).

We reuse `getAppearance` to select styles by elements from the blocks checkout page and send them to WooPay on initialization.

#### Testing instructions
1. Install and activate a [theme that supports the site editor](https://wordpress.com/themes/filter/full-site-editing) from admin -> appearance -> theme
2. Update colors by visiting Theme -> Editor -> Styles -> Colors ( ex. background color )
3. As a shopper, go to blocks checkout page and initialize WooPay checkout

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-07-09 19:02 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9075` or branch name `add/pass-blocks-checkout-appearance-on-init-woopay` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/pass-blocks-checkout-appearance-on-init-woopay) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: ce2148bb12395c0101f87dfc39fdde44f815fc2f
- Build time: 2024-07-09 19:02:06 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-07-12 19:26 UTC, alefesouza commented
@hsingyuc the appearance data is not being sent when clicking the WooPay button, only works on the email field redirect, is that expected?

2024-07-15 19:49 UTC, hsingyuc commented
>@hsingyuc the appearance data is not being sent 

Do you mean you log `appearance` [here](https://github.com/Automattic/woocommerce-payments/blob/26183444668d80954f5cf158e06b8b2c9ef63621/client/checkout/api/index.js#L463) and nothing logged?

> when clicking the WooPay button on blocks checkout page, only works on the email field redirect, is that expected?

@alefesouza When click the WooPay button on the Blocks checkout page, it should work as below:

https://github.com/user-attachments/assets/7dc8399c-cde8-4728-abed-2670cf49e855

2024-07-16 00:57 UTC, alefesouza requested changes
@hsingyuc on your video for some reason the express checkout button is using the fallback instead of redirect to WooPay without opening the popup, could you take a look? On the following video the styles are being applied when using the email redirect but not when clicking the button without the fallback:

https://github.com/user-attachments/assets/b8d9885c-f773-44a6-861a-8213087be8bb

2024-07-16 21:56 UTC, hsingyuc commented
@alefesouza I'm having hard time to hit first-party auth but I pass blocks checkout appearance on first-party auth, can you test it for me?  Thanks!

2024-07-17 12:07 UTC, hsingyuc commented
@alefesouza I got first-party auth working, added a fix when on NUX and updated the test instructions.  Thank you!

2024-07-18 19:01 UTC, alefesouza approved these changes
LGTM, thanks @hsingyuc!

2024-07-19 02:23 UTC, merged