Fix Express Checkout Element button width
Automattic/woocommerce-payments pull request #9094
Opened 2024-07-13 01:46 UTC by ricardo

Fixes #9005 

#### Changes proposed in this Pull Request

- Reset ECE button iframe `max-width` property to its default value.

#### Testing instructions

1. Enable ECE by setting the `_wcpay_feature_stripe_ece` option to `1`.
2. As a merchant, set the store theme to Storefront via **Appearance > Themes**.
3. Enable the WooPay button for comparing widths.
4. As a shopper, navigate to a simple product page and ensure the ECE button's width is the same as the WooPay button.
5. Add a simple product to the cart.
6. Navigate to the cart and checkout pages, and ensure the ECE button's width is the same as the WooPay button.

-------------------

- [x] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-07-13 01:49 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9094` or branch name `fix/9005-fix-ece-button-width` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9005-fix-ece-button-width) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f58b6742e474956396b33b3b85e6b9ecc83eac70
- Build time: 2024-07-13 01:49:34 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-07-13 15:09 UTC, rafaelzaleski requested changes
It works well, and I’m glad you found a simple solution for this issue. 
Now, we just need to apply the same fix to the Blocks implementation.

2024-07-13 15:09 UTC, rafaelzaleski commented on client/checkout/express-checkout-buttons.scss
> +	#wcpay-express-checkout-element iframe {
This currently only selects the iframe in the shortcode implementation. We need to also include the selectors for the Blocks implementation.

![Screen Shot 2024-07-13 at 12 07 00 PM](https://github.com/user-attachments/assets/996c7698-f463-41c0-b1f4-29808371340e)

2024-07-13 17:44 UTC, ricardo commented on client/checkout/express-checkout-buttons.scss
> +	#wcpay-express-checkout-element iframe {
Thanks for the catch. My bad for missing it. Fixed in https://github.com/Automattic/woocommerce-payments/pull/9094/commits/f8c6d397ac37380f33cd64fa0aa9d030ba4989d9.

2024-07-15 08:22 UTC, rafaelzaleski approved these changes
LGTM!

2024-07-15 08:29 UTC, merged