Add/test mode badge classic checkout
Automattic/woocommerce-payments pull request #9495
Opened 2024-09-26 16:01 UTC by danielmx-dev

Fixes #9487

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-09-26 16:05 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9495` or branch name `add/test-mode-badge-classic-checkout` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=add/test-mode-badge-classic-checkout) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: f27a829198cbde868df596341cdc31c54d6fcfc0
- Build time: 2024-09-26 16:05:25 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-09-26 18:01 UTC, danielmx-dev commented
After reviewing my own screenshots I noticed that the badge looked a bit off, so I just pushed a commit to vertically center it.

![image](https://github.com/user-attachments/assets/d04801be-3ea0-4fd5-a095-68a88dbbc315)

Despite looking a bit off in the description screenshots, the badge should be properly centered now during testing.

2024-09-30 14:11 UTC, frosso submitted a review, later dismissed
Some small changes for i18n. I'll take care of them tomorrow.

I also wonder if we could benefit from some horizontal spacing between the label and the payment method name
<img width="365" alt="Screenshot 2024-09-30 at 4 11 03 PM" src="https://github.com/user-attachments/assets/a584be11-637c-41ba-9f24-f06fb0b87032">

2024-09-30 14:11 UTC, frosso commented on includes/class-wc-payment-gateway-wcpay.php
> +				$test_mode_badge = '<span class="test-mode badge">Test Mode</span>';
We'll need to use the `__()` i18n wrapper, here

2024-10-01 16:17 UTC, frosso commented
<img width="800" alt="Screenshot 2024-10-01 at 6 16 31 PM" src="https://github.com/user-attachments/assets/ad2c7981-7220-4069-9d6b-a03afa9167cd">
Updated to have i18n wrapper, added 8px spacing in 7b273a6e4 .

Re-assigning for internal review, as discussed in team meeting.

2024-10-01 18:30 UTC, gpressutto5 commented
@danielmx-dev @frosso FYI paJDYF-foh-p2#comment-26617

2024-10-14 14:24 UTC, danielmx-dev commented
I have pushed a commit https://github.com/Automattic/woocommerce-payments/pull/9495/commits/4daaf36fb87f854ee50673374ec75f2fea770443 to only render the badge for the credit card payment method as it was already done for blocks checkout in https://github.com/Automattic/woocommerce-payments/pull/9514

![image](https://github.com/user-attachments/assets/882c1176-253a-46f2-8c8d-9db96d8d9f70)

2024-10-14 14:54 UTC, gpressutto5 requested changes
| <img width="341" alt="image" src="https://github.com/user-attachments/assets/cd52fb58-15a5-4269-9c4d-43813b7846e1"> | <img width="345" alt="image" src="https://github.com/user-attachments/assets/f1ce7975-6162-4c29-a3e6-addec8dc9f91"> |
|-----|------|

Can we move the label to the text line when there's not enough space instead of changing the logo size? Like we do in the blocks checkout:

<img width="338" alt="image" src="https://github.com/user-attachments/assets/01819492-88dc-449b-84dd-b30a64dfd9fa">

2024-10-14 15:48 UTC, danielmx-dev commented
I pushed an update to push the badge if there is not horizontal space.

![image](https://github.com/user-attachments/assets/a9cfb7e0-f394-422a-8eed-1be0046b922f)

If there's enough space the badge will appear next to the payment method title
![image](https://github.com/user-attachments/assets/7e3e9edd-7b2d-421b-8944-3f02da20d5ed)

2024-10-14 18:12 UTC, danielmx-dev commented
There are some themes that do not hide the radio button like Storefront does (e.g. twenty twenty-four), which was causing issues with the layout. I have updated the styles to make sure the styles look good in that scenario.

![image](https://github.com/user-attachments/assets/af60c7a9-3519-4e7a-8337-f05c9cc72b91)

Since the payment methods other than card won't use the badge, I won't apply any of the new complex styles on them, to keep things simpler.

2024-10-14 18:19 UTC, gpressutto5 approved these changes
It looks great!

![image](https://github.com/user-attachments/assets/fbae7c40-3c63-43bf-b353-3c27c52c90e0)

2024-10-15 16:26 UTC, danielmx-dev commented
The alignment of the title was a bit off so I added a couple of commits to fix it. It should be fine now.

Storefront: 
![image](https://github.com/user-attachments/assets/dd49fb52-f5fa-460c-b47b-fc8af3723146)
![image](https://github.com/user-attachments/assets/04c5560b-d9d1-4cbf-af2b-feb85915ad6b)

Twenty twenty-four
![image](https://github.com/user-attachments/assets/edcbd75f-19ee-4bac-9575-d4a66e1c3620)

Twenty twenty-two
![image](https://github.com/user-attachments/assets/d2bebbb6-fbb7-4b88-874a-c655811b0fc5)

2024-10-15 17:34 UTC, merged