changed the URL and menu from Deposits to Payouts
Automattic/woocommerce-payments pull request #9530
Opened 2024-10-06 22:18 UTC by jessy-p

Fixes #9525 

### TODO:
- Fix snapshots 
- Old URLs should be redirected.

#### Changes proposed in this Pull Request
- Change the menu item under Payments to `Payouts`
- Change the URL to `/payouts` and `/payouts/details` 

#### Testing instructions
TBA

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-10-06 22:21 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9530` or branch name `fix/9525-menu-url-payouts-rename` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9525-menu-url-payouts-rename) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 25c5287bcd23bd1395a8e641ffcd97d0def3f8d4
- Build time: 2024-10-24 17:04:57 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-10-22 09:22 UTC, shendy-a8c requested changes
Great work, @jessy-p!

My feedbacks:
- I wonder if we should change 'deposit' in this [line](https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/client/index.js#L121) as well. What do you think?
- I still found some `/payments/deposits` that might need to be changed:
  - https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/client/components/deposits-overview/index.tsx#L91
  - https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/includes/class-wc-payments-onboarding-service.php#L658
  - https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/includes/class-wc-payments-onboarding-service.php#L858
  - https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/tests/e2e/utils/flows.js#L38
  - https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/tests/e2e-pw/specs/merchant/merchant-admin-deposits.spec.ts#L13
  - https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/tests/e2e-pw/specs/merchant/merchant-admin-deposits.spec.ts#L30
- This might need to be changed as well but I also created an [issue](https://github.com/Automattic/woocommerce-payments/issues/9598) that is dedicated for plugin URLs:
  - https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/client/components/deposits-overview/index.tsx#L222

2024-10-22 09:26 UTC, shendy-a8c commented on includes/admin/class-wc-payments-admin.php
> +	public function redirect_deposits_to_payouts() {
I wonder if redirect at the PHP layer is enough.

I see that Javascript navigation will result to an error.

https://github.com/user-attachments/assets/3af58bda-b19a-451c-8283-4e0ef2412c51

However, since you have changed all the `getDetailsURL()`, there should not be any Javascript navigation to the 'deposit' URLs. I could generate the error in my screen share by modifying locally like so on this [line](https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/client/deposits/list/index.tsx#L120):

```diff
-                               href={ getDetailsURL( deposit.id, 'payouts' ) }
+                               href={ getAdminUrl( {
+                                       page: 'wc-admin',
+                                       path: `/payments/deposits/details`,
+                                       id: deposit.id,
+                               } ) }
```

2024-10-23 16:33 UTC, jessy-p commented on includes/admin/class-wc-payments-admin.php
> +	public function redirect_deposits_to_payouts() {
Yes, the JS error should only happen if you do the following steps
1) Load the page
2) Make the change to URLs (i.e. apply this PR) but do not refresh the page
3) Make a JS navigation on the unrefreshed page.

I guess we can log a seperate issue for this if it needs to be addressed?

2024-10-23 16:36 UTC, jessy-p commented
> I wonder if we should change 'deposit' in this [line](https://github.com/Automattic/woocommerce-payments/blob/766de57db15fc1b868d9f29e303a29e34f278664/client/index.js#L121) as well. What do you think?

I refrained from changing anything that does not present to the user as it was not considered Must Have.

> I still found some /payments/deposits that might need to be changed:

Addressed the mentioned instances.

2024-10-24 04:59 UTC, shendy-a8c commented
> I refrained from changing anything that does not present to the user as it was not considered Must Have.

That's fair and I like that you are being strictly sticking to the plan =)

2024-10-24 05:02 UTC, shendy-a8c commented on includes/class-wc-payments-onboarding-service.php
> +		if ( false !== strpos( $referer, 'path=/payments/payouts' ) ) {
I don't fully understand what this is for but is it possible that the value of `$referer` is `path=/payments/deposits`?

If so, we might want to do an `or` here.

```suggestion
		if ( false !== strpos( $referer, 'path=/payments/deposits' ) || false !== strpos( $referer, 'path=/payments/payouts' ) ) {
```

2024-10-24 05:03 UTC, shendy-a8c commented
How about https://github.com/Automattic/woocommerce-payments/blob/4e2ef3a7be09a158a6ecad8507c0543262e6cc0a/includes/class-wc-payments-onboarding-service.php#L858 @jessy-p ? Have you checked that we need to change that, or add an 'or' there?

2024-10-24 05:05 UTC, shendy-a8c approved these changes
I left some feedback but this deserves an approval!

2024-10-25 05:39 UTC, merged