[Rebrand] Update Woo colors and logos
Automattic/woocommerce-payments pull request #9809
Opened 2024-11-25 20:59 UTC by leonardola

Fixes #9808

#### Changes proposed in this Pull Request

#### Testing instructions

**WooPay merchant churn modal**
- Checkout to this PR's branch in your merchant site
- Go to /wp-admin > Payments > Settings > WooPay 
- Disable WooPay
- Click Save
- The modal should show up 
- Make sure the logo was updated and the size is correct according to the figma file: 9Mk09c2GvJBVRW6hwjlOFo-fi-8_16223

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-11-25 21:07 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9809` or branch name `dev/update-woo-logos-and-colors` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=dev/update-woo-logos-and-colors) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 77a773fb415d1608cebf4aca70246fc432cb3ab3
- Build time: 2025-01-31 19:05:44 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-11-29 18:33 UTC, leonardola commented
Moving issues to the public repo

2024-12-02 20:17 UTC, alefesouza requested changes
In general everything looks good, but the WooPay logo on the express checkout button needs to be a little bigger, it needs to match the top of the `h` in `with`, and be big enough to stay below it:

| Figma | Current design |
|-|-|
|  <img width="539" alt="Screenshot 2024-12-02 at 4 52 54 PM" src="https://github.com/user-attachments/assets/e4fbbf86-aa29-473c-83bc-4912951c235d"> | <img width="403" alt="Screenshot 2024-12-02 at 4 53 26 PM" src="https://github.com/user-attachments/assets/4cf9e4ae-f674-4e83-bae4-394c6bf618dd"> |
| <img width="265" alt="Screenshot 2024-12-02 at 5 09 54 PM" src="https://github.com/user-attachments/assets/c010a2cd-e738-4400-b79a-1402d3cfc4e0"> | <img width="305" alt="Screenshot 2024-12-02 at 5 14 06 PM" src="https://github.com/user-attachments/assets/6aeca829-0131-41b5-92c4-5041bcf41098"> |

2024-12-04 20:10 UTC, leonardola commented
> In general everything looks good, but the WooPay logo on the express checkout button needs to be a little bigger, it needs to match the top of the h in with, and be big enough to stay below it:

@alefesouza fixed with 96972ccc7e17b7159d5a4a8f6478bd5160128208

2024-12-05 14:26 UTC, alefesouza approved these changes
The logo on the express button looks good now, thanks @leonardola 

<img width="806" alt="Screenshot 2024-12-05 at 11 18 37 AM" src="https://github.com/user-attachments/assets/433b80ef-b7f7-4e7c-81a8-7a25ba9f3875">

✅ The disable feedback WooPay modal has the updated logo.
✅ The payment logos are updated on the onboarding.
✅ The banner no longer appears on the WCPay settings.
✅ WooPay preview button color updated.
✅ The WooPay express checkout button has the new styles.

2024-12-05 15:28 UTC, alefesouza requested changes
Just noticed the button content is not fully centered, this is more noticeable on the blocks checkout cart page:

<img width="441" alt="Screenshot 2024-12-05 at 12 26 02 PM" src="https://github.com/user-attachments/assets/3259e1a8-8855-4a8f-8277-766302170a4b">

<img width="282" alt="Screenshot 2024-12-05 at 12 25 09 PM" src="https://github.com/user-attachments/assets/8af29b07-d246-4e41-b3e1-7b2f3fae5717">

2024-12-06 17:28 UTC, leonardola commented
@alefesouza I've fixed the buttons on with d992eb1cdb7b4b12a69e6a60c38dca00ff5acee9

2024-12-06 17:41 UTC, alefesouza approved these changes
The button content is centered now, thanks!

<img width="441" alt="Screenshot 2024-12-06 at 2 40 24 PM" src="https://github.com/user-attachments/assets/0d595d1c-9b98-4288-8998-d39052cf7a4b">

<img width="266" alt="Screenshot 2024-12-06 at 2 40 44 PM" src="https://github.com/user-attachments/assets/8e51f455-0134-4bdf-8bb6-513625b093c3">

2025-01-31 18:29 UTC, alefesouza requested changes
@leonardola recent changes looks good but the gap for payment method logos on the onboarding are bigger than expected on this branch.

| trunk | This branch |
|-|-|
| <img width="711" alt="Screenshot 2025-01-31 at 3 06 49 PM" src="https://github.com/user-attachments/assets/783f9e8a-8dd3-4839-9360-edf2af4c31b2" /> | <img width="711" alt="Screenshot 2025-01-31 at 3 08 30 PM" src="https://github.com/user-attachments/assets/55908b13-1a2a-49e6-9ee6-17b32004e701" /> |

2025-01-31 19:01 UTC, leonardola commented
@alefesouza fixed with 801b22802c5df740d478d194f594b030d0175885

2025-01-31 19:50 UTC, alefesouza approved these changes
The payment methods gap are right now.

2025-01-31 19:58 UTC, merged