Refresh page when ECE is dismissed
Automattic/woocommerce-payments pull request #9888
Opened 2024-12-05 19:19 UTC by rafaelzaleski

Fixes #9794 

#### Changes proposed in this Pull Request

Refresh the page when ECE is dismissed if the shipping information was updated from the payment sheet. This ensures that the shipping options on the cart and checkout pages are updated.

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-12-05 19:22 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9888` or branch name `fix/9794-refresh-page-when-ece-dismissed` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=fix/9794-refresh-page-when-ece-dismissed) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 9dd5e1dda26898761e3c0feb55b3edd30310bf97
- Build time: 2024-12-17 18:02:34 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-12-16 20:24 UTC, asumaran requested changes
@rafaelzaleski @pierorocca when using an address from the UK or Canada, the refresh doesn’t work correctly. It seems that for addresses in those countries, shipping methods cannot be calculated because the [full zip code cannot be retrieved](https://github.com/Automattic/woocommerce-payments/issues/9794#issuecomment-2535439454). It might be better to disable this new behavior for the UK, Canada, and any country where shipping options fail to load with the data provided by the payment sheet.

I also wanted to point out that the billing address is NOT being updated. If the customer has a previously saved address in the session, it remains unchanged even after updating the shipping address. While this might not be an issue, I thought it was worth mentioning to keep in mind.

2024-12-16 20:44 UTC, asumaran commented on client/tokenized-express-checkout/event-handlers.js
> +		return;
Can we add braces here?

2024-12-16 21:52 UTC, rafaelzaleski commented
@asumaran, I'm now bypassing `GB` and `CA` addresses. However, I noticed that these addresses are still being saved in the session with the redacted postcode when they fall under the "rest of the world" category. In this case, the postcode isn’t needed to calculate shipping options.

If the user refreshes the page, they’ll see the incorrect (redacted) address. 

The issue is that the Blocks API won't accept a redacted postcode for calculating shipping options, which is why a live refresh isn’t possible for CA and UK addresses.

2024-12-17 00:23 UTC, pierorocca commented
Asked on the Stripe slack channel if they know why the address is redacted and if that's expected. It's odd it only applied to some countries.

2024-12-17 01:14 UTC, asumaran requested changes
@rafaelzaleski I found a small discrepancy between the shortcode and block implementations. If the address is changed in the cart block page, it is correctly reflected on the cart page in both the block and shortcode pages.

However, on the shortcode Cart page, if we reopen the payment sheet and select the same address, the address changes once the dialog is closed. The state/county is removed. See the video for reference.

https://github.com/user-attachments/assets/dc4461bf-0a6e-4002-8f63-9637917d00e8

So far, this behavior seems to occur with a 🇵🇪 Peruvian address only. Addresses in Brazil and the US appear to work correctly. 

This can lead to unexpected behaviors** if we have specific rates for given city/county as it will appears the shipping options changes.

Here’s another video where the issue can be seen. In the payment sheet, the shipping rate shows $60, but after closing the payment sheet, the shipping rate changes to $5, which is the default rate for “Rest of the world” It should remain $60, which is the specific rate for “Municipalidad Metropolitana de Lima.”

https://github.com/user-attachments/assets/56fd1b1d-0fe5-41b7-9d1a-0596071bbdd8

I think it’s worth looking into what’s going on.

Other than that I left a couple of small comments for you so far. 

I haven't finished testing all the cases I wanted. I'll continue later.

2024-12-17 01:14 UTC, asumaran commented on client/express-checkout/event-handlers.js
> +		! [ 'CA', 'GB' ].includes( lastSelectedAddress.country )
Can we move this array, along with the accompanying comment, into a self-explanatory variable, either within this function or at a higher level? As this list will likely need to be updated with more countries in the future, using a variable name and relocating it would improve readability and maintainability.

2024-12-17 01:14 UTC, asumaran commented on client/tokenized-express-checkout/event-handlers.js
> +		! [ 'CA', 'GB' ].includes( lastSelectedAddress.country )
Same here. Let's put this array in a variable.

2024-12-17 01:14 UTC, asumaran commented on client/tokenized-express-checkout/utils/shipping-fields.js
> + */
Just curious: is it necessary to include this “external dependencies” comment even if we’re not importing a single module?

2024-12-17 12:05 UTC, rafaelzaleski commented
> Asked on the Stripe slack channel if they know why the address is redacted and if that's expected. It's odd it only applied to some countries.

@pierorocca, it looks like this is how Google Pay was implemented ([reference](https://developers.google.com/pay/api/web/reference/response-objects#IntermediateAddress)). I don’t think Stripe has control over this behavior.

I believe the redacted version (showing only the first few digits) is sufficient to calculate shipping costs for a specific region, which is the purpose of the intermediate address. However, proper support for calculating rates with partial postcodes would need to be added in Woo Core. Right now, we’re just hacking a workaround for this.

2024-12-17 12:09 UTC, rafaelzaleski commented on client/tokenized-express-checkout/event-handlers.js
> +		! [ 'CA', 'GB' ].includes( lastSelectedAddress.country )
Since this mirrors the code in the other file, I’ll wait until we complete the review process before copying the changes over to tokenized carts. You can focus your review on the code outside tokenized carts for now.

2024-12-17 14:08 UTC, rafaelzaleski commented
> So far, this behavior seems to occur with a 🇵🇪 Peruvian address only. Addresses in Brazil and the US appear to work correctly.

@asumaran, Peruvian states are coming through the payment sheet as full text instead of the abbreviated 3-letter code. I added a fallback to use the option text when the option value doesn’t match the payment sheet here: https://github.com/Automattic/woocommerce-payments/pull/9888/commits/08d18fcbe1a5d0c09749708d0bea8c5c1c834ba4

2024-12-17 17:27 UTC, asumaran approved these changes
Alright, I’ve tested this on the product and checkout pages (both shortcode and block-based), and everything is working as expected. 

The Peruvian address issue has been resolved.

However, the issue with addresses from countries affected by the zip code limitation still persists. Unfortunately, there’s not much we can do about it but the address isn’t refreshed as expected in those cases.

That said, I think the PR is good to go. Just make sure to apply the changes to the Tokenized Carts implementation. I’ve tested the happy path with the current changes, and it’s working fine there.

2024-12-17 17:27 UTC, asumaran commented on client/express-checkout/utils/shipping-fields.js
> +};
nice

2024-12-17 17:27 UTC, asumaran commented on client/express-checkout/utils/shipping-fields.js
> +	return country.length === 2 && [ 'CA', 'GB' ].includes( country );
Just curious, why are we checking the country name length here? Wouldn’t the `.includes` method be sufficient on its own?

2024-12-17 17:56 UTC, rafaelzaleski commented on client/express-checkout/utils/shipping-fields.js
> +	return country.length === 2 && [ 'CA', 'GB' ].includes( country );
It was initially to ensure we're receiving an alpha-2 ISO code, but you’re right—it's redundant with the array check. I've removed it [here](https://github.com/Automattic/woocommerce-payments/pull/9888/commits/20c4e424bbd3932e307fdb157a606a5e0cb6c55b).

2024-12-17 18:54 UTC, merged

2024-12-17 20:03 UTC, pierorocca commented
> @pierorocca, it looks like this is how Google Pay was implemented ([reference](https://developers.google.com/pay/api/web/reference/response-objects#IntermediateAddress)). I don’t think Stripe has control over this behavior.

>I believe the redacted version (showing only the first few digits) is sufficient to calculate shipping costs for a specific region, which is the purpose of the intermediate address. However, proper support for calculating rates with partial postcodes would need to be added in Woo Core. Right now, we’re just hacking a workaround for this.

I'm a little worried that there's so much information missing if the shopper exits and checks out using the form. It's more likely than not that the shopper will submit and encounter validation errors. My question is how is Shopify able to do that with the same Google Pay integration? I'm asking Stripe anyway in case this happens to be a gated feature.