Enable ECE for shipping subscriptions with free trial and sign up fee
Automattic/woocommerce-payments pull request #9955
Opened 2024-12-14 00:15 UTC by asumaran

Fixes #

#### Changes proposed in this Pull Request

#### Testing instructions

*

-------------------

- [ ] Run `npm run changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times. 
- [ ] Covered with tests (or have a good reason not to test in description ☝️)
- [ ] Tested on mobile (or does not apply)

**Post merge**

- [ ] Link to testing instructions from [release testing doc](https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions) following [these instructions](https://github.com/Automattic/woocommerce-payments/wiki/How-to-write-good-manual-testing-scenarios) : _Add link here / 'QA Testing Not Applicable'_
- [ ] Add or update [critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Critical-flows) and [testing instructions for critical flows](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows), if applicable.
- [ ] Add what's changed (description, screenshot, demo videos etc.) to the release announcement post, if applicable.

2024-12-14 00:19 UTC, botwoo commented
### Test the build 

#### Option 1. Jetpack Beta

- Install and activate [Jetpack Beta](https://jetpack.com/download-jetpack-beta/).
- Use this build by searching for PR number `9955` or branch name `as-fix-ece-shipping-subs-with-free-trial-and-sign-up-fee` in your-test.site/wp-admin/admin.php?page=jetpack-beta&plugin=woocommerce-payments          

#### Option 2. Jurassic Ninja - available for logged-in A12s

:rocket: [Launch a JN site with this branch](https://jurassic.ninja/create/?jetpack-beta&shortlived&nojetpack&woocommerce&woocommerce-payments-dev-tools&branches.woocommerce-payments=as-fix-ece-shipping-subs-with-free-trial-and-sign-up-fee) :rocket:

:information_source: Install this [Tampermonkey script](https://github.com/Automattic/woocommerce-payments/tree/develop/bin/wcpay-live-branches) to get more options.

---

Build info: 

- Latest commit: 558ca32e42c8e56a9e941a8c056cee70ffe1d58c
- Build time: 2025-01-03 01:52:08 UTC

_Note: the build is updated when a new commit is pushed to this PR._

2024-12-14 01:08 UTC, asumaran commented
@cesarcosta99 don't worry too much about the amounts in the payment sheet for now, as they'll be addressed later. It would be great if you could confirm that the amounts charged are correct.

2024-12-17 15:48 UTC, cesarcosta99 requested changes
Changes look good, however, I spotted two potential issues that require some attention, being one a failing test instruction:

- Verify ECE is enabled for case 4 ⚠️ 
  - Checkout succeeded with correct amount charged ✅ 
  - I found one issue where I clicked the ECE button for the first time, closed the payment sheet, then clicked on it again. I got a notice (see image) and the payment sheet didn't load again. Refreshing fixes the payment sheet state. I haven't checked whether this has been introduced in this PR (it doesn't seem like), but we gotta check and track this issue.
    <img width="473" alt="image" src="https://github.com/user-attachments/assets/28ab2f88-5218-4028-8cd2-356977caa5c3" />
- Verify ECE is enabled for case 12 ⚠️ 
  - Checkout succeeded with correct amount charged ✅ 
  - Same issue observed in case 4.
- Verify ECE is not enabled for Case 3 ✅ 
- Verify ECE is not enabled for Case 11 ❌
  - I created a variable subscription with a single variation, non-virtual, with a trial period and no fee, and in the product page the ECE button remains **visible** after selecting that variation.

2024-12-17 15:48 UTC, cesarcosta99 commented on client/express-checkout/index.js
> +							// https://github.com/Automattic/woocommerce-payments/issues/9771#issuecomment-2518829514
This works well, but I wonder if adding more details to this comment here could help others understand the logic more quickly. I think linking to the PR makes sense, but just to provide additional context, not using as the main source of documentation.

2024-12-17 15:48 UTC, cesarcosta99 commented on includes/express-checkout/class-wc-payments-express-checkout-button-helper.php
> +			// Note: This does not check variable subscriptions, as that will be handled on the frontend.
Same as above.

2024-12-17 15:54 UTC, asumaran commented
>I found one issue where I clicked the ECE button for the first time, closed the payment sheet, then clicked on it again. I got a notice (see image) and the payment sheet didn't load again. 

@cesarcosta99 I’ve also started experiencing the same behavior while testing [#9888](https://github.com/Automattic/woocommerce-payments/pull/9888). I’m going to run a `git bisect` to determine whether this issue was recently introduced or if it’s related to Google Pay.

2024-12-17 20:42 UTC, asumaran commented
>Verify ECE is not enabled for Case 11 ❌

@cesarcosta99 I’ve confirmed it’s working on my end—the button is hidden after selecting a variation. Could you double-check the subscription details? A video or screenshot would be super helpful.

> I got a notice (see image) and the payment sheet didn't load again.

I didn’t get the notice this time. I’ve updated my branch with develop just to be sure, but I’m seeing the same results. It doesn’t seem to be related to our codebase.

2024-12-17 21:19 UTC, asumaran commented
I've tested with a variable subscription with all variations (Cases 3, 4, 11, and 12) and I get expected results. Please @cesarcosta99 double check the Case 11 please.

2024-12-18 16:49 UTC, cesarcosta99 commented
>double check the Case 11 please.

@asumaran, case 11 passed after merging `develop` 🎉  However, the other issue I reported (payment sheet not displaying) persists.

2024-12-18 21:30 UTC, asumaran commented
>I found one issue where I clicked the ECE button for the first time, closed the payment sheet, then clicked on it again. I got a notice (see image) and the payment sheet didn't load again.

@cesarcosta99, thank you for identifying this issue. Pinpointing the problem has been a bit tedious. This error occurs when the response from `/?wc-ajax=wcpay_ece_get_shipping_options` returns a `total.amount` lower than the value with which ECE was initially initialized. It seems the free trial is impacting the total calculation, causing it to be lower than expected.

I’m not entirely sure how to resolve this yet, as it’s affecting both regular and variable subscriptions. I’ll look into this further and see what we can do. FYI @bborman22

2024-12-18 23:32 UTC, asumaran commented
@cesarcosta99 I've uploaded a [_fix_](https://github.com/Automattic/woocommerce-payments/pull/9955/commits/4f4554ae198d856072b0a232782f9ad79c8aae44) for the Google Pay issue, but I’d like to run tests across all subscription scenarios before you review it again.

2024-12-20 01:15 UTC, asumaran commented
@cesarcosta99, I’ve verified that ECE works correctly in all cases and that the Google Pay issue is not present in any scenario. However, I think we should wait a bit longer before finalizing the review of this PR, as @mattallan has [commented](https://github.com/Automattic/woocommerce-subscriptions-core/pull/746#issuecomment-2552795073) on my PR in WC Subscriptions Core, pointing out that my changes introduce some errors. I need to fix those before proceeding with the review of this PR.

@bborman22, I'll work on fixing the issues I'm introducing in WC Subscriptions Core, but I think it would be helpful if someone from the team maintaining it could assist. I'm not an expert on subscriptions, and these errors involve scenarios I hadn't considered. Someone with more experience in WC Subscriptions Core could likely resolve this faster.

For now, I’m setting the PR back to draft until the issues in WC Subscriptions Core are resolved.

FYI: @pierorocca

2025-01-07 18:33 UTC, asumaran commented
Since the implementation of Tokenized Carts for Express Checkouts is now the default implementation, and the files from the previous implementation [have been removed](https://github.com/Automattic/woocommerce-payments/pull/10058/), I have created another [PR](https://github.com/Automattic/woocommerce-payments/pull/10099) enabling ECE for subscriptions that require shipping and also include a free trial and a sign-up fee.

Closing this in favor of https://github.com/Automattic/woocommerce-payments/pull/10099

2025-01-07 18:33 UTC, closed without merging